; branch-free probe of X:0xf000   (generated by tools/gen_probe.py)
; init: stamp the mask.  process: read it back and apply it.
init:
        move    #>$e00000,x0
        move    x0,x:>$f000
        rts
proc:
        move    x:>$f000,y0
        move    r0,r1
        do      n7,>loopend
        move    x:(r0)+,a
        move    x:(r0)+,b
        and     y0,a
        and     y0,b
        move    a,x:(r1)+
        move    b,x:(r1)+
loopend:
        rts
