; ---------------------------------------------------------------------------
; reverb v18 -- generated by tools/gen_reverb.py, do not hand-edit
;
; Four series allpasses into a four-line FDN with a 4x4 Hadamard, one-pole
; damping inside the feedback path, and interpolated modulation on two lines.
;
; Sized against the measured end of Y memory at 0xC000:
;   lines      Y:0x01000 .. 0x04fff   4096 words each (93 ms)
;              taps 3121 2477 1949 1453  (71 56 44 33 ms)
;   allpasses  Y:0x05000 .. 0x06fff   2048 words each
;              taps 1051 773 557 379  (24 18 13 9 ms)
;   free       Y:0x7000 .. 0xBFFF  (20K words, 465 ms) for the pre-delay
;
; The allpasses are long on purpose. Four lines at ~50 ms is only ~80 echoes a
; second, which on its own reads as a stutter rather than a wash; the density
; has to come from diffusion, so the allpasses run 9-24 ms instead of the 3-8 ms
; they were when the whole engine had to fit in 6K.
;
; State:
;   r7+$83        write phase (persistent, masked on load as well as save)
;   Y:0x7a1        shared allpass phase
;   Y:0x7a2        LFO phase
;   Y:0x7f0..0x7f3  damping states
;   r7+$55..$66   per-sample scratch
;
; Parameters:
;   p0 TIME -> feedback, 0.875 .. 0.999
;   p1 DAMP -> one-pole coefficient. s += c*(d-s), so a LARGE c keeps highs.
;              DAMP up lowers c: 0 = bright, 127 = dark.
;   p5 MIX  -> wet gain
; ---------------------------------------------------------------------------

init:
; No loop, and nothing reset that has to survive: this runs far more often than
; once per effect selection.
        move    #>$ffffff,m0
        move    #>$ffffff,m1
        move    #>$ffffff,m2
        move    #>$ffffff,m3
        move    #>$ffffff,m4
        move    #>$ffffff,m5
        rts

proc:
; ---- rebuild the four delay pointers from the saved phase ----------------
        move    x:(r7+$83),a
        move    #>$fff,x0
        and     x0,a                    ; mask on LOAD: the phase may be garbage
        move    #>$1000,x0
        add     x0,a
        move    a,r1                    ; line 0  Y:0x01000
        add     x0,a
        move    a,r2                    ; line 1  Y:0x02000
        add     x0,a
        move    a,r3                    ; line 2  Y:0x03000
        add     x0,a
        move    a,r4                    ; line 3  Y:0x04000
        move    #>$fff,m1
        move    #>$fff,m2
        move    #>$fff,m3
        move    #>$fff,m4
        move    #>$fff3cf,n1            ; -3121
        move    #>$fff653,n2            ; -2477
        move    #>$fff863,n3            ; -1949
        move    #>$fffa53,n4            ; -1453
        move    #>$ffffff,m0            ; audio read AND written in place via r0
        move    #>$ffffff,m5

; ---- feedback gain from TIME --------------------------------------------
; p0 arrives as value<<16. g/2 spans 0.4375..0.4995, so g spans 0.875..0.999.
; The 4x4 Hadamard has row norm 2, so folding the half into the gain makes the
; matrix orthonormal and the loop gain equal to g.
        move    x:(r6),x0
        move    #>$080000,y1
        mpy     x0,y1,a
        move    #>$380000,x0
        add     x0,a
        move    a,x:(r7+$5e)

; ---- DAMP: p1 -> damping coefficient ------------------------------------
        move    x:(r6+$1),x0
        move    #>$700000,y1
        mpy     x0,y1,a
        move    #>$7fffff,b
        sub     a,b
        move    b,x:(r7+$5f)

; ---- MIX: p5 -> wet gain ------------------------------------------------
        move    x:(r6+$5),x0
        move    x0,x:(r7+$60)

        do      n7,>rvend

; ---- input: mono sum -----------------------------------------------------
        move    #>$1,n0
        move    x:(r0),a
        move    x:(r0+n0),x0
        add     x0,a
        asr     #$1,a,a
        move    a,x:(r7+$5b)            ; into the diffuser

; -- allpass 0: Y:0x05000, tap 1051 (23.8 ms) --
        move    y:>$7a1,a
        move    #>997,x0
        add     x0,a
        move    #>$7ff,x0
        and     x0,a                    ; (phase - tap) mod 2048
        move    #>$5000,x0
        add     x0,a
        move    a,r5
        move    #>$400000,y0            ; coefficient, and fills the AGU slot
        move    y:(r5),b                ; d
        move    b,x0
        mpy     x0,y0,a
        move    x:(r7+$5b),x0
        add     x0,a                    ; v = x + g*d
        move    a,x:(r7+$5c)
        move    a,x1
        mpy     x1,y0,a
        sub     a,b                     ; out = d - g*v
        move    b,x:(r7+$5b)
        move    y:>$7a1,a         ; write v at base + phase
        move    #>$5000,x0
        add     x0,a
        move    a,r5
        move    x:(r7+$5c),a            ; reload v, fills the AGU slot
        move    a,y:(r5)

; -- allpass 1: Y:0x05800, tap 773 (17.5 ms) --
        move    y:>$7a1,a
        move    #>1275,x0
        add     x0,a
        move    #>$7ff,x0
        and     x0,a                    ; (phase - tap) mod 2048
        move    #>$5800,x0
        add     x0,a
        move    a,r5
        move    #>$400000,y0            ; coefficient, and fills the AGU slot
        move    y:(r5),b                ; d
        move    b,x0
        mpy     x0,y0,a
        move    x:(r7+$5b),x0
        add     x0,a                    ; v = x + g*d
        move    a,x:(r7+$5c)
        move    a,x1
        mpy     x1,y0,a
        sub     a,b                     ; out = d - g*v
        move    b,x:(r7+$5b)
        move    y:>$7a1,a         ; write v at base + phase
        move    #>$5800,x0
        add     x0,a
        move    a,r5
        move    x:(r7+$5c),a            ; reload v, fills the AGU slot
        move    a,y:(r5)

; -- allpass 2: Y:0x06000, tap 557 (12.6 ms) --
        move    y:>$7a1,a
        move    #>1491,x0
        add     x0,a
        move    #>$7ff,x0
        and     x0,a                    ; (phase - tap) mod 2048
        move    #>$6000,x0
        add     x0,a
        move    a,r5
        move    #>$400000,y0            ; coefficient, and fills the AGU slot
        move    y:(r5),b                ; d
        move    b,x0
        mpy     x0,y0,a
        move    x:(r7+$5b),x0
        add     x0,a                    ; v = x + g*d
        move    a,x:(r7+$5c)
        move    a,x1
        mpy     x1,y0,a
        sub     a,b                     ; out = d - g*v
        move    b,x:(r7+$5b)
        move    y:>$7a1,a         ; write v at base + phase
        move    #>$6000,x0
        add     x0,a
        move    a,r5
        move    x:(r7+$5c),a            ; reload v, fills the AGU slot
        move    a,y:(r5)

; -- allpass 3: Y:0x06800, tap 379 (8.6 ms) --
        move    y:>$7a1,a
        move    #>1669,x0
        add     x0,a
        move    #>$7ff,x0
        and     x0,a                    ; (phase - tap) mod 2048
        move    #>$6800,x0
        add     x0,a
        move    a,r5
        move    #>$400000,y0            ; coefficient, and fills the AGU slot
        move    y:(r5),b                ; d
        move    b,x0
        mpy     x0,y0,a
        move    x:(r7+$5b),x0
        add     x0,a                    ; v = x + g*d
        move    a,x:(r7+$5c)
        move    a,x1
        mpy     x1,y0,a
        sub     a,b                     ; out = d - g*v
        move    b,x:(r7+$5b)
        move    y:>$7a1,a         ; write v at base + phase
        move    #>$6800,x0
        add     x0,a
        move    a,r5
        move    x:(r7+$5c),a            ; reload v, fills the AGU slot
        move    a,y:(r5)

        move    y:>$7a1,a         ; advance the shared allpass phase
        move    #>$1,x0
        add     x0,a
        move    #>$7ff,x0
        and     x0,a
        move    a,y:>$7a1
        move    x:(r7+$5b),a
        move    a,x:(r7+$55)            ; diffused input -> tank
        asr     #$1,a,a
        move    a,x:(r7+$67)            ; and at half, for the other three lines

; ---- LFO: one triangle and its inverse ----------------------------------
        move    y:>$7a2,a         ; persistent phase, [0,$7fffff]
        move    #>$0000a0,x0
        add     x0,a
        move    #>$7fffff,x0
        and     x0,a                    ; wrap; A1 is right even if A2 carried
        move    a1,x0                   ; extract without saturating on A2
        move    x0,y:>$7a2
        move    x0,a                    ; clean copy, A2 = 0
        move    #>$400000,x0
        sub     x0,a
        abs     a                       ; triangle T, 0 .. $400000
        move    a1,x0
        move    x0,x:(r7+$66)           ; stash for the inverse
        move    a1,x1                   ; T
        asl     #$5,a,a
        move    a2,x0
        move    x0,x:(r7+$61)     ; line 1: integer offset, 0..8
        move    x1,a                    ; T again, A2 = 0 because T is positive
        move    #>$07ffff,x0
        and     x0,a
        asl     #$4,a,a                 ; fraction, at most $7ffff0 -> positive
        move    a,x0
        move    x0,x:(r7+$62)
        move    #>$400000,a
        move    x:(r7+$66),x0
        sub     x0,a                    ; inverse triangle
        move    a1,x1                   ; T
        asl     #$5,a,a
        move    a2,x0
        move    x0,x:(r7+$63)     ; line 2: integer offset, 0..8
        move    x1,a                    ; T again, A2 = 0 because T is positive
        move    #>$07ffff,x0
        and     x0,a
        asl     #$4,a,a                 ; fraction, at most $7ffff0 -> positive
        move    a,x0
        move    x0,x:(r7+$64)

; ---- four taps, damped inside the feedback path -------------------------
        move    x:(r7+$5f),y0           ; damping coefficient, from DAMP
        move    y:(r1+n1),a         ; line 0, fixed tap 3121
        move    y:>$7f0,b
        sub     b,a
        move    a,x0
        mpy     x0,y0,a
        add     b,a
        move    a,y:>$7f0
        move    a,x:(r7+$56)

; -- line 1 modulated: Y:0x02000, tap 2477, interpolated --
        move    r1,b
        move    #>$fff,x0
        and     x0,b                    ; shared write phase
        move    x:(r7+$61),x0
        sub     x0,b                    ; phase - offset
        move    #>1619,x0
        add     x0,b
        move    #>$fff,x0
        and     x0,b                    ; i0
        move    b,a
        add     x0,a
        and     x0,a                    ; i1 = (i0-1) mod 4096
        move    #>$2000,x0
        add     x0,b
        add     x0,a
        move    a,x1
        move    b,r5
        move    x:(r7+$62),y1     ; fraction -- y1, NOT y0: y0 holds DAMP
        move    x1,a
        move    y:(r5),b                ; d0
        move    a,r5
        move    b,x:(r7+$65)
        move    b,x0                    ; both fill the AGU slot
        move    y:(r5),a                ; d1
        sub     x0,a
        move    a,x0
        mpy     x0,y1,a                 ; f*(d1-d0)
        move    x:(r7+$65),x0
        add     x0,a                    ; interpolated tap
        move    y:>$7f1,b
        sub     b,a
        move    a,x0
        mpy     x0,y0,a
        add     b,a
        move    a,y:>$7f1
        move    a,x:(r7+$57)

; -- line 2 modulated: Y:0x03000, tap 1949, interpolated --
        move    r1,b
        move    #>$fff,x0
        and     x0,b                    ; shared write phase
        move    x:(r7+$63),x0
        sub     x0,b                    ; phase - offset
        move    #>2147,x0
        add     x0,b
        move    #>$fff,x0
        and     x0,b                    ; i0
        move    b,a
        add     x0,a
        and     x0,a                    ; i1 = (i0-1) mod 4096
        move    #>$3000,x0
        add     x0,b
        add     x0,a
        move    a,x1
        move    b,r5
        move    x:(r7+$64),y1     ; fraction -- y1, NOT y0: y0 holds DAMP
        move    x1,a
        move    y:(r5),b                ; d0
        move    a,r5
        move    b,x:(r7+$65)
        move    b,x0                    ; both fill the AGU slot
        move    y:(r5),a                ; d1
        sub     x0,a
        move    a,x0
        mpy     x0,y1,a                 ; f*(d1-d0)
        move    x:(r7+$65),x0
        add     x0,a                    ; interpolated tap
        move    y:>$7f2,b
        sub     b,a
        move    a,x0
        mpy     x0,y0,a
        add     b,a
        move    a,y:>$7f2
        move    a,x:(r7+$58)

        move    y:(r4+n4),a         ; line 3, fixed tap 1453
        move    y:>$7f3,b
        sub     b,a
        move    a,x0
        mpy     x0,y0,a
        add     b,a
        move    a,y:>$7f3
        move    a,x:(r7+$59)

; ---- 4x4 Hadamard: adds and subtracts only ------------------------------
        move    x:(r7+$57),x0
        move    x:(r7+$56),a
        add     x0,a
        move    a,x:(r7+$5a)            ; u0 = d0+d1
        move    x:(r7+$56),a
        sub     x0,a
        move    a,x:(r7+$5b)            ; u1 = d0-d1
        move    x:(r7+$59),x0
        move    x:(r7+$58),a
        add     x0,a
        move    a,x:(r7+$5c)            ; u2 = d2+d3
        move    x:(r7+$58),a
        sub     x0,a
        move    a,x:(r7+$5d)            ; u3 = d2-d3

; ---- feedback and write back --------------------------------------------
        move    x:(r7+$5e),y0           ; g/2
        move    x:(r7+$5c),x0
        move    x:(r7+$5a),a
        add     x0,a
        move    a,x0
        mpy     x0,y0,a
        move    x:(r7+$55),x0           ; diffused input
        add     x0,a
        move    a,y:(r1)+

        move    x:(r7+$5d),x0
        move    x:(r7+$5b),a
        add     x0,a
        move    a,x0
        mpy     x0,y0,a
        move    x:(r7+$55),x0           ; diffused input
        sub     x0,a
        move    a,y:(r2)+

        move    x:(r7+$5c),x0
        move    x:(r7+$5a),a
        sub     x0,a
        move    a,x0
        mpy     x0,y0,a
        move    x:(r7+$67),x0           ; diffused input, half
        sub     x0,a
        move    a,y:(r3)+

        move    x:(r7+$5d),x0
        move    x:(r7+$5b),a
        sub     x0,a
        move    a,x0
        mpy     x0,y0,a
        move    x:(r7+$67),x0           ; diffused input, half
        add     x0,a
        move    a,y:(r4)+

; ---- wet added to dry, two tank taps per channel -------------------------
        move    x:(r7+$60),y1           ; wet gain
        move    x:(r7+$57),a            ; line 1, tap 2477
        move    x:(r7+$58),x0           ; line 2, tap 1949
        add     x0,a
        asr     #$1,a,a
        move    a,x0
        mpy     x0,y1,a
        move    x:(r0),x0
        add     x0,a
        move    a,x:(r0)                ; L in place
        move    x:(r7+$56),a            ; line 0, tap 3121
        move    x:(r7+$59),x0           ; line 3, tap 1453
        add     x0,a
        asr     #$1,a,a
        move    a,x0
        mpy     x0,y1,a
        move    x:(r0+n0),x0
        add     x0,a
        move    a,x:(r0+n0)                ; R in place
        move    #>$2,n0
        move    (r0)+n0                 ; advance one stereo frame
rvend:

; ---- save the phase, restore the M registers ----------------------------
        move    r1,a
        move    #>$fff,x0
        and     x0,a
        move    a,x:(r7+$83)
        move    #>$ffffff,m0
        move    #>$ffffff,m1
        move    #>$ffffff,m2
        move    #>$ffffff,m3
        move    #>$ffffff,m4
        move    #>$ffffff,m5
        rts
