; ---------------------------------------------------------------------------
; v41 -- generated by tools/gen_reverb.py, do not hand-edit
;
; Four series allpasses into a four-line FDN with a 4x4 Hadamard, one-pole
; damping inside the feedback path, and interpolated modulation on two lines.
;
; All buffers are relative to the per-instance base at x:(x:>$213), so two
; tracks running this effect do not write through each other. An FX2 instance is
; given 0x4000 words:
;   lines      base+0x0000 .. base+0x1fff   2048 words each
;              taps 1567 1249 977 733  (36 28 22 17 ms)
;   allpasses  base+0x2000 .. base+0x2fff   1024 words each
;              taps 907 673 487 331  (21 15 11 8 ms)
;   pre-delay  base+0x3000 .. base+0x37ff   2048 words (46 ms)
;   total      0x3800 of the 0x4000 an FX2 instance is given
;
; The allpasses are long on purpose. Four lines at ~50 ms is only ~80 echoes a
; second, which on its own reads as a stutter rather than a wash; the density
; has to come from diffusion, so the allpasses run 9-24 ms instead of the 3-8 ms
; they were when the whole engine had to fit in 6K.
;
; State (all in the per-instance r7 block, not absolute Y):
;   r7+$83        write phase (persistent, masked on load as well as save)
;   r7+$83        the ONE persistent word: tank / allpass / pre-delay phase
;   base+0x3800   LFO phase and 4 damping states, loaded per block
;   r7+$31..$78   this instance's base, and the bases derived from it
;   r7+$15..$66   per-sample scratch
;
; Parameters:
;   p0 TIME -> feedback, 0.875 .. 0.999
;   p1 DAMP -> one-pole coefficient. s += c*(d-s), so a LARGE c keeps highs.
;              DAMP up lowers c: 0 = bright, 127 = dark.
;   p5 MIX  -> wet gain
; ---------------------------------------------------------------------------

init:
; No loop, and nothing reset that has to survive.
;
; Reading X:$213 is only valid HERE. Stash the base where process can
; find it: absolute Y, but at an address unique to this instance.
        move    x:>$213,r4
        move    r7,a
        asr     #$8,a,a                 ; r7 >> 8; also fills the AGU slot
        move    x:(r4),x0               ; this instance's buffer base
        move    #>$800,y0
        add     y0,a
        move    a,r5
        move    #>$ffffff,m5
        move    #>$ffffff,m0            ; both fill the AGU slot
        move    x0,y:(r5)
        move    #>$ffffff,m5
        move    #>$ffffff,m0
        move    #>$ffffff,m1
        move    #>$ffffff,m2
        move    #>$ffffff,m3
        move    #>$ffffff,m4
        rts

proc:
; ---- this instance's buffer base ----------------------------------------
; X:$213 points at this instance's entry in the base table, but ONLY
; during init: the dispatcher advances it per effect, so by the time blocks are
; running it sits wherever the last init left it. With one effect loaded that
; happens to still be a valid FX2 slot, which is why reading it in process
; (v33) worked on one track and hung on two -- both instances then read the SAME
; entry and one of them wrote 14K words through memory it does not own.
;
; So read it in init and carry it across in the per-instance stash. See the
; STASH note above for why the address moved from 0x735 to 0x800.
;
; Deriving it instead as x:(0x255 + ((r7 - 0x6000) >> 8)) does not work:
; measured, r7 = 0x6200 while the base is table[1], not table[2].
        move    r7,a
        move    #>$ffffff,m0            ; audio is read and written via r0
        asr     #$8,a,a
        move    #>$800,y0
        add     y0,a
        move    a,r5
        move    #>$7ff,m1     ; both fill the AGU slot
        move    #>$ffffff,m5
        move    y:(r5),x0               ; the base init stashed for us
        move    x0,x:(r7+$31)

; ---- refuse to run on a slot that cannot hold the layout -----------------
; The bump allocator advances ONE entry per EFFECT, of any type, so which table
; entry we get depends on how many effects the project loaded before us -- not
; on how many reverbs. Of the eight entries only two can hold this layout:
;
;   0x1000 0x1c00 0x2800 0x3400   FX1 slots, 0xc00 words. A 0x3800-word
;                                 layout here runs through the neighbouring
;                                 buffers and into FX2 slot 0.
;   0x4000 0x8000                 FX2 slots, 0x4000 words. The only safe ones.
;   0x30000 0x34000               past the end of Y, which stops at 0xC000.
;                                 dsp/ymemprobe.asm hangs when it writes there.
;
; So check, and pass audio through untouched if the slot is not ours. A dry
; track is a diagnosis; a hung machine is not. y0/b are used rather than x0/a
; because the block below needs x0 to still hold the base.
        move    x:(r7+$31),b
        move    #>$4000,y0
        cmp     y0,b
        blt     dry
        move    #>$8801,y0
        cmp     y0,b
        bge     dry

; ---- every buffer base, derived once per block --------------------------
        move    #>$2000,a
        add     x0,a
        move    a,x:(r7+$32)
        move    #>$2400,a
        add     x0,a
        move    a,x:(r7+$33)
        move    #>$2800,a
        add     x0,a
        move    a,x:(r7+$34)
        move    #>$2c00,a
        add     x0,a
        move    a,x:(r7+$35)
        move    #>$800,a
        add     x0,a
        move    a,x:(r7+$36)
        move    #>$1000,a
        add     x0,a
        move    a,x:(r7+$37)
        move    #>$3000,a
        add     x0,a
        move    a,x:(r7+$38)

; ---- per-block: load the state that cannot be derived -------------------
; The LFO phase and the four one-pole states are the only things that must
; survive between calls and cannot be recomputed. They live in the instance's
; own Y region, so they are per-instance, and touching them once per block costs
; nothing per sample.
        move    #>$3800,a
        add     x0,a
        move    a,x:(r7+$3f)            ; keep the address for the save
        move    a,r5
        move    #>$ffffff,m5            ; linear for the walk
        move    x:(r7+$31),x0           ; base again; fills the AGU slot after r5
        move    y:(r5)+,a
        move    a,x:(r7+$3e)
        move    y:(r5)+,a
        move    a,x:(r7+$3a)
        move    y:(r5)+,a
        move    a,x:(r7+$3b)
        move    y:(r5)+,a
        move    a,x:(r7+$3c)
        move    y:(r5)+,a
        move    a,x:(r7+$3d)

; ---- rebuild the four delay pointers from the saved phase ----------------
        move    x:(r7+$83),a
        move    #>$7ff,x0
        and     x0,a                    ; mask on LOAD: the phase may be garbage
        move    x:(r7+$31),x0
        add     x0,a                    ; base + LINE_OFF(0x0)
        move    a,r1                    ; line 0
        move    #>$800,x0
        add     x0,a
        move    a,r2                    ; line 1
        add     x0,a
        move    a,r3                    ; line 2
        add     x0,a
        move    a,r4                    ; line 3
        move    #>$7ff,m1
        move    #>$7ff,m2
        move    #>$7ff,m3
        move    #>$7ff,m4

; ---- fixed taps: no parameter reaches an address ------------------------
        move    #>$fff9e1,n1         ; -1567, line 0 reads y:(r1+n1)
        move    #>$fffb1f,n2         ; -1249, line 1 reads y:(r2+n2)
        move    #>$fffc2f,n3         ; -977, line 2 reads y:(r3+n3)
        move    #>$fffd23,n4         ; -733, line 3 reads y:(r4+n4)
        move    #>$ffffff,m5           ; pre-delay modulo. Harmless to the
                                        ; diffuser: it only ever does plain
                                        ; y:(r5), never a post-increment, and
                                        ; modulo affects updates, not reads.

; ---- feedback gain from TIME --------------------------------------------
; p0 arrives as value<<16. The 4x4 Hadamard has row norm 2, so folding the half
; into the gain makes the matrix orthonormal and the loop gain equal to g.
;
; g now spans 0.935..0.9995, not 0.875..0.999. Decay is g^n where n is passes,
; so RT60 scales with the loop time -- and fitting a real 16K allocation halved
; the mean tap from ~51 ms to ~26 ms, which halved every decay time and made
; TIME feel like it had stopped doing anything. g_new = g_old^0.5 restores the
; old RT60 range over the same knob travel.
        move    x:(r6),x0
        move    #>$043000,y1
        mpy     x0,y1,a
        move    #>$3bd000,x0
        add     x0,a
        move    a,x:(r7+$1e)

; ---- HI: high cut, as an EQ rather than a damping amount -----------------
; The one-pole is s += c*(d-s), so a LARGE c tracks the input and keeps highs.
; HI reads as an EQ control, so it has to run the other way from the old DAMP:
; HI=0 gives c=0.125 (dark), HI=127 gives c~0.99 (bright).
        move    x:(r6+$1),x0
        move    #>$700000,y1
        mpy     x0,y1,a
        move    #>$100000,x0
        add     x0,a
        move    a,x:(r7+$1f)

; ---- MIX -----------------------------------------------------------------
        move    x:(r6+$5),x0
        move    x0,x:(r7+$20)

; ---- MOD: modulation depth, scales the LFO triangle ---------------------
        move    x:(r6+$4),x0
        move    x0,x:(r7+$28)

; ---- WIDTH: 0 = mono, 127 = full stereo ---------------------------------
        move    x:(r6+$b),x0
        move    x0,x:(r7+$2c)

; ---- RATE: LFO increment, ~0.34 Hz .. ~3 Hz -----------------------------
; 8x what it would be per sample, because the LFO is stepped once per block.
        move    x:(r6+$d),a
        asr     #$b,a,a
        move    #>$200,x0
        add     x0,a
        move    a,x:(r7+$2f)


        do      n7,>rvend

; ---- input: mono sum -----------------------------------------------------
        move    #>$1,n0
        move    x:(r0),a
        move    x:(r0+n0),x0
        add     x0,a
        asr     #$1,a,a
        move    a,x:(r7+$1b)
        move    r1,a                    ; the allpass phase IS the tank phase:
        move    #>$3ff,x0       ; both advance by 1 a sample, and the
        and     x0,a                    ; line base is aligned, so r1 masked is it
        move    a,x:(r7+$39)


        move    x:(r7+$1b),a
        move    a,x:(r7+$15)            ; diffused input -> tank
        asr     #$1,a,a
        move    a,x:(r7+$27)            ; and at half, for the other three lines

; ---- four taps, damped inside the feedback path -------------------------
        move    x:(r7+$1f),y0           ; damping coefficient, from DAMP
        clr     a                       ; line 0 NOT READ -- no buffer traffic
        move    x:(r7+$3a),b
        sub     b,a
        move    a,x0
        mpy     x0,y0,a
        add     b,a
        move    a,x:(r7+$3a)
        move    a,x:(r7+$16)

        clr     a                       ; line 1 NOT READ -- no buffer traffic
        move    x:(r7+$3b),b
        sub     b,a
        move    a,x0
        mpy     x0,y0,a
        add     b,a
        move    a,x:(r7+$3b)
        move    a,x:(r7+$17)

        clr     a                       ; line 2 NOT READ -- no buffer traffic
        move    x:(r7+$3c),b
        sub     b,a
        move    a,x0
        mpy     x0,y0,a
        add     b,a
        move    a,x:(r7+$3c)
        move    a,x:(r7+$18)

        clr     a                       ; line 3 NOT READ -- no buffer traffic
        move    x:(r7+$3d),b
        sub     b,a
        move    a,x0
        mpy     x0,y0,a
        add     b,a
        move    a,x:(r7+$3d)
        move    a,x:(r7+$19)

; ---- 4x4 Hadamard: adds and subtracts only ------------------------------
        move    x:(r7+$17),x0
        move    x:(r7+$16),a
        add     x0,a
        move    a,x:(r7+$1a)            ; u0 = d0+d1
        move    x:(r7+$16),a
        sub     x0,a
        move    a,x:(r7+$1b)            ; u1 = d0-d1
        move    x:(r7+$19),x0
        move    x:(r7+$18),a
        add     x0,a
        move    a,x:(r7+$1c)            ; u2 = d2+d3
        move    x:(r7+$18),a
        sub     x0,a
        move    a,x:(r7+$1d)            ; u3 = d2-d3

; ---- feedback and write back --------------------------------------------
        move    x:(r7+$1e),y0           ; g/2
        move    x:(r7+$1c),x0
        move    x:(r7+$1a),a
        add     x0,a
        move    a,x0
        mpy     x0,y0,a
        move    x:(r7+$15),x0           ; diffused input
        add     x0,a
        move    (r1)+                 ; advance only -- nothing written

        move    x:(r7+$1d),x0
        move    x:(r7+$1b),a
        add     x0,a
        move    a,x0
        mpy     x0,y0,a
        move    x:(r7+$15),x0           ; diffused input
        sub     x0,a
        move    (r2)+                 ; advance only -- nothing written

        move    x:(r7+$1c),x0
        move    x:(r7+$1a),a
        sub     x0,a
        move    a,x0
        mpy     x0,y0,a
        move    x:(r7+$27),x0           ; diffused input, half
        sub     x0,a
        move    (r3)+                 ; advance only -- nothing written

        move    x:(r7+$1d),x0
        move    x:(r7+$1b),a
        sub     x0,a
        move    a,x0
        mpy     x0,y0,a
        move    x:(r7+$27),x0           ; diffused input, half
        add     x0,a
        move    (r4)+                 ; advance only -- nothing written

; ---- wet added to dry, two tank taps per channel -------------------------
        move    x:(r7+$20),y1           ; wet gain
        move    x:(r7+$17),a            ; line 1, tap 1249
        move    x:(r7+$18),x0           ; line 2, tap 977
        add     x0,a
        asr     #$1,a,a
        move    a,x:(r7+$2d)            ; wet L
        move    x:(r7+$16),a            ; line 0, tap 1567
        move    x:(r7+$19),x0           ; line 3, tap 733
        add     x0,a
        asr     #$1,a,a
        move    a,x:(r7+$2e)            ; wet R

; ---- WIDTH: mid/side, then MIX, then onto the dry -----------------------
; M = (L+R)/2, S = (L-R)/2, out = M +/- w*S. w=0 collapses to mono, w=1 gives
; back exactly the two tap sums.
        move    x:(r7+$2d),a
        move    x:(r7+$2e),x0
        add     x0,a
        asr     #$1,a,a
        move    a,x:(r7+$25)            ; M
        move    x:(r7+$2d),a
        sub     x0,a
        asr     #$1,a,a
        move    a,x0
        move    x:(r7+$2c),y0           ; WIDTH
        mpy     x0,y0,a
        move    a,x:(r7+$26)            ; w*S
        move    x:(r7+$25),a
        move    x:(r7+$26),x0
        add     x0,a
        move    a,x0
        mpy     x0,y1,a                 ; * MIX
        move    x:(r0),x0
        add     x0,a
        move    a,x:(r0)                ; L in place
        move    x:(r7+$25),a
        move    x:(r7+$26),x0
        sub     x0,a
        move    a,x0
        mpy     x0,y1,a
        move    x:(r0+n0),x0
        add     x0,a
        move    a,x:(r0+n0)             ; R in place
        move    #>$2,n0
        move    (r0)+n0                 ; advance one stereo frame
rvend:

; ---- per-block: write the underivable state back -------------------------
        move    x:(r7+$3f),r5
        move    #>$ffffff,m5
        move    x:(r7+$3e),a               ; fills the AGU slot
        move    a,y:(r5)+
        move    x:(r7+$3a),a
        move    a,y:(r5)+
        move    x:(r7+$3b),a
        move    a,y:(r5)+
        move    x:(r7+$3c),a
        move    a,y:(r5)+
        move    x:(r7+$3d),a
        move    a,y:(r5)+
noloop:

; ---- save the phase, restore the M registers ---------------------------
        move    r1,a
        move    #>$7ff,x0
        and     x0,a
        move    a,x:(r7+$83)
dry:
        move    #>$ffffff,m0
        move    #>$ffffff,m1
        move    #>$ffffff,m2
        move    #>$ffffff,m3
        move    #>$ffffff,m4
        move    #>$ffffff,m5
        rts
