; ---------------------------------------------------------------------------
; BUS.md task 8: REVERB SERVER. Same engine as dsp/reverb89.asm (all of the
; commentary below this point describes that lineage and is unchanged), with
; three differences:
;
; 1. HARDCODED BASE. init/proc no longer read x:0x213 or the per-instance
;    allocator table at all -- the buffer base is the literal Y:0x4000,
;    every instance, matching dsp/probe_hardcoded_base.asm (BUS.md's Memory
;    section, emulator-verified independent of the allocator table). The
;    "refuse to run on a slot that cannot hold the layout" check is gone
;    too: there is no wrong slot to refuse anymore. At most one REVERB
;    SERVER per bank is a self-enforced convention (BUS.md Known limitations),
;    not something this file checks.
;
; 2. SHARED BUS PLUMBING. Every proc() call now also runs the same
;    position-0 parity-flip-and-clear housekeeping as dsp/send_client.asm
;    (verbatim, BUS.md's documented duplication requirement, including the
;    split-aware frame-offset fix -- see that file's header for the full
;    reasoning). The engine's own input additionally sums in the shared
;    REVERB bus accumulator (one block of latency, built up by every SEND
;    client and by this track's own dry signal, which is also a client of
;    its own bus per BUS.md's Known limitations), and its own clean mono wet
;    (pre-WIDTH, pre-MIX -- the bus should carry the algorithm's output, not
;    this track's own colouring of it) is written to the shared REVERB WET
;    buffer for a future cross-bus consumer (task 10) to read.
;
; 3. Everything else -- the algorithm, the parameters, the memory layout
;    below, the warm-up, all of it -- is untouched.
;
; 4. CROSS-BUS SEND (BUS.md task 10): ->DELAY, dry only, one new knob on the
;    confirmed-dead $d (MONO) slot (REVERB.md's parameter table: proven on
;    hardware to do nothing, so free to repurpose). Taps this reverb's own
;    PRE-EFFECT dry mono signal -- never its processed wet -- and adds it,
;    scaled, into the shared DELAY bus accumulator alongside whatever SEND
;    clients contribute that block. Dry-only is not a simplification, it is
;    the safety argument: BUS.md's Cross-bus sends section forbids a
;    reverb->delay WET path because it would close a loop with DELAY
;    SERVER's own ->VERB wet send (task 10's other half, dsp/delay_server.asm)
;    -- delay's wet reaching reverb, reverb's wet reaching delay, round again,
;    the same shape of instability that self-oscillated during this engine's
;    own development (DSP.md's "flat envelope is proof of instability"). A
;    dry tap can never close that loop: it only ever reads a track's own
;    pre-effect signal, the same guarantee dsp/send_client.asm's two knobs
;    already rely on.
; ---------------------------------------------------------------------------

; ---------------------------------------------------------------------------
; v61 = v59 + LO, and the page-1 knobs put under the names that fit them:
;   HP ($3) -> LO, a NEW one-pole low cut inside the feedback path
;   LP ($4) -> HI, the existing high cut (moved off $1)
;   SHVG ($1) -> MOD depth (moved off $4)
; TIME, SHVF/SIZE, MIX and PRE already matched and do not move. First
; build in the enlarged SPRING+DARK space (2037 words).
;
; v59 = v58 + the PRE slot fix ($e was a flag word; stock DARK uses $c).
;
; v58 = v57 + v46's PRE-DELAY restored (m5 modulo on the base+0x3000 region,
; seven instructions in the loop). Dropped in v50 only to test the modulo
; theory of the two-track freeze, which was wrong: the cause was the $83
; phase load saturating the AGU (v55), and v50 froze with every M register
; linear. PRE is a real parameter again, 0..2032 samples (0..46 ms).
;
; v57 = v56 + run the body on BOTH dispatcher calls. The a=0 call is not a
; control call: it is the FIRST SUB-BLOCK, frames [0,split) at r0=0 with
; n7=split, made only when the track's split is nonzero -- and every trig
; sets the split to its landing offset inside the block, persisting until
; the next trig. rts'ing it (v44..v56) leaves the wet absent from
; [0,split) of every block after a trig: a 2.7 kHz gap train in the tail,
; the "static after a trig". Only the LFO advance gates on the a flag.
;
; v56 = v55 + the warm-up: a tagged block counter in r7+$82 (stock DARK's
; own warmed-flag slot) zeroes the whole 0x3800-word allocation 56 words a
; block over 256 blocks, output dry until warm. Kills the "laddering
; static" -- the lines held boot garbage and the tank recirculated it.
;
; v46 -- generated by tools/gen_reverb.py, do not hand-edit
;
; Four series allpasses into a four-line FDN with a 4x4 Hadamard, one-pole
; damping inside the feedback path, and interpolated modulation on two lines.
;
; All buffers are relative to the per-instance base at x:(x:>$213), so two
; tracks running this effect do not write through each other. An FX2 instance is
; given 0x4000 words:
;   lines      base+0x0000 .. base+0x1fff   2048 words each
;              taps 1567 1249 977 733  (36 28 22 17 ms)
;   allpasses  base+0x2000 .. base+0x2fff   1024 words each
;              taps 907 673 487 331  (21 15 11 8 ms)
;   pre-delay  base+0x3000 .. base+0x37ff   2048 words (46 ms)
;   total      0x3800 of the 0x4000 an FX2 instance is given
;
; The allpasses are long on purpose. Four lines at ~50 ms is only ~80 echoes a
; second, which on its own reads as a stutter rather than a wash; the density
; has to come from diffusion, so the allpasses run 9-24 ms instead of the 3-8 ms
; they were when the whole engine had to fit in 6K.
;
; State (all in the per-instance r7 block, not absolute Y):
;   r7+$83        write phase (persistent, masked on load as well as save)
;   r7+$82        warm-up counter, $2c0000 | blocks, capped at 0x100
;   base+0x3800   4 in-loop allpasses, 512 words each (v74)
;   r7+$40        LO coefficient;  r7+$41..$44  LO states (working copies)
;   r7+$31..$78   this instance's base, and the bases derived from it
;   r7+$15..$66   per-sample scratch
;   r7+$68        this call's DELAY ACC write address (BUS.md task 10,
;                 per-call, advances per sample -- same shape as $63/$64)
;   r7+$69        ->DELAY send level (per block, from knob $d)
;   r7+$6a        this sample's own pre-effect dry mono, stashed before it's
;                 combined with the REVERB bus accumulator into $1b (BUS.md
;                 task 10 -- the ->DELAY send must tap dry alone, not dry+bus)
;
; Parameters:
;   p0 TIME -> feedback, 0.875 .. 0.999
;   p1 DAMP -> one-pole coefficient. s += c*(d-s), so a LARGE c keeps highs.
;              DAMP up lowers c: 0 = bright, 127 = dark.
;   p5 MIX  -> wet gain
;   $d MONO (confirmed dead on hardware, REVERB.md) -> repurposed as ->DELAY
;      send level, dry only (BUS.md task 10)
; ---------------------------------------------------------------------------

init:
; BUS.md task 8: hardcoded base, no per-instance stash needed at all -- the
; literal is the same for every instance, so there is nothing to derive here.
        rts

proc:
; ---- BOTH calls are audio; the A accumulator says which sub-block --------
; The dispatcher (P:0x4b8..0x4d7 for FX1, mirrored at 0x4ec.. for FX2):
;
;   split != 0:  move #$0,r0 / clr a  b,n7 / jsr    a=0, r0=0,       n7=split
;   always:      x:$20d,n7 / x:$20e,r0 / #$1,a/jsr  a=1, r0=split*2, n7=16-split
;
; The a=0 call is NOT a control call: it is the first sub-block, frames
; [0,split) of the SAME 16-frame buffer at X:0, made only when split is
; nonzero -- the dispatcher skips it at split=0 (steady state, whole block
; on the a=1 call). Every trig sets the split (+$1e bits 8..11) to its
; landing offset inside the block and it PERSISTS until the next trig, so
; rts'ing the a=0 call (v44..v56) leaves the wet absent from [0,split) of
; every block once a trig lands: a 2.7 kHz gap train in the tail, and the
; tank never hears those frames. That was the "static after a trig".
;
; So the body runs on BOTH calls. Everything re-derives from r7/$83 per
; call, and the phase and damping states are saved per call, so the two
; sub-blocks are sample-continuous by construction. Only once-per-block
; state gates on the flag: the LFO advance (below). The warm-up counter
; deliberately counts CALLS -- under a nonzero split it just warms faster.
; DARK's own body runs on both calls too (its a=0 `beq $172e` skips only
; the warm-up bump).
        move    a,x:(r7+$14)            ; call flag: $010000 = the a=1 call
                                        ; (the dispatcher's #$1 is left-
                                        ; aligned), 0 = the split sub-call

; ---- BUS.md: split-aware frame offset within the shared bus buffers, and
; the gate for whether THIS track (if it happens to be position 0) may run
; the parity flip on THIS call. Identical mechanism to dsp/send_client.asm
; -- see its header for the full reasoning -- keyed off the SAME r7+$14
; call flag this engine already keeps for its own LFO-advance gating, so no
; new stash of the raw incoming accumulator is needed here.
        clr     a
        move    a,x:(r7+$67)            ; default: offset 0 (first call)
        move    x:(r7+$14),a
        tst     a
        bne     bus_a1
        move    #>$1,a
        move    a,x:(r7+$65)            ; "a=0 ran this block"
        move    n7,a
        and     #>$f,a                  ; same mask on the way in
        move    a1,x0
        move    x0,a
        move    a,x:(r7+$66)            ; stash split for the matching a=1
        bra     bus_off_done
bus_a1:
; COLD-BOOT SAFETY. These slots hold boot garbage the first time an instance
; runs, and x:(r7+$67) feeds straight into r1/r2 as a Y pointer below -- an
; unmasked garbage value there makes the per-sample loop write through a wild
; address, which hangs the DSP. Reproduced on hardware: selecting SEND on any
; track from a clean boot froze the unit. Same class as DSP.md's masked-garbage
; AGU saturation, so the same discipline -- mask AND A2-clean before use.
        move    x:(r7+$65),a
        and     #>$ff,a                 ; flag field only
        move    a1,x0
        move    x0,a                    ; A2-clean before the compare
        move    #>$1,x0
        cmp     x0,a                    ; EXACTLY 1, not merely nonzero --
        bne     bus_off_done            ; "nonzero" accepts almost any garbage
        clr     a
        move    a,x:(r7+$65)            ; consume the flag
        move    x:(r7+$66),a
        and     #>$f,a                  ; a split point is 0..15 by
        move    a1,x0                   ; construction, so this cannot narrow a
        move    x0,a                    ; legitimate value -- it only makes
        move    a,x:(r7+$67)            ; garbage harmless
bus_off_done:

; ---- position-0 housekeeping: flip the shared bus parity, clear the new
; write-target ACC buffers. Gated on r7==0x6200 AND offset==0 -- copied from
; dsp/send_client.asm, must stay identical (BUS.md Known limitations).
; Housekeeping is normally done by position 0 (r7 == 0x6200, the bank's first
; FX2 call). That alone breaks the moment the first track's FX2 is NONE: our
; code never runs there, so nobody flips the parity or clears the
; accumulators, and the bus saturates. NONE became selectable with the task-11
; menu, so this is reachable in ordinary use.
;
; Self-healing election instead. Position 0 still housekeeps whenever it runs.
; Any other instance takes over if it sees that the parity has NOT changed
; since the last time it ran -- which can only mean nobody housekept in
; between. Costs one r7 word (the parity this instance last saw) and no new
; global signal, so it needs nothing the bus does not already have.
;
; Gated on the split offset FIRST: only a block's first call may housekeep, so
; a split block's second call can never flip a second time -- the same trap
; the original position-0 code was written around.
        move    x:(r7+$67),a
        tst     a
        bne     bus_notfirst                ; not this block's first call
        move    r7,a
        move    #>$6200,x0
        cmp     x0,a
        beq     bus_dohk                ; position 0: always the housekeeper
        move    #>$1,x0
        move    y:>$900,a
        and     x0,a
        move    a1,x0
        move    x0,a                    ; parity now, A2-clean
        move    x:(r7+$6b),x0
        cmp     x0,a
        bne     bus_seen                ; it moved: someone else housekept
bus_dohk:                               ; nobody did -- take over this block

        move    #>$1,x0
        move    y:>$900,a
        and     x0,a
        move    a,x1
        move    #>$1,a
        sub     x1,a
        and     x0,a
        move    a,y:>$900
        asl     #$4,a,a
        move    a,x0
        move    #>$901,a
        add     x0,a
        move    a,r1                    ; r1 = REVERB ACC[new] base
        move    #>$941,b
        add     x0,b
        move    b,r2                    ; r2 = DELAY  ACC[new] base
        move    #>$ffffff,m1
        move    #>$ffffff,m2
        clr     a
        move    #>16,y0
        do      y0,>bus_zclr
        move    a,y:(r1)+
        move    a,y:(r2)+
bus_zclr:
        nop
; ---- release both server-role locks for this block (BUS.md hardware test 3)
; a is still 0 from the clear loop above. Whichever of the three effects is
; position 0 does this, so the locks are freed exactly once per block and
; re-claimed below in dispatch order.
        move    a,y:>$981               ; DELAY SERVER role owner
        move    a,y:>$982               ; REVERB SERVER role owner
bus_seen:
        move    #>$1,x0                 ; remember this block's parity so next
        move    y:>$900,a               ; block we can tell whether anybody
        and     x0,a                    ; else housekept in between
        move    a1,x0
        move    x0,a
        move    a,x:(r7+$6b)
bus_notfirst:

; ---- server-role lock: only ONE REVERB SERVER may run per bank -----------------
; Both servers use a FIXED, hardcoded Y base identical for every instance, so
; two of the same role would share one set of buffers and drive each other's
; feedback path -- measured on hardware as a solid, unchanging tone (BUS.md's
; hardware test 3). The lock is released once per block by whichever effect is
; position 0 (above) and claimed here in dispatch order: the first instance to
; arrive owns the role for that block, any duplicate rts's without touching
; the audio buffer at all, which is an exact dry passthrough.
;
; Keyed on r7 (this instance's own state block), so a split block's two calls
; both match the same owner and the second is not mistaken for a duplicate.
        move    y:>$982,a
        move    a1,x0
        move    x0,a                    ; A2-clean before the compare
        tst     a
        beq     bus_claim               ; free: take it
        move    r7,x0
        cmp     x0,a
        beq     bus_mine                ; already ours (split block's 2nd call)
        rts                             ; a duplicate: pass audio through
bus_claim:
        move    r7,a
        move    a,y:>$982
bus_mine:

; ---- this call's REVERB ACC read address and WET write address ----------
; READ is the OTHER buffer from the current write parity -- the one every
; SEND client (and our own dry sum, below) finished filling last block
; (one-block latency, BUS.md's Mechanism section). WRITE uses the SAME
; parity clients currently write into, so it is complete and ready by the
; time next block flips -- for a future cross-bus reader (task 10), not
; consumed by anything yet.
        move    #>$1,x0
        move    y:>$900,a
        and     x0,a                    ; write_parity
        move    a,x1
        move    #>$1,a
        sub     x1,a                    ; a = 1 - write_parity = read_parity
        asl     #$4,a,a
        move    a,x0
        move    #>$901,a
        add     x0,a
        move    x:(r7+$67),b            ; this call's split-aware frame offset
        add     b,a
        move    a,x:(r7+$63)            ; this call's ACC read address
        move    x1,a
        asl     #$4,a,a                 ; write_parity*16
        move    a,x0
        move    #>$921,a
        add     x0,a
        add     b,a
        move    a,x:(r7+$64)            ; this call's WET write address

; ---- this call's DELAY ACC write address (BUS.md task 10: ->DELAY send) --
; x1 (write_parity) and b (split-aware frame offset) are both still valid
; from the block just above -- nothing between there and here touches them.
        move    x1,a
        asl     #$4,a,a                 ; write_parity*16
        move    a,x0
        move    #>$941,a
        add     x0,a
        add     b,a
        move    a,x:(r7+$68)            ; this call's DELAY ACC write address

; ---- hardcoded base: BUS.md task 8 (REVERB SERVER always Y:0x4000) ------
; No x:0x213 read, no per-instance stash -- every instance of this effect
; uses the same literal, the same technique dsp/probe_hardcoded_base.asm
; verified independent of the allocator table (BUS.md's Memory section).
        move    #>$ffffff,m0            ; audio is read and written via r0
        move    #>$4000,x0
        move    x0,x:(r7+$31)

; ---- warm-up: stock DARK's shape, adapted --------------------------------
; The delay lines are never cleared: init zeroes nothing, so the tank
; recirculates whatever the 0x3800-word allocation held -- the "laddering
; static". Stock DARK's answer (P:0x1718..0x172c in payload A) is a
; per-block counter in $83 up to 0x100 with $82 as the warmed flag. Our
; $83 already holds the tank phase, so the counter lives in $82 --
; TAGGED, because on the first call after enable $82 holds leftover
; garbage and init cannot be the reset point (the dispatcher re-invokes
; init most blocks). stageprobe4 proved the tagged-counter idiom stable.
;
; While warming: zero 56 words of the allocation per block (256 * 56 =
; 0x3800, all of it), zero the LFO/damping state block, and stay DRY --
; the engine does not run until the lines are clean.
;
; $82 = $2c0000 | count. The standing rule applies twice: the tag field
; and the count are each masked AND A2-cleaned before use -- the count
; feeds the zero pointer, and a bit-23 leftover would saturate it.
        move    x:(r7+$82),a
        move    #>$fffe00,x0
        and     x0,a                    ; tag field -- AND cleans A1 only
        move    a1,x0
        move    x0,a                    ; A2-clean before the compare
        move    #>$2c0000,x0
        cmp     x0,a
        beq     warmtag
        clr     a                       ; garbage tag: warm-up starts at 0
        bra     warmrun
warmtag:
        move    x:(r7+$82),a
        move    #>$1ff,x0
        and     x0,a
        move    a1,x0
        move    x0,a                    ; the count, A2-clean
        move    #>$100,x0
        cmp     x0,a
        bge     warmdone                ; warmed: run the reverb
warmrun:
        move    a,x:(r7+$15)            ; count, for the save below
        asl     #$6,a,a                 ; count*64 -- v74 clears the FULL
                                        ; 0x4000 words now that the in-loop
                                        ; allpasses occupy base+0x3800..0x3fff
        move    x:(r7+$31),x0
        add     x0,a
        move    a,r5                    ; base + count*56, count < 0x100 so
                                        ; the last word is base+0x37ff
        clr     b                       ; the zero source ...
        move    x:(r7+$31),x0           ; ... and both fill the AGU slot
        do      #64,>warmz
        move    b,y:(r5)+
warmz:
; the one-pole and LFO state now lives in r7, so zero it there
        move    b,x:(r7+$3a)
        move    b,x:(r7+$3b)
        move    b,x:(r7+$3c)
        move    b,x:(r7+$3d)
        move    b,x:(r7+$3e)
        move    b,x:(r7+$41)
        move    b,x:(r7+$42)
        move    b,x:(r7+$43)
        move    b,x:(r7+$44)
        move    b,x:(r7+$4f)
        move    b,x:(r7+$50)
        move    b,x:(r7+$51)
        move    x:(r7+$15),a            ; reload count
        move    #>$1,x0
        add     x0,a
        move    #>$2c0000,x0
        add     x0,a                    ; tag | count+1
        move    a,x:(r7+$82)
        bra     dry                     ; output stays dry until warm
warmdone:
        move    x:(r7+$31),x0           ; the base again: everything below
                                        ; derives buffers from x0

; ---- every buffer base, derived once per block --------------------------
        move    #>$2000,a
        add     x0,a
        move    a,x:(r7+$32)
        move    #>$2400,a
        add     x0,a
        move    a,x:(r7+$33)
        move    #>$2800,a
        add     x0,a
        move    a,x:(r7+$34)
        move    #>$2c00,a
        add     x0,a
        move    a,x:(r7+$35)
        move    #>$800,a
        add     x0,a
        move    a,x:(r7+$36)
        move    #>$1000,a
        add     x0,a
        move    a,x:(r7+$37)
        move    #>$3000,a
        add     x0,a
        move    a,x:(r7+$38)
        move    #>$0,a
        add     x0,a
        move    a,x:(r7+$10)            ; line 0 base
        move    #>$800,a
        add     x0,a
        move    a,x:(r7+$11)            ; line 1 base
        move    #>$1000,a
        add     x0,a
        move    a,x:(r7+$12)            ; line 2 base
        move    #>$1800,a
        add     x0,a
        move    a,x:(r7+$13)            ; line 3 base

; ---- state lives in r7, which is already per-instance and persistent ----
; v74: the LFO phases and one-pole states used to be round-tripped through
; a 12-word block at base+0x3800 every call. That was never necessary --
; the r7 block is per-instance and survives between calls, which $83 has
; proven for seventy builds. Deleting the round-trip frees ~48 instructions
; a block AND the whole 2,048-word region at base+0x3800, which is where
; the in-loop allpasses now live.
; ---- rebuild the four delay pointers from the saved phase ----------------
        move    x:(r7+$83),a
        move    #>$7ff,x0
        and     x0,a                    ; mask on LOAD: the phase may be garbage
        move    a1,x0                   ; -- but AND cleans A1 ONLY. Garbage with
        move    x0,a                    ; bit 23 set sign-extends A2 = $ff, and
                                        ; every move a,rN then SATURATES to
                                        ; $800000: the first line access goes to
                                        ; Y:0x800000, off-chip, and the bus waits
                                        ; forever. THIS WAS THE TWO-TRACK FREEZE:
                                        ; track 2's page held bit-23-set garbage,
                                        ; track 1's did not. Reproduced in the
                                        ; emulator by poisoning X:(r7+$83).
        move    x:(r7+$31),x0
        add     x0,a                    ; base + LINE_OFF(0x0)
        move    a,r1                    ; line 0
        move    #>$800,x0
        add     x0,a
        move    a,r2                    ; line 1
        add     x0,a
        move    a,r3                    ; line 2
        add     x0,a
        move    a,r4                    ; line 3
        move    #>$7ff,m1               ; MODULO 2048: r1..r4 are the four line
        move    #>$7ff,m2               ; pointers and each wraps inside its own
        move    #>$7ff,m3               ; line. Restored in v62 -- this is the
        move    #>$7ff,m4               ; original design, and it is what makes
                                        ; n1/n4 live again so SIZE reaches all
                                        ; four lines. Bases are base+0/0x800/
                                        ; 0x1000/0x1800 and base is 0x4000 or
                                        ; 0x8000, so every line is 2048-aligned
                                        ; as modulo requires.

    ; ---- SIZE: scale all four tap lengths -----------------------------------
    ; tap = 1567*f on the longest line, so f = 0.125..0.993 gives 196..1556
    ; samples, 4.4..35 ms. The nominal taps are the MAXIMUM -- SIZE only ever
    ; shrinks the space.
    ;
    ; These are the ORIGINAL constants, restored in v64. v62 rescaled them to
    ; cap the tap at 2046 "because mpy doubles", and it does not: measured,
    ; 0.5*0.5 = $200000 exactly. The tap was never 3134*f, never ran off the end
    ; of the 2048-word line, and SIZE was never non-monotonic. All the rescale
    ; achieved was shrinking the range to 125..574 samples -- a much smaller and
    ; ringier space, which is what came back from hardware.
    ;
    ; What WAS real, and stays fixed: SIZE reached only two of the four lines,
    ; because n1/n4 were computed every block and thrown away. The v62 modulo
    ; conversion made them live, and that is kept.
    ; Setup only -- this runs once per block, not per sample.
            move    x:(r6+$2),x0
            move    #>$4c0000,y1            ; v77: SIZE FLOOR RAISED.
            mpy     x0,y1,a
            move    #>$333000,x0            ; f = 0.400 .. 0.989, was
            add     x0,a                    ; 0.125 .. 0.993
            move    a,x1
; At the old floor the whole tank was 566 samples -- a mode spacing of 78 Hz,
; which is a metallic comb by construction and no amount of diffusion fixes
; it. Confirmed by ear ("smallest size sounds worst") and by measurement
; (at SIZE=16 nearly half the spectrum's energy sits in 1% of the bins).
; Raising the floor costs the smallest spaces, which were the bad ones.
            move    #>$3DD800,x0            ; 1979 as a fraction of 2048
            mpy     x0,x1,a
            asr     #$b,a,a                 ; back to an integer tap
            move    #>$1,x0                 ; force the tap ODD -- SIZE scales and
            or      x0,a                    ; truncates the prime nominals and the
                                            ; results share factors: gcd hit 204 at
                                            ; SIZE=104, two lines locked at 216 Hz
            move    #>$800,b
            sub     a,b                     ; 2048 - tap, for the modulated read
            move    b,x:(r7+$45)            ; line 0 -- was n1, which only worked
                                            ; for a STATIC tap. All four lines are
                                            ; modulated now, so all four go through
                                            ; the interpolated path.
            move    #>$34E800,x0            ; 1693 as a fraction of 2048
            mpy     x0,x1,a
            asr     #$b,a,a                 ; back to an integer tap
            move    #>$1,x0                 ; force the tap ODD -- SIZE scales and
            or      x0,a                    ; truncates the prime nominals and the
                                            ; results share factors: gcd hit 204 at
                                            ; SIZE=104, two lines locked at 216 Hz
            move    #>$800,b
            sub     a,b                     ; 2048 - tap, for the modulated read
            move    b,x:(r7+$2a)
            move    #>$2D3800,x0            ; 1447 as a fraction of 2048
            mpy     x0,x1,a
            asr     #$b,a,a                 ; back to an integer tap
            move    #>$1,x0                 ; force the tap ODD -- SIZE scales and
            or      x0,a                    ; truncates the prime nominals and the
                                            ; results share factors: gcd hit 204 at
                                            ; SIZE=104, two lines locked at 216 Hz
            move    #>$800,b
            sub     a,b                     ; 2048 - tap, for the modulated read
            move    b,x:(r7+$2b)
            move    #>$26A800,x0            ; 1237 as a fraction of 2048
            mpy     x0,x1,a
            asr     #$b,a,a                 ; back to an integer tap
            move    #>$800,b
            sub     a,b                     ; 2048 - tap
            move    b,x:(r7+$46)            ; line 3                    ; -tap, line 3 reads y:(r4+n4)
            move    #>$7ff,m6           ; PRE-DELAY modulo, moved off m5 in
                                        ; v70 so m5 can be $3ff for the
                                        ; allpasses. r6 is unused inside the
                                        ; sample loop, so it costs nothing.
            move    #>$3ff,m5           ; ALLPASS modulo: with r5 = base+phase,
                                        ; y:(r5+n5) IS the tap read and y:(r5)
                                        ; the write. Set once per block -- an M
                                        ; write inside the loop froze v47.
                                        ; Harmless to the
                                        ; diffuser: it only ever does plain
                                        ; y:(r5), never a post-increment, and
                                        ; modulo affects updates, not reads.
                                        ; The pre-delay region is base+0x3000,
                                        ; and base is 0x4000 or 0x8000, so the
                                        ; buffer is 0x800-aligned as modulo
                                        ; addressing requires. Set here, AFTER
                                        ; the warm-up's linear r5 walk (which
                                        ; m5 is forced linear for at entry) and
                                        ; BEFORE the loop; the state save at the
                                        ; end forces it linear again.

; ---- feedback gain from TIME --------------------------------------------
; p0 arrives as value<<16. The 4x4 Hadamard has row norm 2, so folding the half
; into the gain makes the matrix orthonormal and the loop gain equal to g.
;
; g now spans 0.935..0.9995, not 0.875..0.999. Decay is g^n where n is passes,
; so RT60 scales with the loop time -- and fitting a real 16K allocation halved
; the mean tap from ~51 ms to ~26 ms, which halved every decay time and made
; TIME feel like it had stopped doing anything. g_new = g_old^0.5 restores the
; old RT60 range over the same knob travel.
        move    x:(r6),x0
        move    #>$043000,y1
        mpy     x0,y1,a
        move    #>$3bd000,x0
        add     x0,a
        move    a,x:(r7+$1e)

; ---- HI: high cut, on the knob LABELLED LP ($4) --------------------------
; The one-pole is s += c*(d-s), so a LARGE c tracks the input and keeps highs.
; HI reads as an EQ control, so it has to run the other way from the old DAMP:
; HI=0 gives c=0.125 (dark), HI=127 gives c~0.99 (bright).
;
; MOVED from $1 (labelled SHVG) to $4 (labelled LP) in v61. A one-pole in
; the feedback path IS a low-pass, so this control finally sits under the
; name that describes it. See the LO block below for the other half.
        move    x:(r6+$4),x0
        move    #>$700000,y1
        mpy     x0,y1,a
        move    #>$100000,x0
        add     x0,a
        move    a,x:(r7+$1f)

; ---- LO: low cut inside the feedback path, on the knob LABELLED HP ($3) --
; The Blackhole/Supermassive pair is a low AND a high cut inside the loop,
; shaping the decay per band rather than the wet EQ. gen_reverb.py reserved
; page-1 slot $3 for exactly this from the start ("P_SPARE ... freed for
; LO") and never built it, because at the time the cycle headroom was not
; measured. It is now: stageprobe5/6 put ~1080 instructions a sample per
; DSP within reach and this engine uses ~135, so the ~44 this costs is
; affordable several times over.
;
; $3 is the knob labelled HP, and a low cut IS a high-pass, so the label is
; honest. HP=0 gives coefficient 0 -- the state never moves, nothing is
; subtracted, and the filter is bypassed exactly. HP=127 gives ~0.155,
; sits INSIDE the loop and its cut compounds every pass. Measured:
; the late tail falls 775 -> 308 -> 128 across the knob at TIME=64,
; while RT60 stays ~4.2-4.6 s. A larger coefficient annihilates it.
        move    x:(r6+$3),x0
        move    #>$040000,y1
        mpy     x0,y1,a
        move    a,x:(r7+$40)            ; LO coefficient

; ---- MIX -----------------------------------------------------------------
        move    x:(r6+$5),x0
        move    x0,x:(r7+$20)

; ---- ->DELAY send level (BUS.md task 10, knob on the dead $d/MONO slot) --
        move    x:(r6+$d),x0
        move    x0,x:(r7+$69)

; ---- MOD: modulation depth, scales the LFO triangle ---------------------
; MOVED from $4 to $1 (labelled SHVG) in v61, swapping with HI above: $4
; is labelled LP and now carries the high cut, which is what it says.
        move    x:(r6+$1),x0
        move    x0,x:(r7+$28)

; ---- WIDTH: 0 = mono, 127 = full stereo ---------------------------------
        move    x:(r6+$b),x0
        move    x0,x:(r7+$2c)

; ---- RATE: LFO increment, ~0.34 Hz .. ~3 Hz -----------------------------
; 8x what it would be per sample, because the LFO is stepped once per block.
; ---- LFO RATE: fixed and SLOW, decoupled from MOD -----------------------
; v84, and this is the whole seasickness. MOD used to drive the RATE as
; well as the depth, reaching 2.84 Hz at full. Pitch shift comes from the
; RATE OF CHANGE of the delay, not its depth:
;
;     63 samples at 2.84 Hz -> 716 samples/s -> ~28 cents of vibrato
;     63 samples at 0.25 Hz ->  63 samples/s -> ~2.5 cents, inaudible
;
; So the depth was never the problem. v78 halved it, which halved the
; vibrato AND halved the smearing -- "less seasick but more ringy". Keeping
; the depth and slowing the sweep gives the smearing without the pitch
; artifact.
;
; r6+$d is not read: hardware confirmed the page-2 knob does nothing, so
; that slot is host-side, not a parameter.
        move    #>$300,a                ; ~0.25 Hz; the four lines then run at
                                        ; 0.25 / 0.21 / 0.18 / 0.14 Hz via their
                                        ; own multipliers
        move    a,x:(r7+$2f)

; ---- PRE: pre-delay in samples, 0 .. 2032 (46 ms) -----------------------
; v * 16. The scale MUST keep this below PRE_LEN (2048): the read is
; y:(r5+n5) under m5 modulo, and a modulo offset larger than the buffer is
; undefined on the DSP56300. It does not wrap -- the read returns nothing, the
; tank gets no input, and the reverb goes completely silent.
;
; THE SLOT IS $c, NOT $e. v58 read $e, the pre-delay was inaudible on
; hardware and did not respond to the knob, and stock DARK says why:
;
;   $e is a FLAG word -- stock does `move x:(r6+$e),a / btst #$8,a` at
;   P:0x173c and P:0x1a0d and branches on it. A knob arrives as
;   value<<16, so bit 8 is always clear and `asr #$c` of it is 0: a
;   one-sample pre-delay, forever, whatever the knob does.
;   $c is stock's own PRE. At P:0x17d4 it does exactly what this code
;   does: mask the knob field, scale it, set m5 = $7ff (the same 2048
;   modulo), back a pointer up by the offset, read delayed / write
;   input, and persist the pointer in its own r7 slot.
;
; Stock's scale is `mpy #$7f0 / add #$10` = v*~16 + 16, max 2031 -- our
; v*16 (max 2032) is the same ramp, so only the slot was ever wrong.
; The mask is stock's too: the slot can carry bits outside the knob
; field, and asr alone would drag them into the sample count.
; SLOT MOVED $c -> $e. Measured with dsp/page2_probe.asm on hardware: page-2
; display slots drive $b (slot 6), $d (slot 8) and $e (slot 10) -- and NOTHING
; drives $c. Stock DARK reads its own pre-delay from $c, which is why earlier
; builds read it here, but no page-2 knob can reach $c, so PRE was dead by
; construction. $e carries a full 0..127 knob value (the probe's slot-10 test
; triggered on it), so PRE lives there now. See DSP.md section 9.
        move    x:(r6+$e),a
        and     #>$7f0000,a             ; knob field only, as stock does
        asr     #$c,a,a
        move    a,x:(r7+$29)
        move    #>$1,x0                 ; the read happens BEFORE the write, so
        add     x0,a                    ; the offset is -(PRE+1): at PRE=0 that
        neg     a                       ; is one sample, not a whole buffer of
        move    a,n6                    ; staleness
        move    x:(r7+$83),a            ; the same counter again
        move    #>$7ff,x0
        and     x0,a
        move    a1,x0                   ; A2-clean here too: same garbage, same
        move    x0,a                    ; saturation, same bus hang
        move    x:(r7+$38),x0
        add     x0,a
        move    a,x:(r7+$30)            ; NOT $6d: the width matrix uses that

; ---- FOUR INDEPENDENT LFOs, one per tank line ---------------------------
; v72. Before this, ONE phase accumulator produced a triangle and its
; inverse, so the four lines shared two phases at a single rate --
; correlated by construction, which is exactly what leaves a periodic tail.
; Each line now free-runs at its own rate, the multipliers chosen so the
; periods do not align.
;
; Per BLOCK, not per sample, so ~5 cycles/sample amortised.

        move    x:(r7+$3e),a            ; line 0  (1.000x) phase
        move    x:(r7+$2f),x0           ; base increment, from RATE
        move    #>$7f0000,y1               ; rate x0.992
        mpy     x0,y1,b                 ; this line's own rate
        move    b1,x0
        add     x0,a
        move    #>$7fffff,x0
        and     x0,a                    ; wrap
        move    a1,x0                   ; extract without saturating on A2
        move    x:(r7+$14),b            ; call flag: advance once per block,
        tst     b                       ; but USE the advanced value on both
        beq     lf3e
        move    x0,x:(r7+$3e)
lf3e:
        move    x0,a
        move    #>$400000,x0
        sub     x0,a
        abs     a                       ; triangle, 0 .. $400000
        move    a,x0
        move    x:(r7+$28),y1           ; MOD depth
        mpy     x0,y1,a
        move    a1,x1
        asl     #$8,a,a
        move    a2,x0
        move    x0,x:(r7+$21)           ; integer offset, 0..126 samples
        move    x1,a
        move    #>$00ffff,x0
        and     x0,a
        asl     #$8,a,a
        move    a,x0
        move    x0,x:(r7+$22)           ; interpolation fraction

        move    x:(r7+$4f),a            ; line 1  (1.168x) phase
        move    x:(r7+$2f),x0           ; base increment, from RATE
        move    #>$6cc000,y1               ; rate x0.850
        mpy     x0,y1,b                 ; this line's own rate
        move    b1,x0
        add     x0,a
        move    #>$7fffff,x0
        and     x0,a                    ; wrap
        move    a1,x0                   ; extract without saturating on A2
        move    x:(r7+$14),b            ; call flag: advance once per block,
        tst     b                       ; but USE the advanced value on both
        beq     lf4f
        move    x0,x:(r7+$4f)
lf4f:
        move    x0,a
        move    #>$400000,x0
        sub     x0,a
        abs     a                       ; triangle, 0 .. $400000
        move    a,x0
        move    x:(r7+$28),y1           ; MOD depth
        mpy     x0,y1,a
        move    a1,x1
        asl     #$8,a,a
        move    a2,x0
        move    x0,x:(r7+$23)           ; integer offset, 0..126 samples
        move    x1,a
        move    #>$00ffff,x0
        and     x0,a
        asl     #$8,a,a
        move    a,x0
        move    x0,x:(r7+$24)           ; interpolation fraction

        move    x:(r7+$50),a            ; line 2  (0.887x) phase
        move    x:(r7+$2f),x0           ; base increment, from RATE
        move    #>$5b0000,y1               ; rate x0.711
        mpy     x0,y1,b                 ; this line's own rate
        move    b1,x0
        add     x0,a
        move    #>$7fffff,x0
        and     x0,a                    ; wrap
        move    a1,x0                   ; extract without saturating on A2
        move    x:(r7+$14),b            ; call flag: advance once per block,
        tst     b                       ; but USE the advanced value on both
        beq     lf50
        move    x0,x:(r7+$50)
lf50:
        move    x0,a
        move    #>$400000,x0
        sub     x0,a
        abs     a                       ; triangle, 0 .. $400000
        move    a,x0
        move    x:(r7+$28),y1           ; MOD depth
        mpy     x0,y1,a
        move    a1,x1
        asl     #$8,a,a
        move    a2,x0
        move    x0,x:(r7+$56)           ; integer offset, 0..126 samples
        move    x1,a
        move    #>$00ffff,x0
        and     x0,a
        asl     #$8,a,a
        move    a,x0
        move    x0,x:(r7+$57)           ; interpolation fraction

        move    x:(r7+$51),a            ; line 3  (1.426x) phase
        move    x:(r7+$2f),x0           ; base increment, from RATE
        move    #>$4a0000,y1               ; rate x0.578
        mpy     x0,y1,b                 ; this line's own rate
        move    b1,x0
        add     x0,a
        move    #>$7fffff,x0
        and     x0,a                    ; wrap
        move    a1,x0                   ; extract without saturating on A2
        move    x:(r7+$14),b            ; call flag: advance once per block,
        tst     b                       ; but USE the advanced value on both
        beq     lf51
        move    x0,x:(r7+$51)
lf51:
        move    x0,a
        move    #>$400000,x0
        sub     x0,a
        abs     a                       ; triangle, 0 .. $400000
        move    a,x0
        move    x:(r7+$28),y1           ; MOD depth
        mpy     x0,y1,a
        move    a1,x1
        asl     #$8,a,a
        move    a2,x0
        move    x0,x:(r7+$58)           ; integer offset, 0..126 samples
        move    x1,a
        move    #>$00ffff,x0
        and     x0,a
        asl     #$8,a,a
        move    a,x0
        move    x0,x:(r7+$59)           ; interpolation fraction

; ---- STAGE 1: loop constants preloaded into spare AGU registers ---------
; `move #>$7ff,x0` is a TWO-WORD instruction: opcode plus a 24-bit immediate,
; and the extra program fetch costs an extra CYCLE. `move n1,x0` is one word
; and one cycle. The masks and the allpass coefficient are loop-invariant and
; were being re-fetched every time -- 17 wasted cycles a sample.
;
; n1..n4 and n6 are genuinely free: v65 moved lines 0 and 3 onto arithmetic
; interpolated reads, which orphaned n1/n4, and n2/n3/n6 were never used. The
; tank pointers r1..r4 use modulo (m1..m4) but never indexed (rN+nN)
; addressing, so nothing reads these as offsets.
;
; Written here, well before the loop, with data moves following -- an AGU
; register write next to its address register is the interlock that froze v47.
                                        ; (n6 now carries the pre-delay offset;
                                        ; the allpass mask is gone -- the AGU
                                        ; masks for free under m5 = $3ff)
        move    x:(r7+$31),x0           ; two data moves before the loop, to
        move    x:(r7+$31),x0           ; clear the AGU write


; ---- in-loop allpass setup (v74) ---------------------------------------
; Dattorro puts a MODULATED allpass inside each tank half, before the long
; delay -- not in the input diffusion chain (v73 tried that and measured
; worse). An allpass in the feedback path multiplies echo density on every
; circulation, which is how a smooth tail comes out of finite memory. We had
; none at all: one echo per line per pass, where Dattorro gets a burst.
;
; Two of them, 1024 words each, in the region the Y state block used to
; occupy. They share m5 = $3ff with the input diffusers, so no M write.
        move    #>$3800,a
        add     x0,a
        move    a,x:(r7+$5e)            ; allpass A base, on line 0
        move    #>$3c00,a
        add     x0,a
        move    a,x:(r7+$5f)            ; allpass B base, on line 1
; v85: SHORTER. 401 and 601 were 26-64% of the line they feed, where the
; classic figure is ~15%. Above roughly 20% an allpass in a feedback loop
; stops diffusing and starts DISPERSING -- delaying frequencies by different
; amounts -- which is the mechanism a spring reverb is built on, and which
; the user hears as metallic when the wet is turned up.
        move    #>875,a
        move    a,x:(r7+$60)            ; 1024 - 149   (9.7% of the longest line)
        move    #>801,a
        move    a,x:(r7+$61)            ; 1024 - 223   (14.5%)

; ---- STAGE 2: read offsets for the four modulo-indexed line reads -------
; nK = (2048 - tap_k) - offset_k, so y:(rK+nK) lands on the delayed sample
; with no masking, no base add and no second address. Each is primed one
; sample further back first, which seeds the interpolation carry for the
; first sample of the block.
;
; This costs n1..n4, which Stage 1 was using for constants -- but all eight
; uses of $7ff lived in the address arithmetic this replaces, so that
; constant is simply gone. $3ff moves to n6.
        move    x:(r7+$45),a
        move    x:(r7+$23),x0
        sub     x0,a
        move    a,x:(r7+$4b)            ; running offset, applied below
        move    #>$1,x0
        sub     x0,a
        move    a,n1                    ; primed one sample further back
        move    x:(r7+$2a),a
        move    x:(r7+$21),x0
        sub     x0,a
        move    a,x:(r7+$4c)            ; running offset, applied below
        move    #>$1,x0
        sub     x0,a
        move    a,n2                    ; primed one sample further back
        move    x:(r7+$2b),a
        move    x:(r7+$56),x0
        sub     x0,a
        move    a,x:(r7+$4d)            ; running offset, applied below
        move    #>$1,x0
        sub     x0,a
        move    a,n3                    ; primed one sample further back
        move    x:(r7+$46),a
        move    x:(r7+$58),x0
        sub     x0,a
        move    a,x:(r7+$4e)            ; running offset, applied below
        move    #>$1,x0
        sub     x0,a
        move    a,n4                    ; primed one sample further back
        move    y:(r1+n1),a
        move    a,x:(r7+$47)            ; seed the interpolation carry
        move    y:(r2+n2),a
        move    a,x:(r7+$48)            ; seed the interpolation carry
        move    y:(r3+n3),a
        move    a,x:(r7+$49)            ; seed the interpolation carry
        move    y:(r4+n4),a
        move    a,x:(r7+$4a)            ; seed the interpolation carry
        move    x:(r7+$4b),a
        move    a,n1
        move    x:(r7+$4c),a
        move    a,n2
        move    x:(r7+$4d),a
        move    a,n3
        move    x:(r7+$4e),a
        move    a,n4

        do      n7,>rvend

; ---- input: mono sum, plus the shared REVERB bus accumulator (BUS.md) ----
        move    #>$1,n0
        move    x:(r0),a
        move    x:(r0+n0),x0
        add     x0,a
        asr     #$1,a,a
        move    a,x:(r7+$1b)
        move    a,x:(r7+$6a)            ; own dry mono, stashed BEFORE the bus
                                        ; is folded in below -- the ->DELAY
                                        ; send (BUS.md task 10) taps dry alone
        move    x:(r7+$63),a            ; this sample's ACC read address
        move    a,r5                    ; borrow r5: free here, every use
                                        ; below recomputes it from scratch
        move    y:(r5),b                ; last block's fully-summed sends
        move    x:(r7+$1b),a
        add     b,a
        move    a,x:(r7+$1b)            ; own dry + bus, feeding the tank
        move    x:(r7+$63),a
        move    #>$1,x0
        add     x0,a
        move    a,x:(r7+$63)            ; advance the read pointer one sample

; ---- ->DELAY: dry parallel send into the shared DELAY bus (BUS.md task 10)
        move    x:(r7+$6a),x0           ; own dry mono, this sample
        move    x:(r7+$69),y1           ; ->DELAY level
        mpy     x0,y1,a
        move    x:(r7+$68),b            ; this call's DELAY ACC write address
        move    b,r5
        move    y:(r5),b
        add     b,a
        move    a,y:(r5)                ; DELAY ACC[write][i] += contribution
        move    x:(r7+$68),a
        move    #>$1,x0
        add     x0,a
        move    a,x:(r7+$68)            ; advance DELAY ACC write pointer

        move    r1,a                    ; the allpass phase IS the tank phase:
        and     #>$3ff,a                ; both advance by 1 a sample, and the
                                        ; line base is aligned, so r1 masked is
                                        ; it. Immediate, not n6: n6 now carries
                                        ; the pre-delay offset.
        move    a,x:(r7+$39)

; ---- pre-delay ----------------------------------------------------------
; r5 with m5 modulo and a plain post-increment -- the same shape as the tank
; lines, which are proven safe. The earlier version computed the addresses
; arithmetically like the diffuser does, which cost 28 instructions a sample;
; that is only necessary when r5 and n5 are RECOMPUTED inside the loop, and
; here they are set once per block.
;
; RESTORED in v58. It was dropped in v50 to test the modulo theory of the
; two-track freeze; that theory was wrong -- the freeze was the $83 phase
; load saturating the AGU (v55). Nothing about modulo addressing was ever
; implicated, and v50 froze without any M register non-linear.
;
; Split-safe like everything else: $30 is re-derived from $83 + the
; pre-delay base once per CALL (in the PRE setup, A2-cleaned there), and
; the running pointer is saved back per sample, so the two sub-blocks of a
; split block continue each other exactly.
        move    x:(r7+$30),r6           ; r6, not r5: the allpasses own r5 now
        move    x:(r7+$1b),a            ; input, and fills the AGU slot
        move    #>$1,n0
        move    y:(r6+n6),b             ; delayed
        move    a,y:(r6)+               ; write, and advance
        move    r6,x:(r7+$30)
        move    b,x:(r7+$1b)            ; delayed input -> the diffuser

; -- allpass 0: base+0x2000, tap 997 (20.6 ms) --
; v70: modulo. n5 = 1024-tap, m5 = $3ff, r5 = base + phase. The AGU then
; does the wrap and the base add for free: y:(r5+n5) is the tap read and
; y:(r5) is the write, so the second address build disappears entirely.
        move    #>27,n5             ; 1024 - 997
        move    x:(r7+$39),a            ; phase   (also spaces the n5 write)
        move    x:(r7+$32),x0            ; base
        add     x0,a
        move    a,r5                    ; = write address
        move    #>$5a0000,y0            ; coefficient 0.703
        move    x:(r7+$1b),x1           ; input, and spaces the r5 write
        move    y:(r5+n5),b             ; d, at (phase - tap) mod 1024
        move    b,x0
        mpy     x0,y0,a
        move    x1,x0
        add     x0,a                    ; v = x + g*d
        move    a,x:(r7+$1c)
        move    a,x1
        mpy     x1,y0,a
        sub     a,b                     ; out = d - g*v
        move    b,x:(r7+$1b)
        move    x:(r7+$1c),a
        move    a,y:(r5)                ; write v at base + phase

; -- allpass 1: base+0x2400, tap 853 (15.3 ms) --
; v70: modulo. n5 = 1024-tap, m5 = $3ff, r5 = base + phase. The AGU then
; does the wrap and the base add for free: y:(r5+n5) is the tap read and
; y:(r5) is the write, so the second address build disappears entirely.
        move    #>171,n5             ; 1024 - 853
        move    x:(r7+$39),a            ; phase   (also spaces the n5 write)
        move    x:(r7+$33),x0            ; base
        add     x0,a
        move    a,r5                    ; = write address
        move    x:(r7+$1b),x1           ; input, and spaces the r5 write
        move    y:(r5+n5),b             ; d, at (phase - tap) mod 1024
        move    b,x0
        mpy     x0,y0,a
        move    x1,x0
        add     x0,a                    ; v = x + g*d
        move    a,x:(r7+$1c)
        move    a,x1
        mpy     x1,y0,a
        sub     a,b                     ; out = d - g*v
        move    b,x:(r7+$1b)
        move    x:(r7+$1c),a
        move    a,y:(r5)                ; write v at base + phase

; -- allpass 2: base+0x2800, tap 719 (11.0 ms) --
; v70: modulo. n5 = 1024-tap, m5 = $3ff, r5 = base + phase. The AGU then
; does the wrap and the base add for free: y:(r5+n5) is the tap read and
; y:(r5) is the write, so the second address build disappears entirely.
        move    #>305,n5             ; 1024 - 719
        move    x:(r7+$39),a            ; phase   (also spaces the n5 write)
        move    x:(r7+$34),x0            ; base
        add     x0,a
        move    a,r5                    ; = write address
        move    x:(r7+$1b),x1           ; input, and spaces the r5 write
        move    y:(r5+n5),b             ; d, at (phase - tap) mod 1024
        move    b,x0
        mpy     x0,y0,a
        move    x1,x0
        add     x0,a                    ; v = x + g*d
        move    a,x:(r7+$1c)
        move    a,x1
        mpy     x1,y0,a
        sub     a,b                     ; out = d - g*v
        move    b,x:(r7+$1b)
        move    x:(r7+$1c),a
        move    a,y:(r5)                ; write v at base + phase

; -- allpass 3: base+0x2c00, tap 613 (7.5 ms) --
; v70: modulo. n5 = 1024-tap, m5 = $3ff, r5 = base + phase. The AGU then
; does the wrap and the base add for free: y:(r5+n5) is the tap read and
; y:(r5) is the write, so the second address build disappears entirely.
        move    #>411,n5             ; 1024 - 613
        move    x:(r7+$39),a            ; phase   (also spaces the n5 write)
        move    x:(r7+$35),x0            ; base
        add     x0,a
        move    a,r5                    ; = write address
        move    x:(r7+$1b),x1           ; input, and spaces the r5 write
        move    y:(r5+n5),b             ; d, at (phase - tap) mod 1024
        move    b,x0
        mpy     x0,y0,a
        move    x1,x0
        add     x0,a                    ; v = x + g*d
        move    a,x:(r7+$1c)
        move    a,x1
        mpy     x1,y0,a
        sub     a,b                     ; out = d - g*v
        move    b,x:(r7+$1b)
        move    x:(r7+$1c),a
        move    a,y:(r5)                ; write v at base + phase

        move    x:(r7+$1b),a
        move    a,x:(r7+$15)            ; diffused input -> tank
; ---- STAGE 3b: coefficients held in registers across all four lines -----
; y0 = DAMP and x1 = the LO coefficient. Neither is clobbered between here
; and the write-back: the line reads use y1, the damping uses y0, the LO
; uses x1. Both were being re-fetched once per line. The allpasses above do
; use y0 and x1, which is why this sits after them.
        move    x:(r7+$1f),y0           ; DAMP, for all four lines
        move    x:(r7+$40),x1           ; LO coefficient, for all four lines
        asr     #$1,a,a
        move    a,x:(r7+$27)            ; and at half, for the other three lines

; ---- four taps, damped inside the feedback path -------------------------
        move    x:(r7+$1f),y0           ; damping coefficient, from DAMP
; -- line 0: base+0x0000, tap 1567, interpolated, LFO-modulated --
; STAGE 2: one MODULO-INDEXED read instead of ~29 instructions of address
; arithmetic. r1 already walks this line under modulo 2048, so
; y:(r1+n1) with n1 = (2048-tap) - LFO offset reads exactly
; (phase - tap - offset) mod 2048 -- the AGU does the masking for free.
;
; The interpolation partner needs no second address: the read pointer
; advances one per sample, so d1 THIS sample is d0 LAST sample. The write
; head stays >=69 samples away even at the shortest tap and deepest
; modulation, so the carried value is never overwritten. Primed before the
; loop, one sample further back, so sample 0 is exact too.
        move    y:(r1+n1),b            ; d0
        move    x:(r7+$47),a            ; d1 = last sample's d0
        move    b,x:(r7+$47)            ; carry forward
        move    x:(r7+$57),y1            ; fraction -- y1, NOT y0: y0 holds DAMP
        sub     b,a                     ; d1 - d0
        move    a,x0
        mpy     x0,y1,a                 ; f*(d1-d0)
        add     b,a                     ; + d0 -> interpolated tap
        move    x:(r7+$3a),b
        sub     b,a
        move    a,x0
        mpy     x0,y0,a
        add     b,a
        move    a,x:(r7+$3a)
        move    a,x:(r7+$16)

    ; -- LO: one-pole high-pass on the damped tap, still inside the loop --
    ; a still holds y, the damped tap, and $16 holds a copy. y1 is free
    ; here: the interpolation fraction is finished with, and y0 must keep
    ; holding HI for the lines below.
        move    x:(r7+$41),b            ; lo state

        sub     b,a                     ; y - lo
        move    a,x0
        mpy     x0,x1,a                 ; cl*(y - lo)
        add     b,a                     ; lo += cl*(y - lo)
        move    a,x:(r7+$41)
        move    a,x0                    ; the low-passed part
        move    x:(r7+$16),a            ; y again
        sub     x0,a                    ; y - lo, the low cut
        move    a,x:(r7+$16)

; -- line 1 modulated: base+0x0800, tap 1249, interpolated --
; STAGE 2: one MODULO-INDEXED read instead of ~29 instructions of address
; arithmetic. r2 already walks this line under modulo 2048, so
; y:(r2+n2) with n2 = (2048-tap) - LFO offset reads exactly
; (phase - tap - offset) mod 2048 -- the AGU does the masking for free.
;
; The interpolation partner needs no second address: the read pointer
; advances one per sample, so d1 THIS sample is d0 LAST sample. The write
; head stays >=69 samples away even at the shortest tap and deepest
; modulation, so the carried value is never overwritten. Primed before the
; loop, one sample further back, so sample 0 is exact too.
        move    y:(r2+n2),b            ; d0
        move    x:(r7+$48),a            ; d1 = last sample's d0
        move    b,x:(r7+$48)            ; carry forward
        move    x:(r7+$22),y1            ; fraction -- y1, NOT y0: y0 holds DAMP
        sub     b,a                     ; d1 - d0
        move    a,x0
        mpy     x0,y1,a                 ; f*(d1-d0)
        add     b,a                     ; + d0 -> interpolated tap
        move    x:(r7+$3b),b
        sub     b,a
        move    a,x0
        mpy     x0,y0,a
        add     b,a
        move    a,x:(r7+$3b)
        move    a,x:(r7+$17)

    ; -- LO: one-pole high-pass on the damped tap, still inside the loop --
    ; a still holds y, the damped tap, and $17 holds a copy. y1 is free
    ; here: the interpolation fraction is finished with, and y0 must keep
    ; holding HI for the lines below.
        move    x:(r7+$42),b            ; lo state

        sub     b,a                     ; y - lo
        move    a,x0
        mpy     x0,x1,a                 ; cl*(y - lo)
        add     b,a                     ; lo += cl*(y - lo)
        move    a,x:(r7+$42)
        move    a,x0                    ; the low-passed part
        move    x:(r7+$17),a            ; y again
        sub     x0,a                    ; y - lo, the low cut
        move    a,x:(r7+$17)

; -- line 2 modulated: base+0x1000, tap 977, interpolated --
; STAGE 2: one MODULO-INDEXED read instead of ~29 instructions of address
; arithmetic. r3 already walks this line under modulo 2048, so
; y:(r3+n3) with n3 = (2048-tap) - LFO offset reads exactly
; (phase - tap - offset) mod 2048 -- the AGU does the masking for free.
;
; The interpolation partner needs no second address: the read pointer
; advances one per sample, so d1 THIS sample is d0 LAST sample. The write
; head stays >=69 samples away even at the shortest tap and deepest
; modulation, so the carried value is never overwritten. Primed before the
; loop, one sample further back, so sample 0 is exact too.
        move    y:(r3+n3),b            ; d0
        move    x:(r7+$49),a            ; d1 = last sample's d0
        move    b,x:(r7+$49)            ; carry forward
        move    x:(r7+$24),y1            ; fraction -- y1, NOT y0: y0 holds DAMP
        sub     b,a                     ; d1 - d0
        move    a,x0
        mpy     x0,y1,a                 ; f*(d1-d0)
        add     b,a                     ; + d0 -> interpolated tap
        move    x:(r7+$3c),b
        sub     b,a
        move    a,x0
        mpy     x0,y0,a
        add     b,a
        move    a,x:(r7+$3c)
        move    a,x:(r7+$18)

    ; -- LO: one-pole high-pass on the damped tap, still inside the loop --
    ; a still holds y, the damped tap, and $18 holds a copy. y1 is free
    ; here: the interpolation fraction is finished with, and y0 must keep
    ; holding HI for the lines below.
        move    x:(r7+$43),b            ; lo state

        sub     b,a                     ; y - lo
        move    a,x0
        mpy     x0,x1,a                 ; cl*(y - lo)
        add     b,a                     ; lo += cl*(y - lo)
        move    a,x:(r7+$43)
        move    a,x0                    ; the low-passed part
        move    x:(r7+$18),a            ; y again
        sub     x0,a                    ; y - lo, the low cut
        move    a,x:(r7+$18)

; -- line 3: base+0x1800, tap 733, interpolated, LFO-modulated --
; STAGE 2: one MODULO-INDEXED read instead of ~29 instructions of address
; arithmetic. r4 already walks this line under modulo 2048, so
; y:(r4+n4) with n4 = (2048-tap) - LFO offset reads exactly
; (phase - tap - offset) mod 2048 -- the AGU does the masking for free.
;
; The interpolation partner needs no second address: the read pointer
; advances one per sample, so d1 THIS sample is d0 LAST sample. The write
; head stays >=69 samples away even at the shortest tap and deepest
; modulation, so the carried value is never overwritten. Primed before the
; loop, one sample further back, so sample 0 is exact too.
        move    y:(r4+n4),b            ; d0
        move    x:(r7+$4a),a            ; d1 = last sample's d0
        move    b,x:(r7+$4a)            ; carry forward
        move    x:(r7+$59),y1            ; fraction -- y1, NOT y0: y0 holds DAMP
        sub     b,a                     ; d1 - d0
        move    a,x0
        mpy     x0,y1,a                 ; f*(d1-d0)
        add     b,a                     ; + d0 -> interpolated tap
        move    x:(r7+$3d),b
        sub     b,a
        move    a,x0
        mpy     x0,y0,a
        add     b,a
        move    a,x:(r7+$3d)
        move    a,x:(r7+$19)

    ; -- LO: one-pole high-pass on the damped tap, still inside the loop --
    ; a still holds y, the damped tap, and $19 holds a copy. y1 is free
    ; here: the interpolation fraction is finished with, and y0 must keep
    ; holding HI for the lines below.
        move    x:(r7+$44),b            ; lo state

        sub     b,a                     ; y - lo
        move    a,x0
        mpy     x0,x1,a                 ; cl*(y - lo)
        add     b,a                     ; lo += cl*(y - lo)
        move    a,x:(r7+$44)
        move    a,x0                    ; the low-passed part
        move    x:(r7+$19),a            ; y again
        sub     x0,a                    ; y - lo, the low cut
        move    a,x:(r7+$19)

; ---- 4x4 Hadamard: adds and subtracts only ------------------------------
        move    x:(r7+$17),x0
        move    x:(r7+$16),a
        add     x0,a
        move    a,x:(r7+$1a)            ; u0 = d0+d1
        move    x:(r7+$16),a
        sub     x0,a
        move    a,x:(r7+$1b)            ; u1 = d0-d1
        move    x:(r7+$19),x0
        move    x:(r7+$18),a
        add     x0,a
        move    a,x:(r7+$1c)            ; u2 = d2+d3
        move    x:(r7+$18),a
        sub     x0,a
        move    a,x:(r7+$1d)            ; u3 = d2-d3

; ---- feedback and write back --------------------------------------------
        move    x:(r7+$1e),y0           ; g/2, loaded ONCE for the whole
                                        ; write-back section. Nothing below
                                        ; clobbers y0 -- and it must not: this
                                        ; slot is $1e, NOT $1f. Reloading the
                                        ; DAMPING coefficient here once gave
                                        ; lines 1..3 a feedback gain of up to
                                        ; 0.995 and the tank self-oscillated.
        move    x:(r7+$1c),x0
        move    x:(r7+$1a),a
        add     x0,a
        move    a,x0
        mpy     x0,y0,a
        move    x:(r7+$15),x0           ; diffused input
        add     x0,a
; -- in-loop allpass, line 0: diffuses the feedback before it is stored --
        move    a,x1                    ; x = the value bound for the line
        move    x:(r7+$60),a
        move    a,n5                    ; 1024 - tap
        move    x:(r7+$39),a            ; phase (already masked to $3ff)
        move    x:(r7+$5e),x0
        add     x0,a
        move    a,r5                    ; = write address
        move    #>$5a0000,y1            ; g -- y1, NOT y0: y0 holds g/2 across
        move    x:(r7+$15),x0           ; the whole write-back section
        move    y:(r5+n5),b             ; d
        move    b,x0
        mpy     x0,y1,a
        move    x1,x0
        add     x0,a                    ; v = x + g*d
        move    a,x:(r7+$14)
        move    a,x0
        mpy     x0,y1,a
        sub     a,b                     ; out = d - g*v
        move    x:(r7+$14),a
        move    a,y:(r5)                ; store v
        move    b,a                     ; out -> the line
        move    a,y:(r1)             ; write at the line's own modulo pointer

        move    x:(r7+$1d),x0
        move    x:(r7+$1b),a
        add     x0,a
        move    a,x0
        mpy     x0,y0,a
        move    x:(r7+$15),x0           ; diffused input
        sub     x0,a
; -- in-loop allpass, line 1: diffuses the feedback before it is stored --
        move    a,x1                    ; x = the value bound for the line
        move    x:(r7+$61),a
        move    a,n5                    ; 1024 - tap
        move    x:(r7+$39),a            ; phase (already masked to $3ff)
        move    x:(r7+$5f),x0
        add     x0,a
        move    a,r5                    ; = write address
        move    #>$5a0000,y1            ; g -- y1, NOT y0: y0 holds g/2 across
        move    x:(r7+$15),x0           ; the whole write-back section
        move    y:(r5+n5),b             ; d
        move    b,x0
        mpy     x0,y1,a
        move    x1,x0
        add     x0,a                    ; v = x + g*d
        move    a,x:(r7+$14)
        move    a,x0
        mpy     x0,y1,a
        sub     a,b                     ; out = d - g*v
        move    x:(r7+$14),a
        move    a,y:(r5)                ; store v
        move    b,a                     ; out -> the line
        move    a,y:(r2)             ; write at the line's own modulo pointer

        move    x:(r7+$1c),x0
        move    x:(r7+$1a),a
        sub     x0,a
        move    a,x0
        mpy     x0,y0,a
        move    x:(r7+$27),x0           ; diffused input, half
        sub     x0,a
        move    a,y:(r3)             ; write at the line's own modulo pointer

        move    x:(r7+$1d),x0
        move    x:(r7+$1b),a
        sub     x0,a
        move    a,x0
        mpy     x0,y0,a
        move    x:(r7+$27),x0           ; diffused input, half
        add     x0,a
        move    a,y:(r4)             ; write at the line's own modulo pointer

; ---- wet added to dry, two tank taps per channel -------------------------
        move    x:(r7+$20),y1           ; wet gain
; v89: each channel now averages ALL FOUR lines instead of two, using
; orthogonal sign patterns -- L = (l0+l1-l2-l3)/4, R = (l0-l1-l2+l3)/4.
; Their dot product is zero, so the channels stay decorrelated and WIDTH
; still works, but each output averages four independent line responses
; rather than two, which smooths the residual mode ripple by ~sqrt(2).
        move    x:(r7+$16),a            ; line 0
        move    x:(r7+$17),x0           ; line 1
        add     x0,a
        move    x:(r7+$18),x0           ; line 2
        sub     x0,a
        move    x:(r7+$19),x0           ; line 3
        sub     x0,a
        asr     #$2,a,a
        move    a,x:(r7+$2d)            ; wet L = (l0+l1-l2-l3)/4
        move    x:(r7+$16),a
        move    x:(r7+$17),x0
        sub     x0,a
        move    x:(r7+$18),x0
        sub     x0,a
        move    x:(r7+$19),x0
        add     x0,a
        asr     #$2,a,a
        move    a,x:(r7+$2e)            ; wet R = (l0-l1-l2+l3)/4

; ---- WIDTH: mid/side, then MIX, then onto the dry -----------------------
; M = (L+R)/2, S = (L-R)/2, out = M +/- w*S. w=0 collapses to mono, w=1 gives
; back exactly the two tap sums.
        move    x:(r7+$2d),a
        move    x:(r7+$2e),x0
        add     x0,a
        asr     #$1,a,a
        move    a,x:(r7+$25)            ; M
        move    x:(r7+$2d),a
        sub     x0,a
        asr     #$1,a,a
        move    a,x0
        move    x:(r7+$2c),y0           ; WIDTH
        mpy     x0,y0,a
        move    a,x:(r7+$26)            ; w*S

; ---- write M to the shared REVERB WET buffer (BUS.md task 8) ------------
; Pre-WIDTH, pre-MIX: the bus carries this reverb's own clean output, not
; this track's own colouring of it. x0/a/b/r5 are all free here (x0's old
; value, S, is done -- w*S is already stashed above -- and the next line
; reloads x0 fresh).
        move    x:(r7+$64),a
        move    a,r5
        move    x:(r7+$25),b
        move    b,y:(r5)
        move    #>$1,x0
        add     x0,a
        move    a,x:(r7+$64)

        move    x:(r7+$25),a
        move    x:(r7+$26),x0
        add     x0,a
        move    a,x0
        mpy     x0,y1,a                 ; * MIX
        move    x:(r0),x0
        add     x0,a
        move    a,x:(r0)                ; L in place
        move    x:(r7+$25),a
        move    x:(r7+$26),x0
        sub     x0,a
        move    a,x0
        mpy     x0,y1,a
        move    x:(r0+n0),x0
        add     x0,a
        move    a,x:(r0+n0)             ; R in place
        move    (r1)+                   ; all four line pointers advance together
        move    (r2)+                   ; and each wraps inside its own line
        move    (r3)+                   ; under m1..m4 = $7ff
        move    (r4)+
        move    #>$2,n0
        move    (r0)+n0                 ; advance one stereo frame
rvend:

noloop:

; ---- save the phase, restore the M registers ---------------------------
        move    r1,a
        move    #>$7ff,x0
        and     x0,a
        move    a,x:(r7+$83)
dry:
        move    #>$ffffff,m0
        move    #>$ffffff,m1
        move    #>$ffffff,m2
        move    #>$ffffff,m3
        move    #>$ffffff,m4
        move    #>$ffffff,m5
        rts
