; ---------------------------------------------------------------------------
; v59 = v58 + the PRE slot fix ($e was a flag word; stock DARK uses $c).
;
; v58 = v57 + v46's PRE-DELAY restored (m5 modulo on the base+0x3000 region,
; seven instructions in the loop). Dropped in v50 only to test the modulo
; theory of the two-track freeze, which was wrong: the cause was the $83
; phase load saturating the AGU (v55), and v50 froze with every M register
; linear. PRE is a real parameter again, 0..2032 samples (0..46 ms).
;
; v57 = v56 + run the body on BOTH dispatcher calls. The a=0 call is not a
; control call: it is the FIRST SUB-BLOCK, frames [0,split) at r0=0 with
; n7=split, made only when the track's split is nonzero -- and every trig
; sets the split to its landing offset inside the block, persisting until
; the next trig. rts'ing it (v44..v56) leaves the wet absent from
; [0,split) of every block after a trig: a 2.7 kHz gap train in the tail,
; the "static after a trig". Only the LFO advance gates on the a flag.
;
; v56 = v55 + the warm-up: a tagged block counter in r7+$82 (stock DARK's
; own warmed-flag slot) zeroes the whole 0x3800-word allocation 56 words a
; block over 256 blocks, output dry until warm. Kills the "laddering
; static" -- the lines held boot garbage and the tank recirculated it.
;
; v46 -- generated by tools/gen_reverb.py, do not hand-edit
;
; Four series allpasses into a four-line FDN with a 4x4 Hadamard, one-pole
; damping inside the feedback path, and interpolated modulation on two lines.
;
; All buffers are relative to the per-instance base at x:(x:>$213), so two
; tracks running this effect do not write through each other. An FX2 instance is
; given 0x4000 words:
;   lines      base+0x0000 .. base+0x1fff   2048 words each
;              taps 1567 1249 977 733  (36 28 22 17 ms)
;   allpasses  base+0x2000 .. base+0x2fff   1024 words each
;              taps 907 673 487 331  (21 15 11 8 ms)
;   pre-delay  base+0x3000 .. base+0x37ff   2048 words (46 ms)
;   total      0x3800 of the 0x4000 an FX2 instance is given
;
; The allpasses are long on purpose. Four lines at ~50 ms is only ~80 echoes a
; second, which on its own reads as a stutter rather than a wash; the density
; has to come from diffusion, so the allpasses run 9-24 ms instead of the 3-8 ms
; they were when the whole engine had to fit in 6K.
;
; State (all in the per-instance r7 block, not absolute Y):
;   r7+$83        write phase (persistent, masked on load as well as save)
;   r7+$82        warm-up counter, $2c0000 | blocks, capped at 0x100
;   base+0x3800   LFO phase and 4 damping states, loaded per block
;   r7+$31..$78   this instance's base, and the bases derived from it
;   r7+$15..$66   per-sample scratch
;
; Parameters:
;   p0 TIME -> feedback, 0.875 .. 0.999
;   p1 DAMP -> one-pole coefficient. s += c*(d-s), so a LARGE c keeps highs.
;              DAMP up lowers c: 0 = bright, 127 = dark.
;   p5 MIX  -> wet gain
; ---------------------------------------------------------------------------

init:
; No loop, and nothing reset that has to survive.
;
; Reading X:$213 is only valid HERE. Stash the base where process can
; find it: absolute Y, but at an address unique to this instance.
        move    x:>$213,r4
        move    r7,a
        asr     #$8,a,a                 ; r7 >> 8; also fills the AGU slot
        move    x:(r4),x0               ; this instance's buffer base
        move    #>$800,y0
        add     y0,a
        move    a,r5
        move    #>$ffffff,m5
        move    #>$ffffff,m0            ; both fill the AGU slot
        move    x0,y:(r5)
        move    #>$ffffff,m5
        move    #>$ffffff,m0
        move    #>$ffffff,m1
        move    #>$ffffff,m2
        move    #>$ffffff,m3
        move    #>$ffffff,m4
        rts

proc:
; ---- BOTH calls are audio; the A accumulator says which sub-block --------
; The dispatcher (P:0x4b8..0x4d7 for FX1, mirrored at 0x4ec.. for FX2):
;
;   split != 0:  move #$0,r0 / clr a  b,n7 / jsr    a=0, r0=0,       n7=split
;   always:      x:$20d,n7 / x:$20e,r0 / #$1,a/jsr  a=1, r0=split*2, n7=16-split
;
; The a=0 call is NOT a control call: it is the first sub-block, frames
; [0,split) of the SAME 16-frame buffer at X:0, made only when split is
; nonzero -- the dispatcher skips it at split=0 (steady state, whole block
; on the a=1 call). Every trig sets the split (+$1e bits 8..11) to its
; landing offset inside the block and it PERSISTS until the next trig, so
; rts'ing the a=0 call (v44..v56) leaves the wet absent from [0,split) of
; every block once a trig lands: a 2.7 kHz gap train in the tail, and the
; tank never hears those frames. That was the "static after a trig".
;
; So the body runs on BOTH calls. Everything re-derives from r7/$83 per
; call, and the phase and damping states are saved per call, so the two
; sub-blocks are sample-continuous by construction. Only once-per-block
; state gates on the flag: the LFO advance (below). The warm-up counter
; deliberately counts CALLS -- under a nonzero split it just warms faster.
; DARK's own body runs on both calls too (its a=0 `beq $172e` skips only
; the warm-up bump).
        move    a,x:(r7+$14)            ; call flag: $010000 = the a=1 call
                                        ; (the dispatcher's #$1 is left-
                                        ; aligned), 0 = the split sub-call

; ---- this instance's buffer base ----------------------------------------
; X:$213 points at this instance's entry in the base table, but ONLY
; during init: the dispatcher advances it per effect, so by the time blocks are
; running it sits wherever the last init left it. With one effect loaded that
; happens to still be a valid FX2 slot, which is why reading it in process
; (v33) worked on one track and hung on two -- both instances then read the SAME
; entry and one of them wrote 14K words through memory it does not own.
;
; So read it in init and carry it across in the per-instance stash. See the
; STASH note above for why the address moved from 0x735 to 0x800.
;
; Deriving it instead as x:(0x255 + ((r7 - 0x6000) >> 8)) does not work:
; measured, r7 = 0x6200 while the base is table[1], not table[2].
        move    r7,a
        move    #>$ffffff,m0            ; audio is read and written via r0
        asr     #$8,a,a
        move    #>$800,y0
        add     y0,a
        move    a,r5
        move    #>$ffffff,m1     ; both fill the AGU slot
        move    #>$ffffff,m5
        move    y:(r5),x0               ; the base init stashed for us
        move    x0,x:(r7+$31)

; ---- refuse to run on a slot that cannot hold the layout -----------------
; The bump allocator advances ONE entry per EFFECT, of any type, so which table
; entry we get depends on how many effects the project loaded before us -- not
; on how many reverbs. Of the eight entries only two can hold this layout:
;
;   0x1000 0x1c00 0x2800 0x3400   FX1 slots, 0xc00 words. A 0x3800-word
;                                 layout here runs through the neighbouring
;                                 buffers and into FX2 slot 0.
;   0x4000 0x8000                 FX2 slots, 0x4000 words. The only safe ones.
;   0x30000 0x34000               past the end of Y, which stops at 0xC000.
;                                 dsp/ymemprobe.asm hangs when it writes there.
;
; So check, and pass audio through untouched if the slot is not ours. A dry
; track is a diagnosis; a hung machine is not. y0/b are used rather than x0/a
; because the block below needs x0 to still hold the base.
        move    x:(r7+$31),b
        move    #>$4000,y0
        cmp     y0,b
        blt     dry
        move    #>$8801,y0
        cmp     y0,b
        bge     dry

; ---- warm-up: stock DARK's shape, adapted --------------------------------
; The delay lines are never cleared: init zeroes nothing, so the tank
; recirculates whatever the 0x3800-word allocation held -- the "laddering
; static". Stock DARK's answer (P:0x1718..0x172c in payload A) is a
; per-block counter in $83 up to 0x100 with $82 as the warmed flag. Our
; $83 already holds the tank phase, so the counter lives in $82 --
; TAGGED, because on the first call after enable $82 holds leftover
; garbage and init cannot be the reset point (the dispatcher re-invokes
; init most blocks). stageprobe4 proved the tagged-counter idiom stable.
;
; While warming: zero 56 words of the allocation per block (256 * 56 =
; 0x3800, all of it), zero the LFO/damping state block, and stay DRY --
; the engine does not run until the lines are clean.
;
; $82 = $2c0000 | count. The standing rule applies twice: the tag field
; and the count are each masked AND A2-cleaned before use -- the count
; feeds the zero pointer, and a bit-23 leftover would saturate it.
        move    x:(r7+$82),a
        move    #>$fffe00,x0
        and     x0,a                    ; tag field -- AND cleans A1 only
        move    a1,x0
        move    x0,a                    ; A2-clean before the compare
        move    #>$2c0000,x0
        cmp     x0,a
        beq     warmtag
        clr     a                       ; garbage tag: warm-up starts at 0
        bra     warmrun
warmtag:
        move    x:(r7+$82),a
        move    #>$1ff,x0
        and     x0,a
        move    a1,x0
        move    x0,a                    ; the count, A2-clean
        move    #>$100,x0
        cmp     x0,a
        bge     warmdone                ; warmed: run the reverb
warmrun:
        move    a,x:(r7+$15)            ; count, for the save below
        asl     #$3,a,a                 ; count*8
        move    a,x:(r7+$16)
        asl     #$3,a,a                 ; count*64
        move    x:(r7+$16),x0
        sub     x0,a                    ; count*56: this block's chunk
        move    x:(r7+$31),x0
        add     x0,a
        move    a,r5                    ; base + count*56, count < 0x100 so
                                        ; the last word is base+0x37ff
        clr     b                       ; the zero source ...
        move    x:(r7+$31),x0           ; ... and both fill the AGU slot
        do      #56,>warmz
        move    b,y:(r5)+
warmz:
        move    #>$3800,a               ; the LFO/damping state block:
        add     x0,a                    ; zeroed every warm block, so the
        move    a,r5                    ; engine starts from silence too
        move    x:(r7+$15),a            ; reload count; fills the AGU slot
        move    b,y:(r5)+
        move    b,y:(r5)+
        move    b,y:(r5)+
        move    b,y:(r5)+
        move    b,y:(r5)+
        move    #>$1,x0
        add     x0,a
        move    #>$2c0000,x0
        add     x0,a                    ; tag | count+1
        move    a,x:(r7+$82)
        bra     dry                     ; output stays dry until warm
warmdone:
        move    x:(r7+$31),x0           ; the base again: everything below
                                        ; derives buffers from x0

; ---- every buffer base, derived once per block --------------------------
        move    #>$2000,a
        add     x0,a
        move    a,x:(r7+$32)
        move    #>$2400,a
        add     x0,a
        move    a,x:(r7+$33)
        move    #>$2800,a
        add     x0,a
        move    a,x:(r7+$34)
        move    #>$2c00,a
        add     x0,a
        move    a,x:(r7+$35)
        move    #>$800,a
        add     x0,a
        move    a,x:(r7+$36)
        move    #>$1000,a
        add     x0,a
        move    a,x:(r7+$37)
        move    #>$3000,a
        add     x0,a
        move    a,x:(r7+$38)
        move    #>$0,a
        add     x0,a
        move    a,x:(r7+$10)            ; line 0 base
        move    #>$800,a
        add     x0,a
        move    a,x:(r7+$11)            ; line 1 base
        move    #>$1000,a
        add     x0,a
        move    a,x:(r7+$12)            ; line 2 base
        move    #>$1800,a
        add     x0,a
        move    a,x:(r7+$13)            ; line 3 base

; ---- per-block: load the state that cannot be derived -------------------
; The LFO phase and the four one-pole states are the only things that must
; survive between calls and cannot be recomputed. They live in the instance's
; own Y region, so they are per-instance, and touching them once per block costs
; nothing per sample.
        move    #>$3800,a
        add     x0,a
        move    a,x:(r7+$3f)            ; keep the address for the save
        move    a,r5
        move    #>$ffffff,m5            ; linear for the walk
        move    x:(r7+$31),x0           ; base again; fills the AGU slot after r5
        move    y:(r5)+,a
        move    a,x:(r7+$3e)
        move    y:(r5)+,a
        move    a,x:(r7+$3a)
        move    y:(r5)+,a
        move    a,x:(r7+$3b)
        move    y:(r5)+,a
        move    a,x:(r7+$3c)
        move    y:(r5)+,a
        move    a,x:(r7+$3d)

; ---- rebuild the four delay pointers from the saved phase ----------------
        move    x:(r7+$83),a
        move    #>$7ff,x0
        and     x0,a                    ; mask on LOAD: the phase may be garbage
        move    a1,x0                   ; -- but AND cleans A1 ONLY. Garbage with
        move    x0,a                    ; bit 23 set sign-extends A2 = $ff, and
                                        ; every move a,rN then SATURATES to
                                        ; $800000: the first line access goes to
                                        ; Y:0x800000, off-chip, and the bus waits
                                        ; forever. THIS WAS THE TWO-TRACK FREEZE:
                                        ; track 2's page held bit-23-set garbage,
                                        ; track 1's did not. Reproduced in the
                                        ; emulator by poisoning X:(r7+$83).
        move    x:(r7+$31),x0
        add     x0,a                    ; base + LINE_OFF(0x0)
        move    a,r1                    ; line 0
        move    #>$800,x0
        add     x0,a
        move    a,r2                    ; line 1
        add     x0,a
        move    a,r3                    ; line 2
        add     x0,a
        move    a,r4                    ; line 3
        move    #>$ffffff,m1        ; linear unless TANK_ADDR is "modulo"
        move    #>$ffffff,m2
        move    #>$ffffff,m3
        move    #>$ffffff,m4

    ; ---- SIZE: scale all four tap lengths -----------------------------------
    ; Each tap is held as a fraction of LINE_LEN (tap << 11), multiplied by a factor
    ; f = 0.125 .. 0.992, and shifted back to an integer. The nominal taps are the
    ; MAXIMUM, so SIZE only ever shrinks the space: 1567 samples down to
    ; about 195, i.e. 36 ms down to 4 ms on the longest line.
    ; Setup only -- this runs once per block, not per sample.
            move    x:(r6+$2),x0
            move    #>$700000,y1
            mpy     x0,y1,a                 ; * 0.875 FIRST -- $100000 + $7f0000 is
            move    #>$100000,x0            ; $8f0000, which reads as NEGATIVE, and
            add     x0,a                    ; a negative f flips every tap
            move    a,x1                    ; f = 0.125 .. 0.995
            move    #>$30f800,x0            ; 1567 as a fraction of 2048
            mpy     x0,x1,a
            asr     #$b,a,a                 ; back to an integer tap
            neg     a
            move    a,n1                    ; -tap, line 0 reads y:(r1+n1)
            move    #>$270800,x0            ; 1249 as a fraction of 2048
            mpy     x0,x1,a
            asr     #$b,a,a                 ; back to an integer tap
            move    #>$800,b
            sub     a,b                     ; 2048 - tap, for the modulated read
            move    b,x:(r7+$2a)
            move    #>$1e8800,x0            ; 977 as a fraction of 2048
            mpy     x0,x1,a
            asr     #$b,a,a                 ; back to an integer tap
            move    #>$800,b
            sub     a,b                     ; 2048 - tap, for the modulated read
            move    b,x:(r7+$2b)
            move    #>$16e800,x0            ; 733 as a fraction of 2048
            mpy     x0,x1,a
            asr     #$b,a,a                 ; back to an integer tap
            neg     a
            move    a,n4                    ; -tap, line 3 reads y:(r4+n4)
            move    #>$7ff,m5           ; pre-delay modulo. Harmless to the
                                        ; diffuser: it only ever does plain
                                        ; y:(r5), never a post-increment, and
                                        ; modulo affects updates, not reads.
                                        ; The pre-delay region is base+0x3000,
                                        ; and base is 0x4000 or 0x8000, so the
                                        ; buffer is 0x800-aligned as modulo
                                        ; addressing requires. Set here, AFTER
                                        ; the warm-up's linear r5 walk (which
                                        ; m5 is forced linear for at entry) and
                                        ; BEFORE the loop; the state save at the
                                        ; end forces it linear again.

; ---- feedback gain from TIME --------------------------------------------
; p0 arrives as value<<16. The 4x4 Hadamard has row norm 2, so folding the half
; into the gain makes the matrix orthonormal and the loop gain equal to g.
;
; g now spans 0.935..0.9995, not 0.875..0.999. Decay is g^n where n is passes,
; so RT60 scales with the loop time -- and fitting a real 16K allocation halved
; the mean tap from ~51 ms to ~26 ms, which halved every decay time and made
; TIME feel like it had stopped doing anything. g_new = g_old^0.5 restores the
; old RT60 range over the same knob travel.
        move    x:(r6),x0
        move    #>$043000,y1
        mpy     x0,y1,a
        move    #>$3bd000,x0
        add     x0,a
        move    a,x:(r7+$1e)

; ---- HI: high cut, as an EQ rather than a damping amount -----------------
; The one-pole is s += c*(d-s), so a LARGE c tracks the input and keeps highs.
; HI reads as an EQ control, so it has to run the other way from the old DAMP:
; HI=0 gives c=0.125 (dark), HI=127 gives c~0.99 (bright).
        move    x:(r6+$1),x0
        move    #>$700000,y1
        mpy     x0,y1,a
        move    #>$100000,x0
        add     x0,a
        move    a,x:(r7+$1f)

; ---- MIX -----------------------------------------------------------------
        move    x:(r6+$5),x0
        move    x0,x:(r7+$20)

; ---- MOD: modulation depth, scales the LFO triangle ---------------------
        move    x:(r6+$4),x0
        move    x0,x:(r7+$28)

; ---- WIDTH: 0 = mono, 127 = full stereo ---------------------------------
        move    x:(r6+$b),x0
        move    x0,x:(r7+$2c)

; ---- RATE: LFO increment, ~0.34 Hz .. ~3 Hz -----------------------------
; 8x what it would be per sample, because the LFO is stepped once per block.
        move    x:(r6+$d),a
        asr     #$b,a,a
        move    #>$200,x0
        add     x0,a
        move    a,x:(r7+$2f)

; ---- PRE: pre-delay in samples, 0 .. 2032 (46 ms) -----------------------
; v * 16. The scale MUST keep this below PRE_LEN (2048): the read is
; y:(r5+n5) under m5 modulo, and a modulo offset larger than the buffer is
; undefined on the DSP56300. It does not wrap -- the read returns nothing, the
; tank gets no input, and the reverb goes completely silent.
;
; THE SLOT IS $c, NOT $e. v58 read $e, the pre-delay was inaudible on
; hardware and did not respond to the knob, and stock DARK says why:
;
;   $e is a FLAG word -- stock does `move x:(r6+$e),a / btst #$8,a` at
;   P:0x173c and P:0x1a0d and branches on it. A knob arrives as
;   value<<16, so bit 8 is always clear and `asr #$c` of it is 0: a
;   one-sample pre-delay, forever, whatever the knob does.
;   $c is stock's own PRE. At P:0x17d4 it does exactly what this code
;   does: mask the knob field, scale it, set m5 = $7ff (the same 2048
;   modulo), back a pointer up by the offset, read delayed / write
;   input, and persist the pointer in its own r7 slot.
;
; Stock's scale is `mpy #$7f0 / add #$10` = v*~16 + 16, max 2031 -- our
; v*16 (max 2032) is the same ramp, so only the slot was ever wrong.
; The mask is stock's too: the slot can carry bits outside the knob
; field, and asr alone would drag them into the sample count.
        move    x:(r6+$c),a
        and     #>$7f0000,a             ; knob field only, as stock does
        asr     #$c,a,a
        move    a,x:(r7+$29)
        move    #>$1,x0                 ; the read happens BEFORE the write, so
        add     x0,a                    ; the offset is -(PRE+1): at PRE=0 that
        neg     a                       ; is one sample, not a whole buffer of
        move    a,n5                    ; staleness
        move    x:(r7+$83),a            ; the same counter again
        move    #>$7ff,x0
        and     x0,a
        move    a1,x0                   ; A2-clean here too: same garbage, same
        move    x0,a                    ; saturation, same bus hang
        move    x:(r7+$38),x0
        add     x0,a
        move    a,x:(r7+$30)            ; NOT $6d: the width matrix uses that

; ---- LFO: one triangle and its inverse ----------------------------------
        move    x:(r7+$3e),a               ; persistent phase, [0,$7fffff]
        move    x:(r7+$2f),x0           ; increment, from RATE
        add     x0,a
        move    #>$7fffff,x0
        and     x0,a                    ; wrap; A1 is right even if A2 carried
        move    a1,x0                   ; extract without saturating on A2
        move    x:(r7+$14),b            ; the call flag: advance the phase
        tst     b                       ; only on the a=1 call -- once per
        beq     lfnoadv                 ; block -- but USE the advanced value
        move    x0,x:(r7+$3e)           ; on both, so the sub-blocks agree
lfnoadv:
        move    x0,a                    ; clean copy, A2 = 0
        move    #>$400000,x0
        sub     x0,a
        abs     a                       ; triangle T, 0 .. $400000
        move    a,x0
        move    x:(r7+$28),y1           ; MOD depth
        mpy     x0,y1,a                 ; scaled triangle
        move    a1,x0
        move    x0,x:(r7+$26)           ; stash for the inverse
        move    a1,x1                   ; T
        asl     #$5,a,a
        move    a2,x0
        move    x0,x:(r7+$21)     ; line 1: integer offset, 0..8
        move    x1,a                    ; T again, A2 = 0 because T is positive
        move    #>$07ffff,x0
        and     x0,a
        asl     #$4,a,a                 ; fraction, at most $7ffff0 -> positive
        move    a,x0
        move    x0,x:(r7+$22)
        move    #>$400000,a
        move    x:(r7+$26),x0
        sub     x0,a                    ; inverse triangle
        move    a1,x1                   ; T
        asl     #$5,a,a
        move    a2,x0
        move    x0,x:(r7+$23)     ; line 2: integer offset, 0..8
        move    x1,a                    ; T again, A2 = 0 because T is positive
        move    #>$07ffff,x0
        and     x0,a
        asl     #$4,a,a                 ; fraction, at most $7ffff0 -> positive
        move    a,x0
        move    x0,x:(r7+$24)

        do      n7,>rvend

; ---- input: mono sum -----------------------------------------------------
        move    #>$1,n0
        move    x:(r0),a
        move    x:(r0+n0),x0
        add     x0,a
        asr     #$1,a,a
        move    a,x:(r7+$1b)
        move    r1,a                    ; the allpass phase IS the tank phase:
        move    #>$3ff,x0       ; both advance by 1 a sample, and the
        and     x0,a                    ; line base is aligned, so r1 masked is it
        move    a,x:(r7+$39)

; ---- pre-delay ----------------------------------------------------------
; r5 with m5 modulo and a plain post-increment -- the same shape as the tank
; lines, which are proven safe. The earlier version computed the addresses
; arithmetically like the diffuser does, which cost 28 instructions a sample;
; that is only necessary when r5 and n5 are RECOMPUTED inside the loop, and
; here they are set once per block.
;
; RESTORED in v58. It was dropped in v50 to test the modulo theory of the
; two-track freeze; that theory was wrong -- the freeze was the $83 phase
; load saturating the AGU (v55). Nothing about modulo addressing was ever
; implicated, and v50 froze without any M register non-linear.
;
; Split-safe like everything else: $30 is re-derived from $83 + the
; pre-delay base once per CALL (in the PRE setup, A2-cleaned there), and
; the running pointer is saved back per sample, so the two sub-blocks of a
; split block continue each other exactly.
        move    x:(r7+$30),r5           ; restore: the allpasses clobber r5
        move    x:(r7+$1b),a            ; input, and fills the AGU slot
        move    #>$1,n0
        move    y:(r5+n5),b             ; delayed
        move    a,y:(r5)+               ; write, and advance
        move    r5,x:(r7+$30)
        move    b,x:(r7+$1b)            ; delayed input -> the diffuser

; -- allpass 0: base+0x2000, tap 907 (20.6 ms) --
        move    x:(r7+$39),a
        move    #>117,x0
        add     x0,a
        move    #>$3ff,x0
        and     x0,a                    ; (phase - tap) mod 1024
        move    x:(r7+$32),x0
        add     x0,a
        move    a,r5
        move    #>$400000,y0            ; coefficient, and fills the AGU slot
        move    y:(r5),b                ; d
        move    b,x0
        mpy     x0,y0,a
        move    x:(r7+$1b),x0
        add     x0,a                    ; v = x + g*d
        move    a,x:(r7+$1c)
        move    a,x1
        mpy     x1,y0,a
        sub     a,b                     ; out = d - g*v
        move    b,x:(r7+$1b)
        move    x:(r7+$39),a               ; write v at base + phase
        move    x:(r7+$32),x0
        add     x0,a
        move    a,r5
        move    x:(r7+$1c),a            ; reload v, fills the AGU slot
        move    a,y:(r5)

; -- allpass 1: base+0x2400, tap 673 (15.3 ms) --
        move    x:(r7+$39),a
        move    #>351,x0
        add     x0,a
        move    #>$3ff,x0
        and     x0,a                    ; (phase - tap) mod 1024
        move    x:(r7+$33),x0
        add     x0,a
        move    a,r5
        move    #>$400000,y0            ; coefficient, and fills the AGU slot
        move    y:(r5),b                ; d
        move    b,x0
        mpy     x0,y0,a
        move    x:(r7+$1b),x0
        add     x0,a                    ; v = x + g*d
        move    a,x:(r7+$1c)
        move    a,x1
        mpy     x1,y0,a
        sub     a,b                     ; out = d - g*v
        move    b,x:(r7+$1b)
        move    x:(r7+$39),a               ; write v at base + phase
        move    x:(r7+$33),x0
        add     x0,a
        move    a,r5
        move    x:(r7+$1c),a            ; reload v, fills the AGU slot
        move    a,y:(r5)

; -- allpass 2: base+0x2800, tap 487 (11.0 ms) --
        move    x:(r7+$39),a
        move    #>537,x0
        add     x0,a
        move    #>$3ff,x0
        and     x0,a                    ; (phase - tap) mod 1024
        move    x:(r7+$34),x0
        add     x0,a
        move    a,r5
        move    #>$400000,y0            ; coefficient, and fills the AGU slot
        move    y:(r5),b                ; d
        move    b,x0
        mpy     x0,y0,a
        move    x:(r7+$1b),x0
        add     x0,a                    ; v = x + g*d
        move    a,x:(r7+$1c)
        move    a,x1
        mpy     x1,y0,a
        sub     a,b                     ; out = d - g*v
        move    b,x:(r7+$1b)
        move    x:(r7+$39),a               ; write v at base + phase
        move    x:(r7+$34),x0
        add     x0,a
        move    a,r5
        move    x:(r7+$1c),a            ; reload v, fills the AGU slot
        move    a,y:(r5)

; -- allpass 3: base+0x2c00, tap 331 (7.5 ms) --
        move    x:(r7+$39),a
        move    #>693,x0
        add     x0,a
        move    #>$3ff,x0
        and     x0,a                    ; (phase - tap) mod 1024
        move    x:(r7+$35),x0
        add     x0,a
        move    a,r5
        move    #>$400000,y0            ; coefficient, and fills the AGU slot
        move    y:(r5),b                ; d
        move    b,x0
        mpy     x0,y0,a
        move    x:(r7+$1b),x0
        add     x0,a                    ; v = x + g*d
        move    a,x:(r7+$1c)
        move    a,x1
        mpy     x1,y0,a
        sub     a,b                     ; out = d - g*v
        move    b,x:(r7+$1b)
        move    x:(r7+$39),a               ; write v at base + phase
        move    x:(r7+$35),x0
        add     x0,a
        move    a,r5
        move    x:(r7+$1c),a            ; reload v, fills the AGU slot
        move    a,y:(r5)

        move    x:(r7+$1b),a
        move    a,x:(r7+$15)            ; diffused input -> tank
        asr     #$1,a,a
        move    a,x:(r7+$27)            ; and at half, for the other three lines

; ---- four taps, damped inside the feedback path -------------------------
        move    x:(r7+$1f),y0           ; damping coefficient, from DAMP
        move    r1,a                    ; line 0 read, tap 1567
        move    #>$fff9e1,x0
        add     x0,a
        move    #>$7ff,x0
        and     x0,a                    ; offset within the line
        move    x:(r7+$10),x0
        add     x0,a
        move    a,r5
        move    x:(r7+$3a),b             ; fills the AGU slot
        move    x:(r7+$1f),y0           ; and again
        move    y:(r5),a
        sub     b,a
        move    a,x0
        mpy     x0,y0,a
        add     b,a
        move    a,x:(r7+$3a)
        move    a,x:(r7+$16)

; -- line 1 modulated: base+0x0800, tap 1249, interpolated --
        move    r1,b
        move    #>$7ff,x0
        and     x0,b                    ; shared write phase
        move    x:(r7+$21),x0
        sub     x0,b                    ; phase - offset
        move    x:(r7+$2a),x0    ; 2048 - tap, from SIZE
        add     x0,b
        move    #>$7ff,x0
        and     x0,b                    ; i0
        move    b,a
        add     x0,a
        and     x0,a                    ; i1 = (i0-1) mod 2048
        move    x:(r7+$36),x0
        add     x0,b
        add     x0,a
        move    a,x1
        move    b,r5
        move    x:(r7+$22),y1     ; fraction -- y1, NOT y0: y0 holds DAMP
        move    x1,a
        move    y:(r5),b                ; d0
        move    a,r5
        move    b,x:(r7+$25)
        move    b,x0                    ; both fill the AGU slot
        move    y:(r5),a                ; d1
        sub     x0,a
        move    a,x0
        mpy     x0,y1,a                 ; f*(d1-d0)
        move    x:(r7+$25),x0
        add     x0,a                    ; interpolated tap
        move    x:(r7+$3b),b
        sub     b,a
        move    a,x0
        mpy     x0,y0,a
        add     b,a
        move    a,x:(r7+$3b)
        move    a,x:(r7+$17)

; -- line 2 modulated: base+0x1000, tap 977, interpolated --
        move    r1,b
        move    #>$7ff,x0
        and     x0,b                    ; shared write phase
        move    x:(r7+$23),x0
        sub     x0,b                    ; phase - offset
        move    x:(r7+$2b),x0    ; 2048 - tap, from SIZE
        add     x0,b
        move    #>$7ff,x0
        and     x0,b                    ; i0
        move    b,a
        add     x0,a
        and     x0,a                    ; i1 = (i0-1) mod 2048
        move    x:(r7+$37),x0
        add     x0,b
        add     x0,a
        move    a,x1
        move    b,r5
        move    x:(r7+$24),y1     ; fraction -- y1, NOT y0: y0 holds DAMP
        move    x1,a
        move    y:(r5),b                ; d0
        move    a,r5
        move    b,x:(r7+$25)
        move    b,x0                    ; both fill the AGU slot
        move    y:(r5),a                ; d1
        sub     x0,a
        move    a,x0
        mpy     x0,y1,a                 ; f*(d1-d0)
        move    x:(r7+$25),x0
        add     x0,a                    ; interpolated tap
        move    x:(r7+$3c),b
        sub     b,a
        move    a,x0
        mpy     x0,y0,a
        add     b,a
        move    a,x:(r7+$3c)
        move    a,x:(r7+$18)

        move    r1,a                    ; line 3 read, tap 733
        move    #>$fffd23,x0
        add     x0,a
        move    #>$7ff,x0
        and     x0,a                    ; offset within the line
        move    x:(r7+$13),x0
        add     x0,a
        move    a,r5
        move    x:(r7+$3d),b             ; fills the AGU slot
        move    x:(r7+$1f),y0           ; and again
        move    y:(r5),a
        sub     b,a
        move    a,x0
        mpy     x0,y0,a
        add     b,a
        move    a,x:(r7+$3d)
        move    a,x:(r7+$19)

; ---- 4x4 Hadamard: adds and subtracts only ------------------------------
        move    x:(r7+$17),x0
        move    x:(r7+$16),a
        add     x0,a
        move    a,x:(r7+$1a)            ; u0 = d0+d1
        move    x:(r7+$16),a
        sub     x0,a
        move    a,x:(r7+$1b)            ; u1 = d0-d1
        move    x:(r7+$19),x0
        move    x:(r7+$18),a
        add     x0,a
        move    a,x:(r7+$1c)            ; u2 = d2+d3
        move    x:(r7+$18),a
        sub     x0,a
        move    a,x:(r7+$1d)            ; u3 = d2-d3

; ---- feedback and write back --------------------------------------------
        move    x:(r7+$1e),y0           ; g/2
        move    x:(r7+$1c),x0
        move    x:(r7+$1a),a
        add     x0,a
        move    a,x0
        mpy     x0,y0,a
        move    x:(r7+$15),x0           ; diffused input
        add     x0,a
        move    a,x:(r7+$14)            ; hold it while r5 is built
        move    r1,a
        move    #>$7ff,x0
        and     x0,a
        move    x:(r7+$10),x0
        add     x0,a
        move    a,r5
        move    x:(r7+$14),a            ; fills the AGU slot
        move    x:(r7+$1e),y0           ; and again -- $5e, NOT $5f. y0 holds g/2
                                        ; across the whole write-back section, so
                                        ; reloading the DAMPING coefficient here
                                        ; gave lines 1..3 a feedback gain of up to
                                        ; 0.995 and the tank self-oscillated.
        move    a,y:(r5)

        move    x:(r7+$1d),x0
        move    x:(r7+$1b),a
        add     x0,a
        move    a,x0
        mpy     x0,y0,a
        move    x:(r7+$15),x0           ; diffused input
        sub     x0,a
        move    a,x:(r7+$14)            ; hold it while r5 is built
        move    r1,a
        move    #>$7ff,x0
        and     x0,a
        move    x:(r7+$11),x0
        add     x0,a
        move    a,r5
        move    x:(r7+$14),a            ; fills the AGU slot
        move    x:(r7+$1e),y0           ; and again -- $5e, NOT $5f. y0 holds g/2
                                        ; across the whole write-back section, so
                                        ; reloading the DAMPING coefficient here
                                        ; gave lines 1..3 a feedback gain of up to
                                        ; 0.995 and the tank self-oscillated.
        move    a,y:(r5)

        move    x:(r7+$1c),x0
        move    x:(r7+$1a),a
        sub     x0,a
        move    a,x0
        mpy     x0,y0,a
        move    x:(r7+$27),x0           ; diffused input, half
        sub     x0,a
        move    a,x:(r7+$14)            ; hold it while r5 is built
        move    r1,a
        move    #>$7ff,x0
        and     x0,a
        move    x:(r7+$12),x0
        add     x0,a
        move    a,r5
        move    x:(r7+$14),a            ; fills the AGU slot
        move    x:(r7+$1e),y0           ; and again -- $5e, NOT $5f. y0 holds g/2
                                        ; across the whole write-back section, so
                                        ; reloading the DAMPING coefficient here
                                        ; gave lines 1..3 a feedback gain of up to
                                        ; 0.995 and the tank self-oscillated.
        move    a,y:(r5)

        move    x:(r7+$1d),x0
        move    x:(r7+$1b),a
        sub     x0,a
        move    a,x0
        mpy     x0,y0,a
        move    x:(r7+$27),x0           ; diffused input, half
        add     x0,a
        move    a,x:(r7+$14)            ; hold it while r5 is built
        move    r1,a
        move    #>$7ff,x0
        and     x0,a
        move    x:(r7+$13),x0
        add     x0,a
        move    a,r5
        move    x:(r7+$14),a            ; fills the AGU slot
        move    x:(r7+$1e),y0           ; and again -- $5e, NOT $5f. y0 holds g/2
                                        ; across the whole write-back section, so
                                        ; reloading the DAMPING coefficient here
                                        ; gave lines 1..3 a feedback gain of up to
                                        ; 0.995 and the tank self-oscillated.
        move    a,y:(r5)

; ---- wet added to dry, two tank taps per channel -------------------------
        move    x:(r7+$20),y1           ; wet gain
        move    x:(r7+$17),a            ; line 1, tap 1249
        move    x:(r7+$18),x0           ; line 2, tap 977
        add     x0,a
        asr     #$1,a,a
        move    a,x:(r7+$2d)            ; wet L
        move    x:(r7+$16),a            ; line 0, tap 1567
        move    x:(r7+$19),x0           ; line 3, tap 733
        add     x0,a
        asr     #$1,a,a
        move    a,x:(r7+$2e)            ; wet R

; ---- WIDTH: mid/side, then MIX, then onto the dry -----------------------
; M = (L+R)/2, S = (L-R)/2, out = M +/- w*S. w=0 collapses to mono, w=1 gives
; back exactly the two tap sums.
        move    x:(r7+$2d),a
        move    x:(r7+$2e),x0
        add     x0,a
        asr     #$1,a,a
        move    a,x:(r7+$25)            ; M
        move    x:(r7+$2d),a
        sub     x0,a
        asr     #$1,a,a
        move    a,x0
        move    x:(r7+$2c),y0           ; WIDTH
        mpy     x0,y0,a
        move    a,x:(r7+$26)            ; w*S
        move    x:(r7+$25),a
        move    x:(r7+$26),x0
        add     x0,a
        move    a,x0
        mpy     x0,y1,a                 ; * MIX
        move    x:(r0),x0
        add     x0,a
        move    a,x:(r0)                ; L in place
        move    x:(r7+$25),a
        move    x:(r7+$26),x0
        sub     x0,a
        move    a,x0
        mpy     x0,y1,a
        move    x:(r0+n0),x0
        add     x0,a
        move    a,x:(r0+n0)             ; R in place
        move    (r1)+                   ; the shared phase; every line address is
                                        ; built from it and masked
        move    #>$2,n0
        move    (r0)+n0                 ; advance one stereo frame
rvend:

; ---- per-block: write the underivable state back -------------------------
        move    x:(r7+$3f),r5
        move    #>$ffffff,m5
        move    x:(r7+$3e),a               ; fills the AGU slot
        move    a,y:(r5)+
        move    x:(r7+$3a),a
        move    a,y:(r5)+
        move    x:(r7+$3b),a
        move    a,y:(r5)+
        move    x:(r7+$3c),a
        move    a,y:(r5)+
        move    x:(r7+$3d),a
        move    a,y:(r5)+
noloop:

; ---- save the phase, restore the M registers ---------------------------
        move    r1,a
        move    #>$7ff,x0
        and     x0,a
        move    a,x:(r7+$83)
dry:
        move    #>$ffffff,m0
        move    #>$ffffff,m1
        move    #>$ffffff,m2
        move    #>$ffffff,m3
        move    #>$ffffff,m4
        move    #>$ffffff,m5
        rts
