| Generated by modules/brain/generate_brain.py; edit brain.c / hooks.s.
#NO_APP
	.file	"brain.c"
	.text
	.section	.rodata.str1.1,"aMS",@progbits,1
.LC0:
	.string	"r"
	.text
	.align	2
	.type	slurp, @function
slurp:
	subq.l #4,%sp
	move.l %d2,-(%sp)
	pea 4096.w
	pea iob
	pea .LC0
	move.l 24(%sp),-(%sp)
	pea fobj
	jsr 1073834084
	lea (20,%sp),%sp
	tst.l %d0
	jlt .L6
	pea 32.w
	pea buf
	pea fobj
	jsr 1073833316
	lea (12,%sp),%sp
	subq.l #1,%d0
	tst.l %d0
	jeq .L3
.L13:
	mov3q.l #1,%d1
.L4:
	pea fobj
	move.l %d1,8(%sp)
	jsr 1073833852
	addq.l #4,%sp
	move.l 4(%sp),%d1
	move.l %d1,%d0
	move.l (%sp)+,%d2
	addq.l #4,%sp
	rts
.L3:
	move.l buf+12,%d1
	move.l %d1,%d0
	add.l #-32,%d0
	cmp.l #16352,%d0
	jhi .L13
	moveq #32,%d2
	cmp.l %d1,%d2
	jeq .L4
	move.l %d0,-(%sp)
	pea buf+32
	pea fobj
	move.l %d1,16(%sp)
	jsr 1073833316
	lea (12,%sp),%sp
	subq.l #1,%d0
	move.l 4(%sp),%d1
	tst.l %d0
	jeq .L4
	mov3q.l #1,%d1
	jra .L4
.L6:
	move.l (%sp)+,%d2
	clr.l %d1
	move.l %d1,%d0
	addq.l #4,%sp
	rts
	.size	slurp, .-slurp
	.section	.rodata.str1.1
.LC1:
	.string	"w"
.LC2:
	.string	"/BRAIN"
	.text
	.align	2
	.type	write_file, @function
write_file:
	move.l %a2,-(%sp)
	pea 4096.w
	pea iob
	pea .LC1
	move.l 20(%sp),-(%sp)
	pea fobj
	jsr 1073834084
	lea (20,%sp),%sp
	tst.l %d0
	jlt .L17
.L19:
	move.l 16(%sp),-(%sp)
	move.l 16(%sp),-(%sp)
	pea fobj
	jsr 1073833656
	pea fobj
	move.l %d0,%a2
	jsr 1073833852
	lea (16,%sp),%sp
	mov3q.l #1,%d1
	cmp.l %a2,%d1
	sne %d0
	move.l (%sp)+,%a2
	mvs.b %d0,%d0
	rts
.L17:
	move.l 1187521546,%a0
	pea .LC2
	jsr (%a0)
	pea 4096.w
	pea iob
	pea .LC1
	move.l 24(%sp),-(%sp)
	pea fobj
	jsr 1073834084
	lea (24,%sp),%sp
	tst.l %d0
	jge .L19
	move.l (%sp)+,%a2
	mov3q.l #-1,%d0
	rts
	.size	write_file, .-write_file
	.section	.rodata.str1.1
.LC3:
	.string	"FX2 TRACK "
.LC4:
	.string	"FX1 TRACK "
.LC5:
	.string	"OPEN AN FX PAGE"
.LC6:
	.string	"OF AN AUDIO TRACK"
.LC7:
	.string	"THIS EFFECT HAS"
.LC8:
	.string	"NO STORED DEFAULT"
	.text
	.align	2
	.type	menu_target, @function
menu_target:
	lea (-24,%sp),%sp
	movem.l #1036,(%sp)
	move.l 1175262852,%d0
	move.l %d0,12(%sp)
	tst.b -2147483630.l
	jne .L23
	subq.l #3,%d0
	mov3q.l #1,%d1
	cmp.l %d0,%d1
	jcs .L23
	move.b -2147483648,%d0
	mov3q.l #7,%d2
	move.b -2147483645,%d1
	and.l %d0,%d2
	move.l %d2,16(%sp)
	move.l %d2,%d0
	mov3q.l #4,%d2
	cmp.l 12(%sp),%d2
	jeq .L41
.L26:
	tst.l brain_fx_n
	jeq .L27
	mov3q.l #3,%d3
	and.l %d3,%d1
	mvz.w #6322,%d3
	move.l 1187521622,%a1
	add.l %d0,%a1
	moveq #33,%d2
	moveq #32,%d0
	sub.l brain_fx_n,%d2
	lea brain_fx+32,%a0
	muls.l %d3,%d1
	add.l %d1,%a1
	add.l #585088,%a1
	mvz.b (%a1),%d1
	move.l %d1,%a1
.L32:
	mvz.b (%a0),%d1
	lea (36,%a0),%a0
	cmp.l %a1,%d1
	jeq .L42
	cmp.l %d0,%d2
	jeq .L27
	subq.l #1,%d0
	tst.l %d0
	jne .L32
.L27:
	move.l #.LC7,%d2
	mov3q.l #-1,%d0
	move.l #.LC8,%d3
	move.l %d2,msg
	move.l %d3,msg+4
.L22:
	movem.l (%sp),#1036
	lea (24,%sp),%sp
	rts
.L23:
	move.l #.LC5,%d2
	mov3q.l #-1,%d0
	move.l #.LC6,%d3
	move.l %d2,msg
	move.l %d3,msg+4
	jra .L22
.L41:
	addq.l #8,%d0
	jra .L26
.L42:
	mov3q.l #4,%d2
	cmp.l 12(%sp),%d2
	seq %d0
	move.l %d0,%d3
	neg.l %d3
	move.l %d3,20(%sp)
	cmp.l 12(%sp),%d2
	jeq .L43
	moveq #70,%d2
	move.l #.LC4,%d0
	clr.l %d1
	lea line1,%a0
.L30:
	move.b %d2,(%a0,%d1.l)
	move.l %d1,%a1
	move.l %d0,%a2
	addq.l #1,%d1
	move.b (%a2,%d1.l),%d2
	jne .L30
	clr.b %d0
	move.l 16(%sp),%d2
	add.l #49,%d2
	move.b %d2,(%a0,%d1.l)
	move.l #line1,%d1
	move.l %d1,msg
	move.b %d0,2(%a0,%a1.l)
	mvz.b 23(%sp),%d0
	movem.l (%sp),#1036
	lea (24,%sp),%sp
	rts
.L43:
	moveq #70,%d2
	move.l #.LC3,%d0
	clr.l %d1
	lea line1,%a0
	jra .L30
	.size	menu_target, .-menu_target
	.align	2
	.type	snapshot, @function
snapshot:
	lea (-32,%sp),%sp
	movem.l #31772,(%sp)
	move.l brain_fx_n,%d3
	tst.l %d3
	jeq .L45
	lea brain_fx+32,%a3
	clr.l %d1
	lea desc,%a4
	move.l #shadow+12,%d2
	lea desc+4,%a2
	move.l #1074618332,%a6
	move.l #1074618200,%a5
.L57:
	mvz.b (%a3),%d4
	move.l %d4,%d0
	lsl.l #2,%d0
	move.l %d0,%a0
	move.l (%a0,%a6.l),%d0
	move.l (%a0,%a5.l),%a1
	tst.l %d0
	jeq .L46
	move.l %d0,%a0
	cmp.l (%a0),%d4
	jne .L46
	move.l %d0,(%a4)
	tst.l %a1
	jeq .L54
	cmp.l (%a1),%d4
	jne .L54
	cmp.l %d0,%a1
	jeq .L54
	move.l %a1,(%a2)
	move.l %d0,%a0
	move.l %d2,%a1
	lea (94,%a0),%a0
	add.l #106,%d0
	lea (-12,%a1),%a1
.L55:
	move.b (%a0)+,(%a1)+
	cmp.l %d0,%a0
	jne .L55
	move.l (%a2),%a1
	tst.l %a1
	jne .L53
.L51:
	addq.l #1,%d1
	cmp.l %d3,%d1
	jeq .L45
	lea (36,%a3),%a3
	addq.l #8,%a4
	add.l #24,%d2
	addq.l #8,%a2
	moveq #32,%d0
	cmp.l %d1,%d0
	jne .L57
.L45:
	move.l brain_modedef,%a1
	tst.l %a1
	jeq .L59
	sub.l %a0,%a0
.L58:
	mvz.b (%a1,%a0.l),%d0
	cmp.l #255,%d0
	jeq .L92
	mvz.b 2(%a1,%a0.l),%d2
	addq.l #3,%a0
	tst.l %d2
	jeq .L60
	clr.l %d0
.L61:
	mvz.b 1(%a1,%a0.l),%d1
	addq.l #1,%d0
	lea 2(%a0,%d1.l*2),%a0
	cmp.l %d2,%d0
	jne .L61
.L60:
	cmp.l #1023,%a0
	jls .L58
	clr.l table_len
.L59:
	movem.l (%sp),#31772
	mov3q.l #1,snapped
	lea (32,%sp),%sp
	rts
.L46:
	clr.l (%a4)
	tst.l %a1
	jeq .L87
	cmp.l (%a1),%d4
	jne .L87
	move.l %a1,(%a2)
.L53:
	lea (94,%a1),%a0
	move.l %a1,%d0
	move.l %d2,%a1
	add.l #106,%d0
.L56:
	move.b (%a0)+,(%a1)+
	cmp.l %a0,%d0
	jeq .L51
	move.b (%a0)+,(%a1)+
	cmp.l %a0,%d0
	jne .L56
	jra .L51
.L54:
	move.l %d0,%a0
	move.l %d2,%a1
	clr.l (%a2)
	lea (94,%a0),%a0
	add.l #106,%d0
	lea (-12,%a1),%a1
	jra .L55
.L87:
	clr.l (%a2)
	jra .L51
.L92:
	move.l %a0,table_len
	tst.l %a0
	jeq .L59
	lea table_shadow,%a2
	add.l %a1,%a0
.L65:
	move.b (%a1)+,(%a2)+
	cmp.l %a0,%a1
	jeq .L59
	move.b (%a1)+,(%a2)+
	cmp.l %a0,%a1
	jne .L65
	jra .L59
	.size	snapshot, .-snapshot
	.align	2
	.type	apply.isra.0, @function
apply.isra.0:
	mvz.w buf+10,%d0
	lea (-584,%sp),%sp
	movem.l #31996,(%sp)
	tst.l %d0
	jeq .L93
	move.l brain_fx_n,%d5
	move.l %d0,%d6
	move.l brain_counts+8,%d3
	add.l %d3,%d6
	sub.l %a5,%a5
	moveq #32,%d4
	lea buf+16,%a3
	move.l %d6,44(%sp)
.L108:
	move.l %d4,%a2
	add.l #buf,%a2
	mvz.b (%a2),%d0
	addq.l #1,%d3
	move.l %d3,brain_counts+8
	subq.l #2,%d0
	tst.l %d0
	jne .L102
	move.l 8(%a2),%d2
	mvz.b 1(%a2),%d7
	tst.l %d2
	jeq .L96
	move.l %d7,%d0
	moveq #-4,%d6
	addq.l #3,%d0
	and.l %d6,%d0
	mov3q.l #-1,%d1
	lea 20(%a2,%d0.l),%a1
	add.l %a1,%d2
.L98:
	mvz.b (%a1)+,%d0
	move.w #8,%a0
	eor.l %d0,%d1
.L97:
	mov3q.l #1,%d0
	and.l %d1,%d0
	lsr.l #1,%d1
	subq.l #1,%a0
	neg.l %d0
	and.l #-306674912,%d0
	eor.l %d0,%d1
	tst.l %a0
	jne .L97
	cmp.l %a1,%d2
	jne .L98
	move.l %d1,%d2
	not.l %d2
.L96:
	cmp.l 12(%a2),%d2
	jne .L99
	tst.l %d5
	jeq .L101
	lea brain_fx+4,%a6
	sub.l %a4,%a4
.L107:
	mvz.b 29(%a6),%d0
	cmp.l %d7,%d0
	jne .L103
	tst.l %d7
	jeq .L104
	move.l (%a6),%a0
	move.l %d7,%d2
	lea (20,%a2),%a1
	add.l %a0,%d2
.L105:
	mvz.b (%a1),%d1
	mvz.b (%a0),%d0
	addq.l #1,%a1
	addq.l #1,%a0
	cmp.l %d1,%d0
	jne .L103
	cmp.l %a0,%d2
	jne .L105
.L104:
	moveq #63,%d0
	cmp.l %a5,%d0
	jcs .L102
	lea (%sp,%a5.l*4),%a0
	addq.l #1,%a5
	move.l %a2,72(%a0)
	move.l %a4,328(%a0)
.L102:
	add.l (%a3,%d4.l),%d4
	cmp.l 44(%sp),%d3
	jne .L108
.L203:
	tst.l %a5
	jeq .L93
	clr.l %d7
	lea (328,%sp),%a4
	lea (72,%sp),%a6
.L145:
	move.l (%a6)+,%a1
	moveq #-4,%d4
	move.l %sp,%d1
	clr.l %d3
	lea (328,%sp),%a0
	add.l #72,%d1
	mvz.b 1(%a1),%d2
	clr.l %d0
	addq.l #3,%d2
	and.l %d4,%d2
	lea 20(%a1,%d2.l),%a3
.L112:
	move.l %d1,%a2
	addq.l #4,%d1
	cmp.l %d0,%d7
	jeq .L110
	move.l (%a4),%d6
	cmp.l (%a0),%d6
	jeq .L201
.L110:
	addq.l #1,%d0
	addq.l #4,%a0
	cmp.l %d0,%a5
	jne .L112
.L202:
	tst.l %d3
	jeq .L113
	addq.l #1,brain_counts+36
.L114:
	addq.l #1,%d7
	addq.l #4,%a4
	cmp.l %d7,%a5
	jne .L145
.L93:
	movem.l (%sp),#31996
	lea (584,%sp),%sp
	rts
.L201:
	move.l (%a2),%a2
	moveq #-4,%d4
	move.l (%a3),%d6
	addq.l #1,%d0
	addq.l #4,%a0
	mvz.b 1(%a2),%d2
	addq.l #3,%d2
	and.l %d4,%d2
	cmp.l 20(%a2,%d2.l),%d6
	seq %d2
	mvs.b %d2,%d2
	neg.l %d2
	or.l %d2,%d3
	cmp.l %d0,%a5
	jne .L112
	jra .L202
.L103:
	addq.l #1,%a4
	cmp.l %a4,%d5
	jeq .L101
	lea (36,%a6),%a6
	cmp.l #brain_fx+1156,%a6
	jne .L107
.L101:
	add.l (%a3,%d4.l),%d4
	addq.l #1,brain_counts+20
	cmp.l 44(%sp),%d3
	jne .L108
	jra .L203
.L113:
	mvz.w 2(%a1),%d0
	subq.l #1,%d0
	tst.l %d0
	jne .L114
	move.l 8(%a1),%d6
	mov3q.l #7,%d2
	cmp.l %d6,%d2
	jcc .L114
	tst.w (%a3)
	jne .L118
	move.l (%a4),56(%sp)
	move.l 56(%sp),%d3
	moveq #36,%d4
	lea brain_fx,%a0
	muls.l %d4,%d3
	move.l (%a0,%d3.l),%a1
	move.l %d3,48(%sp)
	cmp.l 4(%a3),%a1
	jeq .L116
	addq.l #1,brain_counts+24
	addq.l #1,%d7
	addq.l #4,%a4
	cmp.l %d7,%a5
	jne .L145
	jra .L93
.L99:
	add.l (%a3,%d4.l),%d4
	addq.l #1,brain_counts+32
	cmp.l 44(%sp),%d3
	jne .L108
	jra .L203
.L116:
	mvz.w 2(%a3),%d0
	move.l %d0,%a2
	cmp.l #65535,%d0
	jne .L204
	clr.l %d5
	clr.l 44(%sp)
.L117:
	addq.l #1,brain_counts+12
	moveq #11,%d3
	cmp.l %d6,%d3
	jcc .L114
	moveq #8,%d1
	move.w #12,%a1
	move.l %a6,60(%sp)
	mvz.b 3(%a3,%d1.l),%d2
	move.l %d7,64(%sp)
	move.l %d1,%a0
	cmp.l #255,%d2
	jeq .L123
.L206:
	move.l %d2,%d0
	moveq #-4,%d4
	addq.l #3,%d0
	and.l %d4,%d0
	addq.l #4,%a0
	add.l %a0,%d0
	cmp.l %d6,%d0
	jhi .L197
.L207:
	mvz.b 2(%a3,%d1.l),%d3
	subq.l #5,%d3
	tst.l %d3
	jeq .L205
.L125:
	move.l %d0,%a1
	addq.l #4,%a1
	cmp.l %d6,%a1
	jhi .L197
	move.l %d0,%d1
	move.l %d1,%a0
	mvz.b 3(%a3,%d1.l),%d2
	cmp.l #255,%d2
	jne .L206
.L123:
	addq.l #8,%a0
	cmp.l %d6,%a0
	jhi .L197
	move.l (%a3,%a1.l),%d2
	moveq #-4,%d4
	move.l %d2,%d0
	addq.l #3,%d0
	and.l %d4,%d0
	add.l %a0,%d0
	cmp.l %d6,%d0
	jls .L207
.L197:
	move.l 64(%sp),%d7
	addq.l #4,%a4
	move.l 60(%sp),%a6
	addq.l #1,%d7
	cmp.l %d7,%a5
	jne .L145
	jra .L93
.L204:
	move.l brain_modedef,%a1
	tst.l %a1
	jeq .L118
	move.l table_len,%d1
	move.l %d1,44(%sp)
	tst.l %d1
	jeq .L118
	move.l 48(%sp),%d2
	mvz.b 32(%a0,%d2.l),%d3
	sub.l %a0,%a0
.L122:
	mvz.b 2(%a1,%a0.l),%d2
	tst.l %d2
	jeq .L147
	move.b (%a1,%a0.l),%d1
	addq.l #3,%a0
	clr.l %d0
	mvz.b %d1,%d1
.L121:
	mvz.b 1(%a1,%a0.l),%d5
	addq.l #1,%d0
	cmp.l %d3,%d1
	jeq .L208
.L120:
	lea 2(%a0,%d5.l*2),%a0
	cmp.l %d2,%d0
	jne .L121
	cmp.l 44(%sp),%a0
	jcs .L122
.L118:
	addq.l #1,brain_counts+28
	addq.l #1,%d7
	addq.l #4,%a4
	cmp.l %d7,%a5
	jne .L145
	jra .L93
.L205:
	subq.l #1,%d2
	tst.l %d2
	jne .L125
	mvz.w (%a3,%d1.l),%d4
	tst.l %d4
	jeq .L125
	move.b (%a3,%a0.l),%d7
	tst.l 44(%sp)
	jne .L209
	move.l 56(%sp),%d3
	mvz.b %d7,%d2
	mvz.w #154,%d1
	lsl.l #3,%d3
	move.w #94,%a0
	move.l 48(%sp),%a1
	add.l #brain_fx+8,%a1
	move.l %d2,52(%sp)
	move.l %d0,68(%sp)
.L143:
	mvz.w (%a1)+,%d2
	cmp.l %d4,%d2
	jeq .L210
.L138:
	addq.l #1,%a0
	addq.l #4,%d1
	cmp.l #202,%d1
	jne .L143
	move.l 68(%sp),%d0
	jra .L125
.L210:
	move.l %d3,%a2
	add.l #desc,%a2
	move.l (%a2)+,%a6
	tst.l %a6
	jeq .L172
	move.l 52(%sp),%d0
	clr.l %d2
	cmp.l (%a6,%d1.l),%d0
	jcc .L140
.L211:
	move.b %d7,(%a6,%a0.l)
	subq.l #1,%d2
	addq.l #1,brain_counts+16
	tst.l %d2
	jeq .L138
.L172:
	move.l (%a2),%a6
	tst.l %a6
	jeq .L138
	move.l 52(%sp),%d0
	addq.l #4,%a2
	mov3q.l #1,%d2
	cmp.l (%a6,%d1.l),%d0
	jcs .L211
.L140:
	addq.l #1,brain_counts+40
	subq.l #1,%d2
	tst.l %d2
	jeq .L138
	jra .L172
.L208:
	mvz.b (%a1,%a0.l),%d4
	cmp.l %a2,%d4
	jne .L120
	lea 2(%a1,%a0.l),%a0
	move.l %a0,44(%sp)
	jra .L117
.L209:
	move.l 56(%sp),%d1
	sub.l %a1,%a1
	mvz.b %d7,%d2
	move.l 48(%sp),%a2
	add.l #brain_fx+8,%a2
	lsl.l #3,%d1
	mvz.w #154,%d3
	move.l %d2,68(%sp)
	move.l %d1,52(%sp)
	mvz.w (%a2)+,%d1
	cmp.l %d4,%d1
	jeq .L212
.L127:
	addq.l #1,%a1
	addq.l #4,%d3
	cmp.l #202,%d3
	jeq .L125
.L200:
	mvz.w (%a2)+,%d1
	cmp.l %d4,%d1
	jne .L127
.L212:
	move.l 52(%sp),%a0
	move.l #desc,%d1
	move.l (%a0,%d1.l),%a6
	tst.l %a6
	jeq .L128
	tst.l %d5
	jeq .L130
	move.l 44(%sp),%a0
	clr.l %d1
.L131:
	mvz.b (%a0),%d2
	addq.l #2,%a0
	cmp.l %d2,%a1
	jeq .L132
	addq.l #1,%d1
	cmp.l %d1,%d5
	jhi .L131
.L132:
	cmp.l %d5,%d1
	jeq .L130
	tst.l %a6
	jeq .L135
	move.l 68(%sp),%d2
	cmp.l (%a6,%d3.l),%d2
	jcc .L135
	mvz.w %d1,%d1
	move.l 44(%sp),%a0
	addq.l #1,%a1
	addq.l #4,%d3
	move.b %d7,1(%a0,%d1.l*2)
	addq.l #1,brain_counts+16
	cmp.l #202,%d3
	jne .L200
	jra .L125
.L135:
	addq.l #1,brain_counts+40
	addq.l #1,%a1
	addq.l #4,%d3
	cmp.l #202,%d3
	jne .L200
	jra .L125
.L128:
	tst.l %d5
	jeq .L130
	move.l 52(%sp),%d1
	lea desc,%a0
	move.l 4(%a0,%d1.l),%a6
	move.l 44(%sp),%a0
	clr.l %d1
	jra .L131
.L130:
	addq.l #1,brain_counts+44
	addq.l #1,%a1
	addq.l #4,%d3
	cmp.l #202,%d3
	jne .L200
	jra .L125
.L147:
	addq.l #3,%a0
	cmp.l 44(%sp),%a0
	jcs .L122
	jra .L118
	.size	apply.isra.0, .-apply.isra.0
	.align	2
	.type	valid, @function
valid:
	lea (-20,%sp),%sp
	moveq #31,%d0
	movem.l #1036,(%sp)
	cmp.l 24(%sp),%d0
	jcc .L216
	move.l #1112686926,%d1
	cmp.l buf.l,%d1
	jeq .L227
.L216:
	movem.l (%sp),#1036
	clr.l %d0
	lea (20,%sp),%sp
	rts
.L227:
	mvz.w buf+4,%d0
	moveq #32,%d2
	cmp.l %d0,%d2
	jne .L216
	mvz.b buf+6,%d0
	subq.l #1,%d0
	tst.l %d0
	jne .L216
	move.l 24(%sp),%a1
	cmp.l buf+12.l,%a1
	jne .L216
	add.l #buf,%a1
	move.l %a1,12(%sp)
	mov3q.l #-1,%d1
	lea buf+20,%a1
.L218:
	mvz.b (%a1)+,%d0
	move.w #8,%a0
	eor.l %d0,%d1
.L217:
	mov3q.l #1,%d0
	and.l %d1,%d0
	lsr.l #1,%d1
	subq.l #1,%a0
	neg.l %d0
	and.l #-306674912,%d0
	eor.l %d0,%d1
	tst.l %a0
	jne .L217
	cmp.l 12(%sp),%a1
	jne .L218
	not.l %d1
	cmp.l buf+16.l,%d1
	jne .L216
	mvz.w buf+10,%d0
	move.l %d0,16(%sp)
	tst.l %d0
	jeq .L221
	moveq #32,%d0
.L220:
	move.l %d0,%d1
	addq.l #1,%a0
	add.l #20,%d1
	cmp.l 24(%sp),%d1
	jhi .L216
	lea buf,%a1
	moveq #-4,%d3
	mvz.b 1(%a1,%d0.l),%d1
	move.l %d1,%a1
	addq.l #3,%a1
	move.l %a1,%d2
	subq.l #1,%d1
	and.l %d3,%d2
	move.l %d2,%a1
	moveq #62,%d2
	cmp.l %d1,%d2
	jcs .L216
	lea buf+8,%a2
	move.l (%a2,%d0.l),%d1
	addq.l #3,%d1
	and.l %d3,%d1
	lea buf+16,%a2
	lea 20(%a1,%d1.l),%a1
	cmp.l (%a2,%d0.l),%a1
	jne .L216
	add.l %a1,%d0
	cmp.l 24(%sp),%d0
	jhi .L216
	cmp.l 16(%sp),%a0
	jne .L220
	cmp.l 24(%sp),%d0
	seq %d0
	mvs.b %d0,%d0
	neg.l %d0
.L228:
	movem.l (%sp),#1036
	lea (20,%sp),%sp
	rts
.L221:
	moveq #32,%d0
	cmp.l 24(%sp),%d0
	seq %d0
	mvs.b %d0,%d0
	neg.l %d0
	jra .L228
	.size	valid, .-valid
	.section	.rodata.str1.1
.LC9:
	.string	"/BRAIN/card.work"
.LC10:
	.string	"/BRAIN/card.strd"
	.text
	.align	2
	.type	write_default, @function
write_default:
	lea (-64,%sp),%sp
	mov3q.l #3,%d1
	movem.l #31996,(%sp)
	mvz.w #6322,%d2
	move.l 72(%sp),%d5
	move.l 68(%sp),%d6
	move.b -2147483645,%d0
	and.l %d1,%d0
	muls.l %d2,%d0
	move.l %d0,%a2
	add.l #585088,%a2
	add.l 1187521622,%a2
	move.l %d6,%d0
	tst.l %d5
	jeq .L230
	addq.l #8,%d0
.L230:
	move.b (%a2,%d0.l),%d2
	addq.l #1,brain_save_counts
	tst.l snapped
	jeq .L353
.L231:
	move.l brain_fx_n,%d3
	tst.l %d3
	jeq .L240
	mvz.b %d2,%d2
	clr.l %d0
	lea desc,%a1
	mov3q.l #-1,%d4
	lea brain_fx+32,%a0
.L239:
	mvz.b (%a0),%d1
	lea (36,%a0),%a0
	cmp.l %d2,%d1
	jeq .L354
.L235:
	addq.l #1,%d0
	addq.l #8,%a1
	cmp.l %d0,%d3
	jeq .L238
	moveq #32,%d1
	cmp.l %d0,%d1
	jne .L239
.L238:
	mov3q.l #-1,%d2
	cmp.l %d4,%d2
	jeq .L285
	mov3q.l #7,%d3
	cmp.l %d6,%d3
	jcs .L240
	tst.l %d5
	sne %d1
	moveq #24,%d0
	moveq #30,%d2
	muls.l %d6,%d0
	muls.l %d2,%d6
	lea (52,%sp),%a3
	move.l %d0,%a0
	lea (294,%a0),%a0
	neg.l %d1
	add.l %a2,%a0
	tst.b %d1
	jne .L355
	move.w #766,%a5
	move.l %a3,%a1
	clr.l %d0
	add.l %d6,%a2
.L245:
	tst.l %d5
	jeq .L243
	move.b 6(%a0),%d1
	lea (%a2,%d0.l),%a4
	addq.l #1,%a0
	add.l %a5,%a4
	addq.l #1,%d0
	mov3q.l #6,%d3
	move.b %d1,(%a1)+
	move.b (%a4),5(%a1)
	cmp.l %d0,%d3
	jne .L245
.L359:
	pea .LC9
	lea slurp,%a2
	jsr (%a2)
	addq.l #4,%sp
	tst.l %d0
	jeq .L246
	move.l %d0,-(%sp)
	lea valid,%a4
	jsr (%a4)
	addq.l #4,%sp
	tst.l %d0
	jne .L247
	pea .LC10
	jsr (%a2)
	addq.l #4,%sp
	move.l %d0,%d7
	tst.l %d0
	jeq .L251
	move.l %d7,-(%sp)
	jsr (%a4)
	addq.l #4,%sp
	tst.l %d0
	jne .L247
.L251:
.L233:
	mov3q.l #2,%d0
	moveq #-2,%d4
	move.l %d0,brain_save_counts+4
	move.l %d4,%d0
	movem.l (%sp),#31996
	lea (64,%sp),%sp
	rts
.L354:
	tst.l (%a1)
	jeq .L356
	move.l %d0,%d4
	jra .L235
.L356:
	tst.l 4(%a1)
	jeq .L235
	move.l %d0,%d4
	jra .L235
.L353:
	jsr snapshot
	jra .L231
.L355:
	move.w #772,%a5
	move.l %a3,%a1
	clr.l %d0
	add.l %d6,%a2
	jra .L245
.L247:
	mvz.w buf+10,%d5
	move.l %d5,%a4
	tst.l %d5
	jeq .L286
	moveq #36,%d0
	moveq #32,%d3
	muls.l %d4,%d0
	move.l %a3,44(%sp)
	moveq #32,%d1
	clr.l %d5
	clr.l %d7
	lea buf+16,%a5
	move.l %d4,48(%sp)
	move.l %d0,%a0
	add.l #brain_fx+4,%d0
	add.l #brain_fx+33,%a0
	move.l %a0,%a3
	move.l %d0,%a6
.L259:
	move.l %d3,%a0
	add.l #buf,%a0
	mvz.b (%a0),%d0
	subq.l #2,%d0
	tst.l %d0
	jne .L252
	mvz.b 1(%a0),%d4
	mvz.b (%a3),%d0
	cmp.l %d4,%d0
	jne .L252
	tst.l %d4
	jeq .L253
	move.l (%a6),%a1
	move.l %d4,%d6
	lea (20,%a0),%a2
	add.l %a1,%d6
.L254:
	mvz.b (%a2),%d2
	mvz.b (%a1),%d0
	addq.l #1,%a2
	addq.l #1,%a1
	cmp.l %d2,%d0
	jne .L252
	cmp.l %d6,%a1
	jne .L254
.L253:
	mov3q.l #3,%d0
	cmp.l 8(%a0),%d0
	jcc .L252
	addq.l #3,%d4
	moveq #-4,%d2
	and.l %d2,%d4
	lea 20(%a0,%d4.l),%a1
	tst.w (%a1)
	jne .L252
	mvz.w 2(%a1),%d0
	cmp.l #65535,%d0
	jeq .L255
.L252:
	move.l 16(%a0),%d0
	move.l %d0,%d2
	add.l %d1,%d2
	cmp.l #16384,%d2
	jhi .L256
	tst.l %d0
	jeq .L257
	move.l %d1,%a1
	add.l %a0,%d0
	add.l #out,%a1
.L258:
	move.b (%a0)+,(%a1)+
	cmp.l %d0,%a0
	jne .L258
.L257:
	addq.l #1,%d7
	move.l %d2,%d1
.L255:
	add.l (%a5,%d3.l),%d3
	addq.l #1,%d5
	cmp.l %d5,%a4
	jne .L259
	move.l 44(%sp),%a3
	move.l 48(%sp),%d4
.L250:
	tst.l 76(%sp)
	jne .L260
	move.w %d4,%d3
	clr.l %d0
	mulu.w #36,%d3
	move.l %d3,%a1
	add.l #brain_fx+8,%a1
	add.l #brain_fx+32,%d3
	move.l %a1,%a0
.L261:
	tst.w (%a0)+
	sne %d2
	mvs.b %d2,%d2
	sub.l %d2,%d0
	cmp.l %d3,%a0
	jne .L261
	moveq #36,%d5
	moveq #-4,%d6
	muls.l %d4,%d5
	lea brain_fx,%a5
	addq.l #1,%d0
	lsl.l #3,%d0
	move.b 33(%a5,%d5.l),%d3
	mvz.b %d3,%d2
	move.w %d3,%a6
	move.l %d2,%d3
	addq.l #3,%d3
	and.l %d6,%d3
	move.l %d3,%a0
	move.l %d0,%d3
	lea (20,%a0),%a0
	add.l %a0,%d3
	move.l %d3,%d6
	add.l %d1,%d6
	cmp.l #16384,%d6
	jhi .L256
	move.l %d1,%a4
	add.l #out,%a4
	tst.l %d3
	jeq .L263
	move.l %d3,%d1
	move.l %a4,%a2
	add.l %a4,%d1
.L264:
	clr.b (%a2)+
	cmp.l %d1,%a2
	jne .L264
.L263:
	move.w %a6,%d1
	move.b #2,(%a4)
	move.l %d0,8(%a4)
	move.l %d3,16(%a4)
	move.b %d1,1(%a4)
	moveq #1,%d1
	move.w %d1,2(%a4)
	tst.l %d2
	jeq .L265
	move.l 4(%a5,%d5.l),%a2
	lea (20,%a4),%a6
	add.l %a2,%d2
.L266:
	move.b (%a2)+,(%a6)+
	cmp.l %d2,%a2
	jne .L266
.L265:
	moveq #-1,%d2
	add.l %a4,%a0
	add.l %d5,%a5
	lea (8,%a0),%a6
	move.l %a3,%a2
	move.w %d2,2(%a0)
	move.l %a3,%d2
	add.l #12,%d2
	move.l (%a5),4(%a0)
.L268:
	move.w (%a1)+,%d1
	jeq .L267
	move.w #1281,%d3
	move.b (%a2),4(%a6)
	move.w %d1,(%a6)
	addq.l #8,%a6
	move.w %d3,-6(%a6)
.L267:
	addq.l #1,%a2
	cmp.l %a2,%d2
	jne .L268
	tst.l %d0
	jeq .L287
	add.l %a0,%d0
	mov3q.l #-1,%d2
.L271:
	mvz.b (%a0)+,%d1
	move.w #8,%a1
	eor.l %d1,%d2
.L270:
	mov3q.l #1,%d1
	and.l %d2,%d1
	lsr.l #1,%d2
	subq.l #1,%a1
	neg.l %d1
	and.l #-306674912,%d1
	eor.l %d1,%d2
	tst.l %a1
	jne .L270
	cmp.l %d0,%a0
	jne .L271
	not.l %d2
	move.b %d2,%d3
	moveq #24,%d5
	addq.l #1,%d7
	move.l %d2,%d1
	move.l %d2,%d0
	lsr.l %d5,%d2
	lsr.l #8,%d0
	clr.w %d1
	swap %d1
	move.b %d2,12(%a4)
	move.b %d0,14(%a4)
	move.b %d3,15(%a4)
	move.b %d1,13(%a4)
	move.l %d6,%d1
.L260:
	move.l #out,%d3
	move.l %d3,%a0
.L272:
	clr.l (%a0)+
	cmp.l #out+32,%a0
	jne .L272
	moveq #1,%d0
	moveq #32,%d6
	move.l #1112686926,%d2
	clr.w %d5
	move.l %d2,out
	moveq #20,%d2
	move.w %d7,out+10
	move.w %d1,out+14
	move.b %d0,out+6
	moveq #78,%d0
	move.w %d6,out+4
	move.l #1112686921,%d6
	move.w %d5,out+12
	move.l %d6,out+20
	move.b %d0,out+24
	cmp.l %d1,%d2
	jeq .L288
	move.l %d1,%d5
	mov3q.l #-1,%d2
	add.l #out,%d5
	lea out+20,%a1
.L275:
	mvz.b (%a1)+,%d0
	move.w #8,%a0
	eor.l %d0,%d2
.L274:
	mov3q.l #1,%d0
	and.l %d2,%d0
	lsr.l #1,%d2
	subq.l #1,%a0
	neg.l %d0
	and.l #-306674912,%d0
	eor.l %d0,%d2
	tst.l %a0
	jne .L274
	cmp.l %a1,%d5
	jne .L275
	not.l %d2
.L273:
	move.l %d1,-(%sp)
	move.l %d3,-(%sp)
	pea .LC9
	move.l %d2,out+16
	jsr write_file
	lea (12,%sp),%sp
	addq.l #1,%d0
	tst.l %d0
	jeq .L289
	tst.l 76(%sp)
	jne .L357
	move.l %d4,%d3
	moveq #94,%d1
	lsl.l #3,%d3
	lea desc,%a2
	mulu.w #36,%d4
	mvz.w #154,%d0
	lea (12,%a3),%a1
	move.l %d4,%a0
	add.l #brain_fx+8,%a0
	lea 4(%a2,%d3.l),%a4
.L283:
	tst.w (%a0)+
	jne .L358
.L281:
	addq.l #1,%d1
	addq.l #1,%a3
	addq.l #4,%d0
	cmp.l %a3,%a1
	jne .L283
.L348:
	clr.l %d0
	clr.l %d4
	move.l %d0,brain_save_counts+4
	move.l %d4,%d0
	movem.l (%sp),#31996
	lea (64,%sp),%sp
	rts
.L243:
	move.b (%a0),%d1
	lea (%a2,%d0.l),%a4
	addq.l #1,%a0
	add.l %a5,%a4
	addq.l #1,%d0
	mov3q.l #6,%d3
	move.b %d1,(%a1)+
	move.b (%a4),5(%a1)
	cmp.l %d0,%d3
	jne .L245
	jra .L359
.L240:
	mov3q.l #1,%d0
	mov3q.l #-1,%d4
	move.l %d0,brain_save_counts+4
	move.l %d4,%d0
	movem.l (%sp),#31996
	lea (64,%sp),%sp
	rts
.L358:
	lea desc,%a5
	move.l (%a5,%d3.l),%a2
	tst.l %a2
	jeq .L282
	move.b (%a3),%d2
	mvz.b %d2,%d4
	cmp.l (%a2,%d0.l),%d4
	jcc .L282
	move.b %d2,(%a2,%d1.l)
.L282:
	move.l (%a4),%a2
	tst.l %a2
	jeq .L281
	move.b (%a3),%d2
	mvz.b %d2,%d4
	cmp.l (%a2,%d0.l),%d4
	jcc .L281
	move.b %d2,(%a2,%d1.l)
	addq.l #1,%d1
	addq.l #1,%a3
	addq.l #4,%d0
	cmp.l %a3,%a1
	jne .L283
	jra .L348
.L256:
	mov3q.l #3,%d0
	moveq #-3,%d4
	move.l %d0,brain_save_counts+4
	move.l %d4,%d0
	movem.l (%sp),#31996
	lea (64,%sp),%sp
	rts
.L246:
	pea .LC10
	jsr (%a2)
	addq.l #4,%sp
	move.l %d0,%d7
	tst.l %d0
	jeq .L347
	move.l %d7,-(%sp)
	lea valid,%a4
	jsr (%a4)
	addq.l #4,%sp
	tst.l %d0
	jeq .L251
	jra .L247
.L285:
	mov3q.l #1,%d0
	move.l %d0,brain_save_counts+4
	move.l %d4,%d0
	movem.l (%sp),#31996
	lea (64,%sp),%sp
	rts
.L286:
	clr.l %d7
.L347:
	moveq #32,%d1
	jra .L250
.L357:
	move.l %d4,%d1
	lsl.l #3,%d1
	lea desc,%a0
	move.l (%a0,%d1.l),%a1
	tst.l %a1
	jne .L360
.L277:
	lea desc,%a0
	lea 4(%a0,%d1.l),%a2
	move.l (%a2),%a1
	tst.l %a1
	jeq .L348
	moveq #24,%d1
	moveq #95,%d0
	muls.l %d4,%d1
	mulu.w #24,%d4
	move.l %d1,%a0
	add.l #shadow+12,%a0
	move.b (%a0),94(%a1)
	move.l %d4,%a0
	add.l #shadow+13,%a0
.L280:
	move.l (%a2),%a1
	moveq #106,%d1
	move.b (%a0)+,(%a1,%d0.l)
	addq.l #1,%d0
	cmp.l %d0,%d1
	jeq .L348
	move.l (%a2),%a1
	moveq #106,%d1
	move.b (%a0)+,(%a1,%d0.l)
	addq.l #1,%d0
	cmp.l %d0,%d1
	jne .L280
	jra .L348
.L360:
	move.w %d4,%d3
	moveq #24,%d2
	moveq #95,%d0
	muls.l %d4,%d2
	move.l %d2,%a0
	add.l #shadow,%a0
	mulu.w #24,%d3
	move.b (%a0),94(%a1)
	move.l %d3,%a0
	add.l #shadow+1,%a0
.L278:
	lea desc,%a2
	moveq #106,%d2
	move.l (%a2,%d1.l),%a1
	move.b (%a0)+,(%a1,%d0.l)
	addq.l #1,%d0
	cmp.l %d0,%d2
	jeq .L277
	lea desc,%a2
	moveq #106,%d2
	move.l (%a2,%d1.l),%a1
	move.b (%a0)+,(%a1,%d0.l)
	addq.l #1,%d0
	cmp.l %d0,%d2
	jne .L278
	jra .L277
.L289:
	mov3q.l #4,%d0
	moveq #-4,%d4
	move.l %d0,brain_save_counts+4
	move.l %d4,%d0
	movem.l (%sp),#31996
	lea (64,%sp),%sp
	rts
.L288:
	clr.l %d2
	jra .L273
.L287:
	clr.b %d1
	clr.b %d3
	clr.b %d0
	clr.b %d2
	addq.l #1,%d7
	move.b %d1,13(%a4)
	move.b %d3,15(%a4)
	move.b %d0,14(%a4)
	move.b %d2,12(%a4)
	move.l %d6,%d1
	jra .L260
	.size	write_default, .-write_default
	.align	2
	.globl	brain_load
	.type	brain_load, @function
brain_load:
	lea (-20,%sp),%sp
	movem.l #7180,(%sp)
	lea brain_counts+4,%a0
.L362:
	clr.l (%a0)+
	cmp.l #brain_counts+48,%a0
	jne .L362
	addq.l #1,brain_counts
	tst.l snapped
	jeq .L406
.L363:
	move.l brain_fx_n,%d2
	tst.l %d2
	jeq .L364
	lea desc,%a3
	clr.l %d1
	lea shadow,%a4
	lea desc+4,%a2
.L365:
	move.l (%a3),%a1
	tst.l %a1
	jne .L407
.L369:
	move.l (%a2),%a0
	tst.l %a0
	jne .L408
.L371:
	addq.l #1,%d1
	cmp.l %d2,%d1
	jeq .L364
	addq.l #8,%a3
	lea (24,%a4),%a4
	addq.l #8,%a2
	moveq #32,%d0
	cmp.l %d1,%d0
	jne .L365
.L364:
	move.l table_len,%d0
	tst.l %d0
	jeq .L368
	move.l brain_modedef,%a1
	lea table_shadow,%a0
	add.l %a0,%d0
.L373:
	move.b (%a0)+,(%a1)+
	cmp.l %a0,%d0
	jne .L373
.L368:
	pea .LC9
	lea slurp,%a2
	jsr (%a2)
	addq.l #4,%sp
	tst.l %d0
	jeq .L374
	move.l %d0,-(%sp)
	lea valid,%a3
	jsr (%a3)
	addq.l #4,%sp
	tst.l %d0
	jne .L409
	pea .LC10
	jsr (%a2)
	addq.l #4,%sp
	tst.l %d0
	jeq .L378
	move.l %d0,-(%sp)
	jsr (%a3)
	addq.l #4,%sp
	tst.l %d0
	jne .L410
.L378:
	mov3q.l #3,%d0
.L377:
	movem.l (%sp),#7180
	move.l %d0,brain_counts+4
	lea (20,%sp),%sp
	rts
.L408:
	move.b 12(%a4),94(%a0)
	lea (13,%a4),%a0
	moveq #95,%d0
.L372:
	move.l (%a2),%a1
	moveq #106,%d3
	move.b (%a0)+,(%a1,%d0.l)
	addq.l #1,%d0
	cmp.l %d0,%d3
	jeq .L371
	move.l (%a2),%a1
	moveq #106,%d3
	move.b (%a0)+,(%a1,%d0.l)
	addq.l #1,%d0
	cmp.l %d0,%d3
	jne .L372
	jra .L371
.L407:
	move.l %a4,%a0
	moveq #95,%d0
	move.b (%a0)+,94(%a1)
.L370:
	move.l (%a3),%a1
	moveq #106,%d3
	move.b (%a0)+,(%a1,%d0.l)
	addq.l #1,%d0
	cmp.l %d0,%d3
	jeq .L369
	move.l (%a3),%a1
	moveq #106,%d3
	move.b (%a0)+,(%a1,%d0.l)
	addq.l #1,%d0
	cmp.l %d0,%d3
	jne .L370
	jra .L369
.L406:
	jsr snapshot
	jra .L363
.L374:
	pea .LC10
	jsr (%a2)
	addq.l #4,%sp
	tst.l %d0
	jeq .L377
	move.l %d0,-(%sp)
	lea valid,%a3
	jsr (%a3)
	addq.l #4,%sp
	tst.l %d0
	jeq .L378
.L410:
	movem.l (%sp),#7180
	mov3q.l #2,brain_counts+4
	lea (20,%sp),%sp
	jra (apply.isra.0)
.L409:
	movem.l (%sp),#7180
	mov3q.l #1,brain_counts+4
	lea (20,%sp),%sp
	jra (apply.isra.0)
	.size	brain_load, .-brain_load
	.align	2
	.globl	brain_save_default
	.type	brain_save_default, @function
brain_save_default:
	clr.l -(%sp)
	move.l 12(%sp),-(%sp)
	move.l 12(%sp),-(%sp)
	jsr write_default
	lea (12,%sp),%sp
	rts
	.size	brain_save_default, .-brain_save_default
	.align	2
	.globl	brain_clear_default
	.type	brain_clear_default, @function
brain_clear_default:
	mov3q.l #1,-(%sp)
	move.l 12(%sp),-(%sp)
	move.l 12(%sp),-(%sp)
	jsr write_default
	lea (12,%sp),%sp
	rts
	.size	brain_clear_default, .-brain_clear_default
	.align	2
	.globl	brain_card_store
	.type	brain_card_store, @function
brain_card_store:
	subq.l #4,%sp
	pea .LC9
	jsr slurp
	addq.l #4,%sp
	tst.l %d0
	jeq .L415
	move.l %d0,-(%sp)
	move.l %d0,4(%sp)
	jsr valid
	addq.l #4,%sp
	move.l (%sp),%d1
	tst.l %d0
	jne .L426
.L415:
	addq.l #4,%sp
	rts
.L426:
	moveq #1,%d0
	move.l %d1,-(%sp)
	pea buf
	pea .LC10
	move.b %d0,buf+8
	jsr write_file
	lea (12,%sp),%sp
	addq.l #1,%d0
	tst.l %d0
	jeq .L427
	addq.l #1,brain_save_counts+8
	addq.l #4,%sp
	rts
.L427:
	addq.l #1,brain_save_counts+12
	addq.l #4,%sp
	rts
	.size	brain_card_store, .-brain_card_store
	.align	2
	.globl	brain_post_save
	.type	brain_post_save, @function
brain_post_save:
	move.l %d2,-(%sp)
	tst.l 12(%sp)
	sne %d0
	mov3q.l #7,%d1
	and.l 8(%sp),%d1
	lea job_msg,%a0
	moveq #65,%d2
	move.l %a0,12(%sp)
	mvs.b %d0,%d0
	neg.l %d0
	lsl.l #8,%d0
	move.b %d2,job_msg
	move.l #1175263182,%d2
	move.l %d2,8(%sp)
	move.l (%sp)+,%d2
	or.l %d1,%d0
	move.l %d0,job_args
	jmp 1073744956
	.size	brain_post_save, .-brain_post_save
	.align	2
	.globl	brain_post_store
	.type	brain_post_store, @function
brain_post_store:
	lea job_msg,%a0
	moveq #1,%d0
	swap %d0
	move.b #65,(%a0)
	move.l %a0,-(%sp)
	move.l #1175263182,-(%sp)
	move.l %d0,job_args
	jsr 1073744956
	addq.l #8,%sp
	rts
	.size	brain_post_store, .-brain_post_store
	.align	2
	.globl	brain_post_clear
	.type	brain_post_clear, @function
brain_post_clear:
	move.l %d2,-(%sp)
	tst.l 12(%sp)
	sne %d0
	mov3q.l #7,%d1
	and.l 8(%sp),%d1
	lea job_msg,%a0
	moveq #65,%d2
	move.l %a0,12(%sp)
	mvs.b %d0,%d0
	neg.l %d0
	lsl.l #8,%d0
	move.b %d2,job_msg
	move.l #1175263182,%d2
	move.l %d2,8(%sp)
	move.l (%sp)+,%d2
	or.l %d1,%d0
	bset #9,%d0
	move.l %d0,job_args
	jmp 1073744956
	.size	brain_post_clear, .-brain_post_clear
	.align	2
	.globl	brain_job
	.type	brain_job, @function
brain_job:
	move.l job_args,%d0
	move.l %d3,-(%sp)
	move.l %d2,-(%sp)
	btst #16,%d0
	jeq .L435
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	jra brain_card_store
.L435:
	moveq #9,%d2
	move.l %d0,%d1
	lsr.l %d2,%d1
	mov3q.l #1,%d2
	move.l %d1,%d3
	move.l %d0,%d1
	and.l %d2,%d3
	lsr.l #8,%d1
	move.l %d3,-(%sp)
	mov3q.l #1,%d3
	and.l %d1,%d3
	mov3q.l #7,%d1
	and.l %d0,%d1
	move.l %d3,-(%sp)
	move.l %d1,-(%sp)
	jsr write_default
	lea (12,%sp),%sp
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	rts
	.size	brain_job, .-brain_job
	.section	.rodata.str1.1
.LC11:
	.string	"SAVED AS DEFAULT"
.LC12:
	.string	"SAVE AS DEFAULT"
	.text
	.align	2
	.globl	brain_menu_save
	.type	brain_menu_save, @function
brain_menu_save:
	move.l %d2,-(%sp)
	jsr menu_target
	mov3q.l #-1,%d1
	cmp.l %d0,%d1
	jne .L445
	clr.l -(%sp)
	clr.l -(%sp)
	pea msg
	mov3q.l #2,-(%sp)
	pea .LC12
	jsr 1074189692
	lea (20,%sp),%sp
	move.l (%sp)+,%d2
	rts
.L445:
	moveq #65,%d2
	move.b -2147483648,%d1
	lsl.l #8,%d0
	pea job_msg
	move.l #1175263182,-(%sp)
	move.b %d2,job_msg
	mov3q.l #7,%d2
	and.l %d2,%d1
	or.l %d0,%d1
	move.l %d1,job_args
	jsr 1073744956
	addq.l #8,%sp
	clr.l -(%sp)
	clr.l -(%sp)
	pea msg
	move.l #.LC11,%d0
	mov3q.l #2,-(%sp)
	move.l %d0,msg+4
	pea .LC12
	jsr 1074189692
	lea (20,%sp),%sp
	move.l (%sp)+,%d2
	rts
	.size	brain_menu_save, .-brain_menu_save
	.section	.rodata.str1.1
.LC13:
	.string	"DEFAULT CLEARED"
.LC14:
	.string	"CLEAR DEFAULT"
	.text
	.align	2
	.globl	brain_menu_clear
	.type	brain_menu_clear, @function
brain_menu_clear:
	move.l %d2,-(%sp)
	jsr menu_target
	mov3q.l #-1,%d1
	cmp.l %d0,%d1
	jne .L453
	clr.l -(%sp)
	clr.l -(%sp)
	pea msg
	mov3q.l #2,-(%sp)
	pea .LC14
	jsr 1074189692
	lea (20,%sp),%sp
	move.l (%sp)+,%d2
	rts
.L453:
	moveq #65,%d2
	move.b -2147483648,%d1
	lsl.l #8,%d0
	pea job_msg
	move.l #1175263182,-(%sp)
	move.b %d2,job_msg
	mov3q.l #7,%d2
	and.l %d2,%d1
	or.l %d0,%d1
	bset #9,%d1
	move.l %d1,job_args
	jsr 1073744956
	addq.l #8,%sp
	clr.l -(%sp)
	clr.l -(%sp)
	pea msg
	move.l #.LC13,%d0
	mov3q.l #2,-(%sp)
	move.l %d0,msg+4
	pea .LC14
	jsr 1074189692
	lea (20,%sp),%sp
	move.l (%sp)+,%d2
	rts
	.size	brain_menu_clear, .-brain_menu_clear
	.local	line1
	.comm	line1,16,1
	.local	msg
	.comm	msg,8,2
	.local	job_args
	.comm	job_args,4,2
	.local	job_msg
	.comm	job_msg,16,2
	.local	out
	.comm	out,16384,4
	.globl	brain_save_counts
	.section	.bss
	.align	2
	.type	brain_save_counts, @object
	.size	brain_save_counts, 16
brain_save_counts:
	.zero	16
	.local	buf
	.comm	buf,16384,1
	.local	iob
	.comm	iob,4096,1
	.local	fobj
	.comm	fobj,24,1
	.local	snapped
	.comm	snapped,4,2
	.local	desc
	.comm	desc,256,2
	.local	table_len
	.comm	table_len,4,2
	.local	table_shadow
	.comm	table_shadow,1024,1
	.local	shadow
	.comm	shadow,768,1
	.globl	brain_counts
	.align	2
	.type	brain_counts, @object
	.size	brain_counts, 48
brain_counts:
	.zero	48


| ---- hooks.s: the two load-path detours and the per-remix table --------------
|
| Both sites are on the engine task's load path, before the banks are read:
|   0x40085342  LOAD PROJECT, before the empty-project init 0x400909d8:
|               `moveq #27,%d1 / movel %d1,%fp@(-570)`
|   0x40084d4a  the bank load every bank but the current (the power-up's
|               path too): `mvzb 0x80000002,%d1`
| Each stub keeps every register, calls brain_load and replays what the
| detour displaced.

        .include "remix.inc"           | brain_fx, brain_fx_n (manifest.py fx_inc)

| MODE DEFAULTS' view table, or 0 when that module is not in the remix
| (Linked.defsyms resolves MODEDEF_TABLE).
        .section .rodata
        .balign 4
        .globl  brain_modedef
brain_modedef: .long MODEDEF_TABLE

        .text
        .globl  brain_on_load, brain_on_bankload
brain_on_load:
        lea     %sp@(-16),%sp
        movem.l %d0-%d1/%a0-%a1,%sp@
        jsr     brain_load
        movem.l %sp@,%d0-%d1/%a0-%a1
        lea     %sp@(16),%sp
        moveq   #27,%d1
        move.l  %d1,%fp@(-570)
        rts
brain_on_bankload:
        lea     %sp@(-16),%sp
        movem.l %d0-%d1/%a0-%a1,%sp@
        jsr     brain_load
        movem.l %sp@,%d0-%d1/%a0-%a1
        lea     %sp@(16),%sp
        mvz.b   0x80000002,%d1
        rts

| ---- SAVE PROJECT: card.work -> card.strd --------------------------------------
| The project store 0x4008ee74 is called from 0x40085642, 0x400856dc and
| 0x40085780; KITS hooks its entry. Each call site jumps here: copy, then
| tail-call the store with the caller's arguments (PLOCKS P2's form).
        .globl  brain_on_store
brain_on_store:
        lea     %sp@(-16),%sp
        movem.l %d0-%d1/%a0-%a1,%sp@
        jsr     brain_card_store
        movem.l %sp@,%d0-%d1/%a0-%a1
        lea     %sp@(16),%sp
        jmp     0x4008ee74

| ---- the engine task's job switch --------------------------------------------
|   0x4008485e  `mvzb %a2@,%d0 / moveq #45,%d1 / cmpl %d0,%d1`, then bcss
|               0x4008484e (a type above 45 goes back to the receive) and the
|               jump table. Type 0x41 runs brain_job and goes back to the
|               receive; every other type takes the stock path.
        .globl  brain_on_job
brain_on_job:
        mvz.b   %a2@,%d0
        cmp.l   #0x41,%d0
        bne.s   1f
        lea     %sp@(-16),%sp
        movem.l %d0-%d1/%a0-%a1,%sp@
        jsr     brain_job
        movem.l %sp@,%d0-%d1/%a0-%a1
        lea     %sp@(16),%sp
        jmp     0x4008484e
1:      moveq   #45,%d1
        cmp.l   %d0,%d1
        jmp     0x40084864
