#!/usr/bin/env python3
"""Generate a BRANCH-FREE X-memory probe for one address.

    python3 tools/gen_probe.py <addr_hex> > dsp/probe.asm

The first probe used conditional branches and hung the DSP even against
addresses that certainly exist, so the branches themselves are suspect:
dsp56kEmu's assembler emits 2-word long-form branches (0d104a / 0d10c0) for tiny
displacements, while the stock firmware only ever uses 1-word short forms
(05a404 / 050c84). The emulator accepts its own encodings by construction.

So this version has no branches at all. It stores a mask at the probe address and
reads it back as the mask it applies to the audio:

    heavy distortion -> the address is real and held the value
    silence          -> read back 0 (memory absent, reads as zero)
    clean audio      -> read back all-ones
    anything else    -> garbage, still audible as *something* wrong

Every instruction used here appears in the stock firmware.
"""
import sys
addr = sys.argv[1]
print(f"""; branch-free probe of X:0x{addr}   (generated by tools/gen_probe.py)
; init: stamp the mask.  process: read it back and apply it.
init:
        move    #>$e00000,x0
        move    x0,x:>${addr}
        rts
proc:
        move    x:>${addr},y0
        move    r0,r1
        do      n7,>loopend
        move    x:(r0)+,a
        move    x:(r0)+,b
        and     y0,a
        and     y0,b
        move    a,x:(r1)+
        move    b,x:(r1)+
loopend:
        rts""")
