| Generated by modules/core/generate_core.py; edit core.c / hooks.s.
#NO_APP
	.file	"core.c"
	.text
	.section	.rodata.str1.1,"aMS",@progbits,1
.LC0:
	.string	"r"
	.text
	.align	2
	.type	slurp, @function
slurp:
	subq.l #4,%sp
	move.l %d2,-(%sp)
	pea 4096.w
	pea iob
	pea .LC0
	move.l 24(%sp),-(%sp)
	pea fobj
	jsr 1073834084
	lea (20,%sp),%sp
	tst.l %d0
	jlt .L6
	pea 32.w
	pea buf
	pea fobj
	jsr 1073833316
	lea (12,%sp),%sp
	subq.l #1,%d0
	tst.l %d0
	jeq .L3
.L13:
	mov3q.l #1,%d1
.L4:
	pea fobj
	move.l %d1,8(%sp)
	jsr 1073833852
	addq.l #4,%sp
	move.l 4(%sp),%d1
	move.l %d1,%d0
	move.l (%sp)+,%d2
	addq.l #4,%sp
	rts
.L3:
	move.l buf+12,%d1
	move.l %d1,%d0
	add.l #-32,%d0
	cmp.l #16352,%d0
	jhi .L13
	moveq #32,%d2
	cmp.l %d1,%d2
	jeq .L4
	move.l %d0,-(%sp)
	pea buf+32
	pea fobj
	move.l %d1,16(%sp)
	jsr 1073833316
	lea (12,%sp),%sp
	subq.l #1,%d0
	move.l 4(%sp),%d1
	tst.l %d0
	jeq .L4
	mov3q.l #1,%d1
	jra .L4
.L6:
	move.l (%sp)+,%d2
	clr.l %d1
	move.l %d1,%d0
	addq.l #4,%sp
	rts
	.size	slurp, .-slurp
	.align	2
	.type	valid, @function
valid:
	lea (-20,%sp),%sp
	moveq #31,%d0
	movem.l #1036,(%sp)
	cmp.l 24(%sp),%d0
	jcc .L19
	move.l #1329742157,%d1
	cmp.l buf.l,%d1
	jeq .L30
.L19:
	movem.l (%sp),#1036
	clr.l %d0
	lea (20,%sp),%sp
	rts
.L30:
	mvz.w buf+4,%d0
	moveq #32,%d2
	cmp.l %d0,%d2
	jne .L19
	mvz.b buf+6,%d0
	subq.l #1,%d0
	tst.l %d0
	jne .L19
	move.l 24(%sp),%a1
	cmp.l buf+12.l,%a1
	jne .L19
	add.l #buf,%a1
	move.l %a1,12(%sp)
	mov3q.l #-1,%d1
	lea buf+20,%a1
.L21:
	mvz.b (%a1)+,%d0
	move.w #8,%a0
	eor.l %d0,%d1
.L20:
	mov3q.l #1,%d0
	and.l %d1,%d0
	lsr.l #1,%d1
	subq.l #1,%a0
	neg.l %d0
	and.l #-306674912,%d0
	eor.l %d0,%d1
	tst.l %a0
	jne .L20
	cmp.l 12(%sp),%a1
	jne .L21
	not.l %d1
	cmp.l buf+16.l,%d1
	jne .L19
	mvz.w buf+10,%d0
	move.l %d0,16(%sp)
	tst.l %d0
	jeq .L24
	moveq #32,%d0
.L23:
	move.l %d0,%d1
	addq.l #1,%a0
	add.l #20,%d1
	cmp.l 24(%sp),%d1
	jhi .L19
	lea buf,%a1
	moveq #-4,%d3
	mvz.b 1(%a1,%d0.l),%d1
	move.l %d1,%a1
	addq.l #3,%a1
	move.l %a1,%d2
	subq.l #1,%d1
	and.l %d3,%d2
	move.l %d2,%a1
	moveq #62,%d2
	cmp.l %d1,%d2
	jcs .L19
	lea buf+8,%a2
	move.l (%a2,%d0.l),%d1
	addq.l #3,%d1
	and.l %d3,%d1
	lea buf+16,%a2
	lea 20(%a1,%d1.l),%a1
	cmp.l (%a2,%d0.l),%a1
	jne .L19
	add.l %a1,%d0
	cmp.l 24(%sp),%d0
	jhi .L19
	cmp.l 16(%sp),%a0
	jne .L23
	cmp.l 24(%sp),%d0
	seq %d0
	mvs.b %d0,%d0
	neg.l %d0
.L31:
	movem.l (%sp),#1036
	lea (20,%sp),%sp
	rts
.L24:
	moveq #32,%d0
	cmp.l 24(%sp),%d0
	seq %d0
	mvs.b %d0,%d0
	neg.l %d0
	jra .L31
	.size	valid, .-valid
	.align	2
	.type	apply.isra.0, @function
apply.isra.0:
	mvz.w buf+10,%d0
	lea (-576,%sp),%sp
	movem.l #31996,(%sp)
	tst.l %d0
	jeq .L32
	move.w #32,%a6
	move.l core_fx_n,%d4
	move.l %d0,%d5
	move.l core_counts+8,%a3
	clr.l %d1
	lea buf+16,%a4
	add.l %a3,%d5
.L47:
	move.l %a6,%a2
	add.l #buf,%a2
	mvz.b (%a2),%d0
	addq.l #1,%a3
	move.l %a3,core_counts+8
	subq.l #2,%d0
	tst.l %d0
	jne .L41
	move.l 8(%a2),%d3
	mvz.b 1(%a2),%d6
	tst.l %d3
	jeq .L35
	move.l %d6,%d0
	moveq #-4,%d7
	addq.l #3,%d0
	and.l %d7,%d0
	mov3q.l #-1,%d2
	lea 20(%a2,%d0.l),%a1
	add.l %a1,%d3
.L37:
	mvz.b (%a1)+,%d0
	move.w #8,%a0
	eor.l %d0,%d2
.L36:
	mov3q.l #1,%d0
	and.l %d2,%d0
	lsr.l #1,%d2
	subq.l #1,%a0
	neg.l %d0
	and.l #-306674912,%d0
	eor.l %d0,%d2
	tst.l %a0
	jne .L36
	cmp.l %d3,%a1
	jne .L37
	move.l %d2,%d3
	not.l %d3
.L35:
	cmp.l 12(%a2),%d3
	jne .L38
	tst.l %d4
	jeq .L40
	lea core_fx+4,%a5
	clr.l %d7
.L46:
	mvz.b 29(%a5),%d0
	cmp.l %d6,%d0
	jne .L42
	tst.l %d6
	jeq .L43
	move.l (%a5),%a0
	move.l %a0,%d3
	lea (20,%a2),%a1
	add.l %d6,%d3
.L44:
	mvz.b (%a1),%d2
	mvz.b (%a0),%d0
	addq.l #1,%a1
	addq.l #1,%a0
	cmp.l %d2,%d0
	jne .L42
	cmp.l %a0,%d3
	jne .L44
.L43:
	moveq #63,%d0
	cmp.l %d1,%d0
	jcs .L41
	lea (%sp,%d1.l*4),%a0
	addq.l #1,%d1
	move.l %a2,64(%a0)
	move.l %d7,320(%a0)
.L41:
	add.l (%a4,%a6.l),%a6
	cmp.l %a3,%d5
	jne .L47
.L107:
	tst.l %d1
	jeq .L32
	clr.l %d0
	lea (320,%sp),%a0
	lea (64,%sp),%a5
.L67:
	move.l (%a5)+,%a3
	moveq #-4,%d6
	move.l %sp,%d3
	clr.l %d5
	lea (320,%sp),%a2
	add.l #64,%d3
	mvz.b 1(%a3),%d4
	clr.l %d2
	addq.l #3,%d4
	and.l %d6,%d4
	lea 20(%a3,%d4.l),%a1
.L51:
	move.l %d3,%a4
	addq.l #4,%d3
	cmp.l %d0,%d2
	jeq .L49
	move.l (%a0),%d7
	cmp.l (%a2),%d7
	jeq .L105
.L49:
	addq.l #1,%d2
	addq.l #4,%a2
	cmp.l %d2,%d1
	jne .L51
.L106:
	tst.l %d5
	jeq .L52
	addq.l #1,core_counts+36
.L53:
	addq.l #1,%d0
	addq.l #4,%a0
	cmp.l %d0,%d1
	jne .L67
.L32:
	movem.l (%sp),#31996
	lea (576,%sp),%sp
	rts
.L105:
	move.l (%a4),%a4
	moveq #-4,%d6
	move.l (%a1),%d7
	addq.l #1,%d2
	addq.l #4,%a2
	mvz.b 1(%a4),%d4
	addq.l #3,%d4
	and.l %d6,%d4
	cmp.l 20(%a4,%d4.l),%d7
	seq %d4
	mvs.b %d4,%d4
	neg.l %d4
	or.l %d4,%d5
	cmp.l %d2,%d1
	jne .L51
	jra .L106
.L42:
	addq.l #1,%d7
	cmp.l %d7,%d4
	jeq .L40
	lea (36,%a5),%a5
	cmp.l #core_fx+1156,%a5
	jne .L46
.L40:
	add.l (%a4,%a6.l),%a6
	addq.l #1,core_counts+20
	cmp.l %a3,%d5
	jne .L47
	jra .L107
.L52:
	mvz.w 2(%a3),%d2
	subq.l #1,%d2
	tst.l %d2
	jne .L53
	move.l 8(%a3),%a6
	mov3q.l #7,%d4
	cmp.l %a6,%d4
	jcc .L53
	tst.w (%a1)
	jne .L54
	mvz.w 2(%a1),%d2
	cmp.l #65535,%d2
	jeq .L55
.L54:
	addq.l #1,core_counts+28
	addq.l #1,%d0
	addq.l #4,%a0
	cmp.l %d0,%d1
	jne .L67
	jra .L32
.L38:
	add.l (%a4,%a6.l),%a6
	addq.l #1,core_counts+32
	cmp.l %a3,%d5
	jne .L47
	jra .L107
.L55:
	move.l (%a0),50(%sp)
	move.l 50(%sp),%d5
	moveq #36,%d6
	lea core_fx,%a2
	muls.l %d6,%d5
	move.l (%a2,%d5.l),%a2
	move.l %d5,56(%sp)
	cmp.l 4(%a1),%a2
	jne .L108
	addq.l #1,core_counts+12
	moveq #11,%d7
	cmp.l %a6,%d7
	jcc .L53
	moveq #8,%d3
	moveq #12,%d5
	move.l %d3,%d6
	mvz.b 3(%a1,%d3.l),%d4
	cmp.l #255,%d4
	jeq .L57
.L110:
	addq.l #4,%d6
.L58:
	move.l %d4,%d2
	moveq #-4,%d5
	addq.l #3,%d2
	and.l %d5,%d2
	add.l %d6,%d2
	cmp.l %a6,%d2
	jhi .L53
	mvz.b 2(%a1,%d3.l),%d5
	subq.l #5,%d5
	tst.l %d5
	jeq .L109
.L59:
	move.l %d2,%d5
	addq.l #4,%d5
	cmp.l %a6,%d5
	jhi .L53
	move.l %d2,%d3
	move.l %d3,%d6
	mvz.b 3(%a1,%d3.l),%d4
	cmp.l #255,%d4
	jne .L110
.L57:
	addq.l #8,%d6
	cmp.l %a6,%d6
	jhi .L53
	move.l (%a1,%d5.l),%d4
	jra .L58
.L109:
	subq.l #1,%d4
	tst.l %d4
	jne .L59
	mvz.w (%a1,%d3.l),%d5
	tst.l %d5
	jeq .L59
	move.b (%a1,%d6.l),%d6
	move.l 50(%sp),%d7
	moveq #94,%d4
	mvz.w #154,%d3
	move.l 56(%sp),%a4
	add.l #core_fx+8,%a4
	lsl.l #3,%d7
	move.l %d0,46(%sp)
	move.b %d6,55(%sp)
	mvz.b %d6,%d6
	move.l %d6,60(%sp)
.L65:
	mvz.w (%a4)+,%d6
	cmp.l %d5,%d6
	jeq .L111
.L60:
	addq.l #1,%d4
	addq.l #4,%d3
	cmp.l #202,%d3
	jne .L65
	move.l 46(%sp),%d0
	jra .L59
.L108:
	addq.l #1,core_counts+24
	addq.l #1,%d0
	addq.l #4,%a0
	cmp.l %d0,%d1
	jne .L67
	jra .L32
.L111:
	move.l %d7,%a2
	add.l #desc,%a2
	move.l (%a2)+,%a3
	tst.l %a3
	jeq .L84
	clr.l %d6
.L64:
	move.l 60(%sp),%d0
	cmp.l (%a3,%d3.l),%d0
	jcc .L62
	move.b 55(%sp),%d0
	subq.l #1,%d6
	move.b %d0,(%a3,%d4.l)
	addq.l #1,core_counts+16
	tst.l %d6
	jeq .L60
.L84:
	move.l (%a2),%a3
	tst.l %a3
	jeq .L60
	addq.l #4,%a2
	mov3q.l #1,%d6
	jra .L64
.L62:
	addq.l #1,core_counts+40
	subq.l #1,%d6
	tst.l %d6
	jeq .L60
	jra .L84
	.size	apply.isra.0, .-apply.isra.0
	.section	.rodata.str1.1
.LC1:
	.string	"/OCTABAM/card.work"
.LC2:
	.string	"/OCTABAM/card.strd"
	.text
	.align	2
	.globl	core_load
	.type	core_load, @function
core_load:
	lea (-32,%sp),%sp
	movem.l #31772,(%sp)
	lea core_counts+4,%a0
.L113:
	clr.l (%a0)+
	cmp.l #core_counts+44,%a0
	jne .L113
	move.l snapped,%d1
	move.l core_fx_n,%d2
	addq.l #1,core_counts
	tst.l %d1
	jeq .L180
	tst.l %d2
	jeq .L130
	lea desc,%a3
	clr.l %d1
	lea shadow,%a4
	lea desc+4,%a2
.L132:
	move.l (%a3),%a1
	tst.l %a1
	jne .L181
.L133:
	move.l (%a2),%a0
	tst.l %a0
	jne .L182
.L135:
	addq.l #1,%d1
	cmp.l %d1,%d2
	jeq .L130
	addq.l #8,%a3
	lea (24,%a4),%a4
	addq.l #8,%a2
	moveq #32,%d3
	cmp.l %d1,%d3
	jne .L132
.L130:
	pea .LC1
	lea slurp,%a2
	jsr (%a2)
	addq.l #4,%sp
	tst.l %d0
	jeq .L137
	move.l %d0,-(%sp)
	lea valid,%a3
	jsr (%a3)
	addq.l #4,%sp
	tst.l %d0
	jne .L183
	pea .LC2
	jsr (%a2)
	addq.l #4,%sp
	tst.l %d0
	jeq .L141
	move.l %d0,-(%sp)
	jsr (%a3)
	addq.l #4,%sp
	tst.l %d0
	jne .L184
.L141:
	mov3q.l #3,%d0
.L140:
	movem.l (%sp),#31772
	move.l %d0,core_counts+4
	lea (32,%sp),%sp
	rts
.L182:
	move.b 12(%a4),94(%a0)
	lea (13,%a4),%a0
	moveq #95,%d0
.L136:
	move.l (%a2),%a1
	moveq #106,%d3
	move.b (%a0)+,(%a1,%d0.l)
	addq.l #1,%d0
	cmp.l %d0,%d3
	jeq .L135
	move.l (%a2),%a1
	moveq #106,%d3
	move.b (%a0)+,(%a1,%d0.l)
	addq.l #1,%d0
	cmp.l %d0,%d3
	jne .L136
	jra .L135
.L181:
	move.l %a4,%a0
	moveq #95,%d0
	move.b (%a0)+,94(%a1)
.L134:
	move.l (%a3),%a1
	moveq #106,%d3
	move.b (%a0)+,(%a1,%d0.l)
	addq.l #1,%d0
	cmp.l %d0,%d3
	jeq .L133
	move.l (%a3),%a1
	moveq #106,%d3
	move.b (%a0)+,(%a1,%d0.l)
	addq.l #1,%d0
	cmp.l %d0,%d3
	jne .L134
	jra .L133
.L137:
	pea .LC2
	jsr (%a2)
	addq.l #4,%sp
	tst.l %d0
	jeq .L140
	move.l %d0,-(%sp)
	lea valid,%a3
	jsr (%a3)
	addq.l #4,%sp
	tst.l %d0
	jeq .L141
	jra .L184
.L180:
	tst.l %d2
	jeq .L115
	lea core_fx+32,%a5
	lea desc,%a4
	move.l #shadow+12,%d3
	lea desc+4,%a3
	move.l #1074618332,%a6
.L128:
	mvz.b (%a5),%d4
	move.l %d4,%d0
	lsl.l #2,%d0
	move.l (%a6,%d0.l),%a2
	move.l %d0,%a0
	add.l #1074618200,%a0
	tst.l %a2
	jeq .L116
	cmp.l (%a2),%d4
	jne .L116
	move.l %a2,(%a4)
	move.l (%a0),%a0
	tst.l %a0
	jeq .L124
	cmp.l (%a0),%d4
	jne .L124
	cmp.l %a2,%a0
	jeq .L124
	move.l %a0,(%a3)
	move.l %d3,%a1
	move.l %a2,%d0
	lea (94,%a2),%a0
	add.l #106,%d0
	lea (-12,%a1),%a1
.L125:
	move.b (%a0)+,(%a1)+
	cmp.l %d0,%a0
	jne .L125
	move.l (%a3),%d0
	tst.l %d0
	jne .L123
.L120:
	addq.l #1,%d1
	cmp.l %d1,%d2
	jeq .L173
	lea (36,%a5),%a5
	addq.l #8,%a4
	add.l #24,%d3
	addq.l #8,%a3
	moveq #32,%d0
	cmp.l %d1,%d0
	jne .L128
.L173:
	mov3q.l #1,snapped
	lea desc,%a3
	clr.l %d1
	lea shadow,%a4
	lea desc+4,%a2
	jra .L132
.L116:
	clr.l (%a4)
	move.l (%a0),%d0
	tst.l %d0
	jeq .L174
	move.l %d0,%a0
	cmp.l (%a0),%d4
	jne .L174
	move.l %d0,(%a3)
.L123:
	move.l %d0,%a0
	move.l %d3,%a1
	lea (94,%a0),%a0
	add.l #106,%d0
.L126:
	move.b (%a0)+,(%a1)+
	cmp.l %d0,%a0
	jeq .L120
	move.b (%a0)+,(%a1)+
	cmp.l %d0,%a0
	jne .L126
	jra .L120
.L124:
	move.l %d3,%a1
	move.l %a2,%d0
	clr.l (%a3)
	lea (94,%a2),%a0
	add.l #106,%d0
	lea (-12,%a1),%a1
	jra .L125
.L174:
	clr.l (%a3)
	jra .L120
.L184:
	movem.l (%sp),#31772
	mov3q.l #2,core_counts+4
	lea (32,%sp),%sp
	jra (apply.isra.0)
.L183:
	movem.l (%sp),#31772
	mov3q.l #1,core_counts+4
	lea (32,%sp),%sp
	jra (apply.isra.0)
.L115:
	mov3q.l #1,snapped
	jra .L130
	.size	core_load, .-core_load
	.local	buf
	.comm	buf,16384,1
	.local	iob
	.comm	iob,4096,1
	.local	fobj
	.comm	fobj,24,1
	.local	snapped
	.comm	snapped,4,2
	.local	desc
	.comm	desc,256,2
	.local	shadow
	.comm	shadow,768,1
	.globl	core_counts
	.section	.bss
	.align	2
	.type	core_counts, @object
	.size	core_counts, 44
core_counts:
	.zero	44


| ---- hooks.s: the two load-path detours and the per-remix table --------------
|
| Both sites are on the engine task's load path, before the banks are read:
|   0x40085342  LOAD PROJECT, before the empty-project init 0x400909d8:
|               `moveq #27,%d1 / movel %d1,%fp@(-570)`
|   0x40084d4a  the bank load every bank but the current (the power-up's
|               path too): `mvzb 0x80000002,%d1`
| Each stub keeps every register, calls core_load and replays what the
| detour displaced.

        .include "remix.inc"           | core_fx, core_fx_n (manifest.py fx_inc)

        .text
        .globl  core_on_load, core_on_bankload
core_on_load:
        lea     %sp@(-16),%sp
        movem.l %d0-%d1/%a0-%a1,%sp@
        jsr     core_load
        movem.l %sp@,%d0-%d1/%a0-%a1
        lea     %sp@(16),%sp
        moveq   #27,%d1
        move.l  %d1,%fp@(-570)
        rts
core_on_bankload:
        lea     %sp@(-16),%sp
        movem.l %d0-%d1/%a0-%a1,%sp@
        jsr     core_load
        movem.l %sp@,%d0-%d1/%a0-%a1
        lea     %sp@(16),%sp
        mvz.b   0x80000002,%d1
        rts
