#!/usr/bin/env python3
"""Rebuild the ColdFire source consumed by Linked, or --check for drift.

The firmware builder accepts GNU-as units. Keep the core in C
and its compiler output together, without changing other modules' build.
"""
import pathlib
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[1]
FLAGS = ['-mcpu=5475', '-msoft-float', '-O2', '-ffreestanding', '-fno-builtin',
         '-fno-common', '-fno-jump-tables', '-fno-asynchronous-unwind-tables',
         '-fno-ident', '-fomit-frame-pointer']


def generate():
    with tempfile.TemporaryDirectory() as td:
        asm = pathlib.Path(td) / 'core.s'
        subprocess.run(['m68k-elf-gcc', *FLAGS, '-S',
                        'modules/core/core.c', '-o', str(asm)], cwd=ROOT, check=True)
        return ('| Generated by modules/core/generate_core.py; edit core.c / hooks.s.\n'
                + asm.read_text() + '\n' + (HERE / 'hooks.s').read_text())


if __name__ == '__main__':
    source = generate()
    dest = HERE / 'core.s'
    if '--check' in sys.argv:
        if not dest.exists() or source != dest.read_text():
            sys.exit('CORE core.s is stale: run modules/core/generate_core.py')
        print('CORE ColdFire source matches core.c and hooks.s')
    else:
        dest.write_text(source)
